/mnt/hwfile/huqinghao/miniconda3/bin/python
2024-05-16 17:53:45,544 - INFO - Note: detected 128 virtual cores but NumExpr set to maximum of 64, check "NUMEXPR_MAX_THREADS" environment variable.
2024-05-16 17:53:45,545 - INFO - Note: NumExpr detected 128 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
2024-05-16 17:53:45,545 - INFO - NumExpr defaulting to 8 threads.
2024-05-16 17:53:46,355	INFO scripts.py:1182 -- Did not find any active Ray processes.
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f306d0>: Failed to establish a new connection: [Errno 111] Connection refused'))

==========
== CUDA ==
==========

CUDA Version 12.1.0

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

*************************
** DEPRECATION NOTICE! **
*************************
THIS IMAGE IS DEPRECATED and is scheduled for DELETION.
    https://gitlab.com/nvidia/container-images/cuda/blob/master/doc/support-policy.md

Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f31450>: Failed to establish a new connection: [Errno 111] Connection refused'))
INFO 05-16 17:54:02 api_server.py:191] vLLM API server version 0.3.3
INFO 05-16 17:54:02 api_server.py:192] args: Namespace(host=None, port=8000, uvicorn_log_level='info', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_key=None, served_model_name=None, lora_modules=[], delta_modules=[Delta(name='delta-1', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-1'), Delta(name='delta-2', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-2'), Delta(name='delta-3', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-3'), Delta(name='delta-4', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-4'), Delta(name='delta-5', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-5'), Delta(name='delta-6', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-6'), Delta(name='delta-7', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-7'), Delta(name='delta-8', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-8'), Delta(name='delta-9', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-9'), Delta(name='delta-10', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-10'), Delta(name='delta-11', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-11'), Delta(name='delta-12', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-12'), Delta(name='delta-13', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-13'), Delta(name='delta-14', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-14'), Delta(name='delta-15', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-15'), Delta(name='delta-16', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-16'), Delta(name='delta-17', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-17'), Delta(name='delta-18', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-18'), Delta(name='delta-19', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-19'), Delta(name='delta-20', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-20'), Delta(name='delta-21', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-21'), Delta(name='delta-22', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-22'), Delta(name='delta-23', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-23'), Delta(name='delta-24', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-24'), Delta(name='delta-25', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-25'), Delta(name='delta-26', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-26'), Delta(name='delta-27', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-27'), Delta(name='delta-28', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-28'), Delta(name='delta-29', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-29'), Delta(name='delta-30', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-30'), Delta(name='delta-31', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-31'), Delta(name='delta-32', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-32')], swap_modules=[], chat_template=None, response_role='assistant', ssl_keyfile=None, ssl_certfile=None, ssl_ca_certs=None, ssl_cert_reqs=0, root_path=None, middleware=[], model='/vllm/.idea/full_models/Llama-2-13b-hf', tokenizer=None, revision=None, code_revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=False, download_dir=None, load_format='auto', dtype='auto', kv_cache_dtype='auto', max_model_len=None, worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=4, max_parallel_loading_workers=None, ray_workers_use_nsight=False, block_size=16, enable_prefix_caching=False, seed=0, swap_space=4, gpu_memory_utilization=0.85, max_num_batched_tokens=None, max_num_seqs=256, max_logprobs=5, disable_log_stats=False, quantization=None, enforce_eager=True, max_context_len_to_capture=8192, disable_custom_all_reduce=False, tokenizer_pool_size=0, tokenizer_pool_type='ray', tokenizer_pool_extra_config=None, enable_lora=False, max_loras=1, max_lora_rank=64, lora_extra_vocab_size=256, lora_dtype='auto', max_cpu_loras=32, enable_delta=True, max_deltas=24, max_cpu_deltas=32, max_delta_bitwidth=4, device='auto', image_input_type=None, image_token_id=None, image_input_shape=None, image_feature_size=None, scheduler_delay_factor=0.0, enable_prefetch=False, scheduler_policy='fcfs', max_swap_slots=1, max_cpu_models=4, enable_swap=False, engine_use_ray=False, disable_log_requests=True, max_log_len=None)
2024-05-16 17:54:05,813	INFO worker.py:1749 -- Started a local Ray instance.
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f31d20>: Failed to establish a new connection: [Errno 111] Connection refused'))
INFO 05-16 17:54:08 llm_engine.py:90] Initializing an LLM engine (v0.3.3) with config: model='/vllm/.idea/full_models/Llama-2-13b-hf', tokenizer='/vllm/.idea/full_models/Llama-2-13b-hf', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, lora_config=None, delta_config=DeltaConfig(max_deltas=24, max_bitwidth=4, delta_dtype=torch.int8, max_cpu_deltas=32, delta_extra_vocab_size=0, pack_factor=Fraction(2, 1), kernel=<QuantKernel.TRITON: 'triton'>), swap_config=None, max_seq_len=4096, download_dir=None, load_format=auto, tensor_parallel_size=4, disable_custom_all_reduce=False, quantization=None, enforce_eager=True, kv_cache_dtype=auto, device_config=cuda, seed=0)
INFO 05-16 17:54:08 llm_engine.py:243] ignored verifying delta_config
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f31150>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f30880>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f325f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f32ec0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f33790>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f329e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f32110>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f303d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f31390>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1afc0a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f33b20>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f313f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f30370>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f32140>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f33310>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f32a10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f32800>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f31f30>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f30ee0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f33cd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1afc370>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f33e80>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f31510>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f301f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f32350>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f32c50>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f337f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f326e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f30580>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f31030>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f33d90>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f31cf0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f33fa0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f31000>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f30070>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f32650>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f32980>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1afc070>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f30580>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f31030>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f33d90>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f31cf0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f0bb20>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f31540>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f31c00>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f33880>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f30dc0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f31ff0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1afc9a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f302b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f31270>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f33d30>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f33ee0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1afc400>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f31bd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f31ae0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f33850>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f31150>: Failed to establish a new connection: [Errno 111] Connection refused'))
Using bitblas
WARNING 05-16 18:03:54 models.py:48] Using bitblas delta modules
INFO 05-16 18:03:54 selector.py:16] Using FlashAttention backend.
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f304f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[36m(RayWorkerVllm pid=72443)[0m Exception ignored in: <function TempDirectory.__del__ at 0x7ecfcf1adcf0>
[36m(RayWorkerVllm pid=72443)[0m Traceback (most recent call last):
[36m(RayWorkerVllm pid=72443)[0m   File "/usr/local/lib/python3.10/dist-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 145, in __del__
[36m(RayWorkerVllm pid=72443)[0m     self.remove()
[36m(RayWorkerVllm pid=72443)[0m   File "/usr/local/lib/python3.10/dist-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 121, in remove
[36m(RayWorkerVllm pid=72443)[0m     if self.temp_dir:
[36m(RayWorkerVllm pid=72443)[0m AttributeError: 'TempDirectory' object has no attribute 'temp_dir'
[36m(RayWorkerVllm pid=72591)[0m Exception ignored in: <function TempDirectory.__del__ at 0x7f0ecbd11cf0>
[36m(RayWorkerVllm pid=72591)[0m Traceback (most recent call last):
[36m(RayWorkerVllm pid=72591)[0m   File "/usr/local/lib/python3.10/dist-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 145, in __del__
[36m(RayWorkerVllm pid=72591)[0m     self.remove()
[36m(RayWorkerVllm pid=72591)[0m   File "/usr/local/lib/python3.10/dist-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 121, in remove
[36m(RayWorkerVllm pid=72591)[0m     if self.temp_dir:
[36m(RayWorkerVllm pid=72591)[0m AttributeError: 'TempDirectory' object has no attribute 'temp_dir'
[36m(RayWorkerVllm pid=72591)[0m Exception ignored in: <function TempDirectory.__del__ at 0x7f0ecbd11cf0>
[36m(RayWorkerVllm pid=72591)[0m Traceback (most recent call last):
[36m(RayWorkerVllm pid=72591)[0m   File "/usr/local/lib/python3.10/dist-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 145, in __del__
[36m(RayWorkerVllm pid=72591)[0m     self.remove()
[36m(RayWorkerVllm pid=72591)[0m   File "/usr/local/lib/python3.10/dist-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 121, in remove
[36m(RayWorkerVllm pid=72591)[0m     if self.temp_dir:
[36m(RayWorkerVllm pid=72591)[0m AttributeError: 'TempDirectory' object has no attribute 'temp_dir'
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1afc040>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f30160>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f31420>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f33910>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f31a20>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1afcbe0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f33d00>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f31810>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f314b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f30220>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f325c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1afd270>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f32530>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f30730>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f31120>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f31c30>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1afc700>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f31540>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f31a20>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f33910>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f31420>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f30490>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1afca60>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f321a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f32440>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f30130>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f315d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1afd4e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f31660>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f311e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f30640>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f32410>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f321d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1afdb70>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f32500>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f30f70>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f33ac0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[36m(RayWorkerVllm pid=72591)[0m Exception ignored in: <function TempDirectory.__del__ at 0x7f0ecbd11cf0>
[36m(RayWorkerVllm pid=72591)[0m Traceback (most recent call last):
[36m(RayWorkerVllm pid=72591)[0m   File "/usr/local/lib/python3.10/dist-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 145, in __del__
[36m(RayWorkerVllm pid=72591)[0m     self.remove()
[36m(RayWorkerVllm pid=72591)[0m   File "/usr/local/lib/python3.10/dist-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 121, in remove
[36m(RayWorkerVllm pid=72591)[0m     if self.temp_dir:
[36m(RayWorkerVllm pid=72591)[0m AttributeError: 'TempDirectory' object has no attribute 'temp_dir'
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f310f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f32830>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f32230>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f31e40>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f32770>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f32380>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f30fd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1afd4b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f33820>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f33970>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f317b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f306a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f0bd60>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f329e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f32c50>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f31b40>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f31210>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f303a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1afd840>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f339a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f31600>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f31660>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f32b00>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1afd960>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f329e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f33f40>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f312a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f30eb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f339d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1afd000>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f30250>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f31300>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f316f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f329b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1afd6f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f32800>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f33f40>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f312a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f30eb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f311b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1afc2e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f30250>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f31300>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f316f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f329b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1afc5e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f33bb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f33f40>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f312a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f30eb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f30070>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1afe470>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f31ae0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[36m(RayWorkerVllm pid=72269)[0m Using bitblas
[36m(RayWorkerVllm pid=72443)[0m Using bitblas
[36m(RayWorkerVllm pid=72591)[0m Using bitblas
[36m(RayWorkerVllm pid=72443)[0m BitBLAS Operator not loaded, retrying in 5 seconds...
[36m(RayWorkerVllm pid=72443)[0m Error: [Errno 17] File exists: '/home/xiayao/.cache/bitblas/nvidia/nvidia-a100/c96df0f34eb23be516ef0126651d4e78b151337f28ebc87cc5492d79d135855f/tvm_rt_mod'
[36m(RayWorkerVllm pid=72591)[0m BitBLAS Operator not loaded, retrying in 5 seconds...
[36m(RayWorkerVllm pid=72591)[0m Error: [Errno 17] File exists: '/home/xiayao/.cache/bitblas/nvidia/nvidia-a100/c96df0f34eb23be516ef0126651d4e78b151337f28ebc87cc5492d79d135855f/tvm_rt_mod'
[36m(RayWorkerVllm pid=72591)[0m BitBLAS Operator not loaded, retrying in 5 seconds...
[36m(RayWorkerVllm pid=72591)[0m Error: [Errno 17] File exists: '/home/xiayao/.cache/bitblas/nvidia/nvidia-a100/c96df0f34eb23be516ef0126651d4e78b151337f28ebc87cc5492d79d135855f/tvm_rt_mod'
[36m(RayWorkerVllm pid=72591)[0m BitBLAS Operator not loaded, retrying in 5 seconds...
[36m(RayWorkerVllm pid=72591)[0m Error: [Errno 17] File exists: '/home/xiayao/.cache/bitblas/nvidia/nvidia-a100/f357498f99f799f093dedc4de224566345b2b3f2dc0d3306e2520ad45fd0496f/tvm_rt_mod'
[36m(RayWorkerVllm pid=72269)[0m WARNING 05-16 18:12:35 models.py:48] Using bitblas delta modules
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:12:36 selector.py:16] Using FlashAttention backend.
[36m(RayWorkerVllm pid=72443)[0m WARNING 05-16 18:12:43 models.py:48] Using bitblas delta modules
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:12:43 selector.py:16] Using FlashAttention backend.
[36m(RayWorkerVllm pid=72591)[0m WARNING 05-16 18:18:51 models.py:48] Using bitblas delta modules
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:18:51 selector.py:16] Using FlashAttention backend.
INFO 05-16 18:19:05 model_runner.py:161] Loading model weights took 6.1114 GB
INFO 05-16 18:19:05 worker_manager.py:297] Starting prefetching thread
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f328f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:19:06 model_runner.py:161] Loading model weights took 6.1114 GB
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:19:06 worker_manager.py:297] Starting prefetching thread
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:19:06 model_runner.py:161] Loading model weights took 6.1114 GB
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:19:06 worker_manager.py:297] Starting prefetching thread
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:19:06 model_runner.py:161] Loading model weights took 6.1114 GB
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:19:06 worker_manager.py:297] Starting prefetching thread
WARNING 05-16 18:19:08 quant_linear_triton.py:557] We should warm up the kernel here 
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23c1f32b90>: Failed to establish a new connection: [Errno 111] Connection refused'))
[36m(RayWorkerVllm pid=72269)[0m WARNING 05-16 18:19:10 quant_linear_triton.py:557] We should warm up the kernel here 
[36m(RayWorkerVllm pid=72591)[0m WARNING 05-16 18:19:10 quant_linear_triton.py:557] We should warm up the kernel here 
[36m(RayWorkerVllm pid=72443)[0m WARNING 05-16 18:19:10 quant_linear_triton.py:557] We should warm up the kernel here 
INFO 05-16 18:19:23 ray_gpu_executor.py:275] # GPU blocks: 6431, # CPU blocks: 1310
INFO 05-16 18:19:26 scheduler.py:136] Using fcfs policy.
INFO 05-16 18:19:26 block_manager.py:264] disable automatic prefix caching
WARNING 05-16 18:19:26 serving_chat.py:373] No chat template provided. Chat API will not work.
INFO:     Started server process [64205]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     ::1:44792 - "GET /sysinfo HTTP/1.1" 200 OK
Translating from base-model to /vllm/.idea/full_models/Llama-2-13b-hf
Warming up starts
{'id': 49, 'prompt': 'USER: What do you know about California Superbloom?\nASSISTANT:', 'timestamp': 0, 'model': 'delta-25', 'min_tokens': 193, 'max_tokens': 193}
Prefetching is disabled
WARNING 05-16 18:19:28 worker_manager.py:344] Missed prefetch, fall back to loading delta 25 now
[36m(RayWorkerVllm pid=72269)[0m WARNING 05-16 18:19:28 worker_manager.py:344] Missed prefetch, fall back to loading delta 25 now
[36m(RayWorkerVllm pid=72443)[0m WARNING 05-16 18:19:28 worker_manager.py:344] Missed prefetch, fall back to loading delta 25 now
[36m(RayWorkerVllm pid=72591)[0m WARNING 05-16 18:19:28 worker_manager.py:344] Missed prefetch, fall back to loading delta 25 now
INFO 05-16 18:19:28 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-16 18:19:28 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:19:28 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:19:28 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:19:28 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:19:28 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:19:28 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:19:28 models.py:263] [main] Lossless Compression Disabled
INFO 05-16 18:19:29 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.707 seconds
INFO 05-16 18:19:29 worker_manager.py:364] Main thread loading delta 25 done
INFO 05-16 18:19:29 worker_manager.py:379] [1715854769.9730546] activating delta
INFO 05-16 18:19:30 worker_manager.py:384] [1715854770.0749595] CPU -> GPU time: 0.1018
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:19:30 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.278 seconds
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:19:30 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.339 seconds
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:19:30 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.317 seconds
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:19:30 worker_manager.py:364] Main thread loading delta 25 done
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:19:30 worker_manager.py:379] [1715854770.5587862] activating delta
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:19:30 worker_manager.py:364] Main thread loading delta 25 done
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:19:30 worker_manager.py:379] [1715854770.608322] activating delta
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:19:30 worker_manager.py:364] Main thread loading delta 25 done
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:19:30 worker_manager.py:379] [1715854770.595419] activating delta
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:19:30 worker_manager.py:384] [1715854770.741115] CPU -> GPU time: 0.1327
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:19:30 worker_manager.py:384] [1715854770.7122881] CPU -> GPU time: 0.1535
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:19:30 worker_manager.py:384] [1715854770.7542148] CPU -> GPU time: 0.1587
INFO 05-16 18:19:31 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
INFO 05-16 18:19:36 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
INFO 05-16 18:19:41 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%
INFO 05-16 18:19:46 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 3.9 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%
INFO 05-16 18:19:51 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.2 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%
INFO 05-16 18:19:56 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.1 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%
INFO 05-16 18:20:02 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.1 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%
INFO 05-16 18:20:07 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.1 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.2%, CPU KV cache usage: 0.0%
INFO 05-16 18:20:12 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.1 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.2%, CPU KV cache usage: 0.0%
INFO 05-16 18:20:17 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.1 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.2%, CPU KV cache usage: 0.0%
INFO:     ::1:44794 - "POST /v1/completions HTTP/1.1" 200 OK
Warming up ends
Issuing queries
sending 1 queries at 0.4
sending 1 queries at 1.1
sending 1 queries at 1.5
sending 1 queries at 1.9000000000000001
sending 1 queries at 2.2
sending 1 queries at 2.7
sending 1 queries at 3.0
sending 1 queries at 4.1000000000000005
sending 1 queries at 5.800000000000001
sending 1 queries at 6.0
sending 1 queries at 6.800000000000001
sending 1 queries at 7.2
sending 1 queries at 7.6000000000000005
sending 2 queries at 8.9
sending 2 queries at 9.0
sending 1 queries at 9.9
sending 1 queries at 10.600000000000001
sending 1 queries at 11.700000000000001
sending 1 queries at 13.600000000000001
sending 1 queries at 14.4
sending 1 queries at 14.700000000000001
sending 2 queries at 15.5
sending 1 queries at 16.0
sending 1 queries at 16.1
sending 1 queries at 17.6
sending 1 queries at 17.900000000000002
sending 1 queries at 18.2
sending 1 queries at 18.3
sending 1 queries at 19.1
sending 1 queries at 19.400000000000002
sending 2 queries at 19.8
sending 1 queries at 20.3
sending 1 queries at 20.8
sending 1 queries at 21.3
sending 1 queries at 22.700000000000003
sending 1 queries at 23.3
sending 1 queries at 23.5
sending 1 queries at 23.8
sending 2 queries at 24.400000000000002
sending 1 queries at 25.0
sending 1 queries at 25.5
sending 1 queries at 25.6
sending 1 queries at 25.700000000000003
sending 1 queries at 25.900000000000002
sending 1 queries at 26.1
sending 1 queries at 26.5
sending 1 queries at 26.8
sending 2 queries at 29.1
sending 1 queries at 29.200000000000003
sending 1 queries at 29.3
sending 1 queries at 29.8
sending 1 queries at 30.0
Prefetching is disabled
WARNING 05-16 18:20:18 worker_manager.py:344] Missed prefetch, fall back to loading delta 13 now
[36m(RayWorkerVllm pid=72269)[0m WARNING 05-16 18:20:18 worker_manager.py:344] Missed prefetch, fall back to loading delta 13 now
[36m(RayWorkerVllm pid=72443)[0m WARNING 05-16 18:20:18 worker_manager.py:344] Missed prefetch, fall back to loading delta 13 now
[36m(RayWorkerVllm pid=72591)[0m WARNING 05-16 18:20:18 worker_manager.py:344] Missed prefetch, fall back to loading delta 13 now
INFO 05-16 18:20:18 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-16 18:20:18 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:20:18 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:20:18 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:20:18 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:20:18 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:20:18 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:20:18 models.py:263] [main] Lossless Compression Disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
INFO 05-16 18:20:21 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.126 seconds
INFO 05-16 18:20:21 worker_manager.py:364] Main thread loading delta 13 done
Prefetching is disabled
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:20:21 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.483 seconds
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:20:21 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.586 seconds
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:20:21 worker_manager.py:364] Main thread loading delta 13 done
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:20:21 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.581 seconds
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:20:21 worker_manager.py:364] Main thread loading delta 13 done
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:20:21 worker_manager.py:364] Main thread loading delta 13 done
Prefetching is disabled
WARNING 05-16 18:20:22 worker_manager.py:344] Missed prefetch, fall back to loading delta 2 now
INFO 05-16 18:20:22 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-16 18:20:22 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72269)[0m WARNING 05-16 18:20:22 worker_manager.py:344] Missed prefetch, fall back to loading delta 2 now
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:20:22 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:20:22 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72443)[0m WARNING 05-16 18:20:22 worker_manager.py:344] Missed prefetch, fall back to loading delta 2 now
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:20:22 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:20:22 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72591)[0m WARNING 05-16 18:20:22 worker_manager.py:344] Missed prefetch, fall back to loading delta 2 now
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:20:22 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:20:22 models.py:263] [main] Lossless Compression Disabled
Prefetching is disabled
INFO 05-16 18:20:23 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.601 seconds
INFO 05-16 18:20:23 worker_manager.py:364] Main thread loading delta 2 done
WARNING 05-16 18:20:23 worker_manager.py:344] Missed prefetch, fall back to loading delta 9 now
INFO 05-16 18:20:23 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-16 18:20:23 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:20:24 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.068 seconds
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:20:24 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.086 seconds
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:20:24 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.111 seconds
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:20:24 worker_manager.py:364] Main thread loading delta 2 done
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:20:24 worker_manager.py:364] Main thread loading delta 2 done
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:20:24 worker_manager.py:364] Main thread loading delta 2 done
Prefetching is disabled
[36m(RayWorkerVllm pid=72269)[0m WARNING 05-16 18:20:24 worker_manager.py:344] Missed prefetch, fall back to loading delta 9 now
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:20:24 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:20:24 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72443)[0m WARNING 05-16 18:20:24 worker_manager.py:344] Missed prefetch, fall back to loading delta 9 now
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:20:24 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:20:24 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72591)[0m WARNING 05-16 18:20:24 worker_manager.py:344] Missed prefetch, fall back to loading delta 9 now
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:20:24 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:20:24 models.py:263] [main] Lossless Compression Disabled
Prefetching is disabled
Prefetching is disabled
INFO 05-16 18:20:25 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.646 seconds
INFO 05-16 18:20:25 worker_manager.py:364] Main thread loading delta 9 done
WARNING 05-16 18:20:25 worker_manager.py:344] Missed prefetch, fall back to loading delta 10 now
INFO 05-16 18:20:25 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-16 18:20:25 models.py:263] [main] Lossless Compression Disabled
Prefetching is disabled
Prefetching is disabled
INFO 05-16 18:20:26 metrics.py:276] Avg prompt throughput: 2.3 tokens/s, Avg generation throughput: 0.6 tokens/s, Running: 7 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.2%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:20:26 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.199 seconds
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:20:26 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.177 seconds
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:20:26 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.243 seconds
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:20:26 worker_manager.py:364] Main thread loading delta 9 done
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:20:26 worker_manager.py:364] Main thread loading delta 9 done
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:20:26 worker_manager.py:364] Main thread loading delta 9 done
[36m(RayWorkerVllm pid=72269)[0m WARNING 05-16 18:20:26 worker_manager.py:344] Missed prefetch, fall back to loading delta 10 now
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:20:26 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:20:26 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72443)[0m WARNING 05-16 18:20:26 worker_manager.py:344] Missed prefetch, fall back to loading delta 10 now
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:20:26 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:20:26 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72591)[0m WARNING 05-16 18:20:26 worker_manager.py:344] Missed prefetch, fall back to loading delta 10 now
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:20:26 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:20:26 models.py:263] [main] Lossless Compression Disabled
INFO 05-16 18:20:27 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.625 seconds
INFO 05-16 18:20:27 worker_manager.py:364] Main thread loading delta 10 done
Prefetching is disabled
Prefetching is disabled
WARNING 05-16 18:20:27 worker_manager.py:344] Missed prefetch, fall back to loading delta 21 now
INFO 05-16 18:20:27 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-16 18:20:27 models.py:263] [main] Lossless Compression Disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:20:28 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.127 seconds
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:20:28 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.161 seconds
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:20:29 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.165 seconds
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:20:29 worker_manager.py:364] Main thread loading delta 10 done
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:20:29 worker_manager.py:364] Main thread loading delta 10 done
INFO 05-16 18:20:29 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.602 seconds
INFO 05-16 18:20:29 worker_manager.py:364] Main thread loading delta 21 done
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:20:29 worker_manager.py:364] Main thread loading delta 10 done
[36m(RayWorkerVllm pid=72443)[0m WARNING 05-16 18:20:29 worker_manager.py:344] Missed prefetch, fall back to loading delta 21 now
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:20:29 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:20:29 models.py:263] [main] Lossless Compression Disabled
Prefetching is disabled
[36m(RayWorkerVllm pid=72269)[0m WARNING 05-16 18:20:29 worker_manager.py:344] Missed prefetch, fall back to loading delta 21 now
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:20:29 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:20:29 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72591)[0m WARNING 05-16 18:20:29 worker_manager.py:344] Missed prefetch, fall back to loading delta 21 now
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:20:29 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:20:29 models.py:263] [main] Lossless Compression Disabled
WARNING 05-16 18:20:29 worker_manager.py:344] Missed prefetch, fall back to loading delta 23 now
INFO 05-16 18:20:29 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-16 18:20:29 models.py:263] [main] Lossless Compression Disabled
Prefetching is disabled
INFO 05-16 18:20:30 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.613 seconds
INFO 05-16 18:20:31 worker_manager.py:364] Main thread loading delta 23 done
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:20:31 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.134 seconds
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:20:31 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.118 seconds
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:20:31 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.145 seconds
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:20:31 worker_manager.py:364] Main thread loading delta 21 done
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:20:31 worker_manager.py:364] Main thread loading delta 21 done
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:20:31 worker_manager.py:364] Main thread loading delta 21 done
[36m(RayWorkerVllm pid=72269)[0m WARNING 05-16 18:20:31 worker_manager.py:344] Missed prefetch, fall back to loading delta 23 now
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:20:31 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:20:31 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72443)[0m WARNING 05-16 18:20:31 worker_manager.py:344] Missed prefetch, fall back to loading delta 23 now
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:20:31 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:20:31 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72591)[0m WARNING 05-16 18:20:31 worker_manager.py:344] Missed prefetch, fall back to loading delta 23 now
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:20:31 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:20:31 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:20:33 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.028 seconds
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:20:33 worker_manager.py:364] Main thread loading delta 23 done
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:20:33 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.027 seconds
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:20:33 worker_manager.py:364] Main thread loading delta 23 done
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:20:33 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.079 seconds
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:20:33 worker_manager.py:364] Main thread loading delta 23 done
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
INFO 05-16 18:20:34 metrics.py:276] Avg prompt throughput: 14.2 tokens/s, Avg generation throughput: 0.7 tokens/s, Running: 7 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.2%, CPU KV cache usage: 0.0%
WARNING 05-16 18:20:34 worker_manager.py:344] Missed prefetch, fall back to loading delta 32 now
INFO 05-16 18:20:34 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-16 18:20:34 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72269)[0m WARNING 05-16 18:20:34 worker_manager.py:344] Missed prefetch, fall back to loading delta 32 now
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:20:34 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:20:34 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72443)[0m WARNING 05-16 18:20:34 worker_manager.py:344] Missed prefetch, fall back to loading delta 32 now
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:20:34 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:20:34 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72591)[0m WARNING 05-16 18:20:34 worker_manager.py:344] Missed prefetch, fall back to loading delta 32 now
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:20:34 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:20:34 models.py:263] [main] Lossless Compression Disabled
Prefetching is disabled
Prefetching is disabled
INFO 05-16 18:20:36 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.546 seconds
INFO 05-16 18:20:36 worker_manager.py:364] Main thread loading delta 32 done
WARNING 05-16 18:20:36 worker_manager.py:344] Missed prefetch, fall back to loading delta 1 now
INFO 05-16 18:20:36 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-16 18:20:36 models.py:263] [main] Lossless Compression Disabled
Prefetching is disabled
Prefetching is disabled
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:20:37 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.045 seconds
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:20:37 worker_manager.py:364] Main thread loading delta 32 done
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:20:37 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.072 seconds
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:20:37 worker_manager.py:364] Main thread loading delta 32 done
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:20:37 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.146 seconds
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:20:37 worker_manager.py:364] Main thread loading delta 32 done
[36m(RayWorkerVllm pid=72443)[0m WARNING 05-16 18:20:37 worker_manager.py:344] Missed prefetch, fall back to loading delta 1 now
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:20:37 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:20:37 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72269)[0m WARNING 05-16 18:20:37 worker_manager.py:344] Missed prefetch, fall back to loading delta 1 now
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:20:37 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:20:37 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72591)[0m WARNING 05-16 18:20:37 worker_manager.py:344] Missed prefetch, fall back to loading delta 1 now
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:20:37 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:20:37 models.py:263] [main] Lossless Compression Disabled
Prefetching is disabled
Prefetching is disabled
INFO 05-16 18:20:38 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.545 seconds
INFO 05-16 18:20:38 worker_manager.py:364] Main thread loading delta 1 done
Prefetching is disabled
Prefetching is disabled
WARNING 05-16 18:20:38 worker_manager.py:344] Missed prefetch, fall back to loading delta 3 now
INFO 05-16 18:20:38 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-16 18:20:38 models.py:263] [main] Lossless Compression Disabled
Prefetching is disabled
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:20:39 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.042 seconds
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:20:39 worker_manager.py:364] Main thread loading delta 1 done
Prefetching is disabled
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:20:39 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.067 seconds
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:20:39 worker_manager.py:364] Main thread loading delta 1 done
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:20:39 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.122 seconds
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:20:39 worker_manager.py:364] Main thread loading delta 1 done
[36m(RayWorkerVllm pid=72443)[0m WARNING 05-16 18:20:39 worker_manager.py:344] Missed prefetch, fall back to loading delta 3 now
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:20:39 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:20:39 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72591)[0m WARNING 05-16 18:20:39 worker_manager.py:344] Missed prefetch, fall back to loading delta 3 now
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:20:39 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:20:39 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72269)[0m WARNING 05-16 18:20:39 worker_manager.py:344] Missed prefetch, fall back to loading delta 3 now
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:20:39 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:20:39 models.py:263] [main] Lossless Compression Disabled
Prefetching is disabled
INFO 05-16 18:20:40 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.600 seconds
INFO 05-16 18:20:40 worker_manager.py:364] Main thread loading delta 3 done
WARNING 05-16 18:20:40 worker_manager.py:344] Missed prefetch, fall back to loading delta 11 now
INFO 05-16 18:20:40 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-16 18:20:40 models.py:263] [main] Lossless Compression Disabled
Prefetching is disabled
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:20:41 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.173 seconds
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:20:41 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.120 seconds
INFO 05-16 18:20:41 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.558 seconds
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:20:41 worker_manager.py:364] Main thread loading delta 3 done
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:20:41 worker_manager.py:364] Main thread loading delta 3 done
INFO 05-16 18:20:41 worker_manager.py:364] Main thread loading delta 11 done
Prefetching is disabled
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:20:41 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.209 seconds
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:20:41 worker_manager.py:364] Main thread loading delta 3 done
[36m(RayWorkerVllm pid=72443)[0m WARNING 05-16 18:20:41 worker_manager.py:344] Missed prefetch, fall back to loading delta 11 now
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:20:41 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:20:41 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72591)[0m WARNING 05-16 18:20:41 worker_manager.py:344] Missed prefetch, fall back to loading delta 11 now
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:20:41 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:20:41 models.py:263] [main] Lossless Compression Disabled
WARNING 05-16 18:20:41 worker_manager.py:344] Missed prefetch, fall back to loading delta 14 now
INFO 05-16 18:20:41 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-16 18:20:41 models.py:263] [main] Lossless Compression Disabled
Prefetching is disabled
[36m(RayWorkerVllm pid=72269)[0m WARNING 05-16 18:20:42 worker_manager.py:344] Missed prefetch, fall back to loading delta 11 now
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:20:42 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:20:42 models.py:263] [main] Lossless Compression Disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
INFO 05-16 18:20:43 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.586 seconds
INFO 05-16 18:20:43 worker_manager.py:364] Main thread loading delta 14 done
Prefetching is disabled
WARNING 05-16 18:20:43 worker_manager.py:344] Missed prefetch, fall back to loading delta 16 now
INFO 05-16 18:20:43 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-16 18:20:43 models.py:263] [main] Lossless Compression Disabled
Prefetching is disabled
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:20:44 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.119 seconds
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:20:44 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.144 seconds
Prefetching is disabled
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:20:44 worker_manager.py:364] Main thread loading delta 11 done
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:20:44 worker_manager.py:364] Main thread loading delta 11 done
Prefetching is disabled
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:20:44 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.183 seconds
[36m(RayWorkerVllm pid=72443)[0m WARNING 05-16 18:20:44 worker_manager.py:344] Missed prefetch, fall back to loading delta 14 now
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:20:44 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:20:44 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72591)[0m WARNING 05-16 18:20:44 worker_manager.py:344] Missed prefetch, fall back to loading delta 14 now
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:20:44 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:20:44 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:20:44 worker_manager.py:364] Main thread loading delta 11 done
Prefetching is disabled
[36m(RayWorkerVllm pid=72269)[0m WARNING 05-16 18:20:44 worker_manager.py:344] Missed prefetch, fall back to loading delta 14 now
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:20:44 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:20:44 models.py:263] [main] Lossless Compression Disabled
Prefetching is disabled
Prefetching is disabled
INFO 05-16 18:20:45 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.573 seconds
INFO 05-16 18:20:45 worker_manager.py:364] Main thread loading delta 16 done
Prefetching is disabled
WARNING 05-16 18:20:45 worker_manager.py:344] Missed prefetch, fall back to loading delta 17 now
INFO 05-16 18:20:45 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-16 18:20:45 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:20:46 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.096 seconds
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:20:46 worker_manager.py:364] Main thread loading delta 14 done
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:20:46 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.153 seconds
INFO 05-16 18:20:46 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 27 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.9%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=72443)[0m WARNING 05-16 18:20:46 worker_manager.py:344] Missed prefetch, fall back to loading delta 16 now
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:20:46 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:20:46 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:20:46 worker_manager.py:364] Main thread loading delta 14 done
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:20:46 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.162 seconds
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:20:46 worker_manager.py:364] Main thread loading delta 14 done
[36m(RayWorkerVllm pid=72591)[0m WARNING 05-16 18:20:46 worker_manager.py:344] Missed prefetch, fall back to loading delta 16 now
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:20:46 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:20:46 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72269)[0m WARNING 05-16 18:20:46 worker_manager.py:344] Missed prefetch, fall back to loading delta 16 now
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:20:46 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:20:46 models.py:263] [main] Lossless Compression Disabled
INFO 05-16 18:20:47 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.556 seconds
INFO 05-16 18:20:47 worker_manager.py:364] Main thread loading delta 17 done
WARNING 05-16 18:20:47 worker_manager.py:344] Missed prefetch, fall back to loading delta 18 now
INFO 05-16 18:20:47 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-16 18:20:47 models.py:263] [main] Lossless Compression Disabled
total threads: 58
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:20:48 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.088 seconds
INFO 05-16 18:20:48 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.567 seconds
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:20:48 worker_manager.py:364] Main thread loading delta 16 done
INFO 05-16 18:20:48 worker_manager.py:364] Main thread loading delta 18 done
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:20:48 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.109 seconds
[36m(RayWorkerVllm pid=72443)[0m WARNING 05-16 18:20:48 worker_manager.py:344] Missed prefetch, fall back to loading delta 17 now
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:20:48 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:20:48 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:20:48 worker_manager.py:364] Main thread loading delta 16 done
WARNING 05-16 18:20:48 worker_manager.py:344] Missed prefetch, fall back to loading delta 19 now
INFO 05-16 18:20:48 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-16 18:20:48 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:20:48 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.151 seconds
[36m(RayWorkerVllm pid=72591)[0m WARNING 05-16 18:20:48 worker_manager.py:344] Missed prefetch, fall back to loading delta 17 now
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:20:48 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:20:48 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:20:49 worker_manager.py:364] Main thread loading delta 16 done
[36m(RayWorkerVllm pid=72269)[0m WARNING 05-16 18:20:49 worker_manager.py:344] Missed prefetch, fall back to loading delta 17 now
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:20:49 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:20:49 models.py:263] [main] Lossless Compression Disabled
INFO 05-16 18:20:50 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.557 seconds
INFO 05-16 18:20:50 worker_manager.py:364] Main thread loading delta 19 done
WARNING 05-16 18:20:50 worker_manager.py:344] Missed prefetch, fall back to loading delta 20 now
INFO 05-16 18:20:50 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-16 18:20:50 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:20:50 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.057 seconds
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:20:50 worker_manager.py:364] Main thread loading delta 17 done
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:20:51 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.043 seconds
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:20:51 worker_manager.py:364] Main thread loading delta 17 done
[36m(RayWorkerVllm pid=72443)[0m WARNING 05-16 18:20:51 worker_manager.py:344] Missed prefetch, fall back to loading delta 18 now
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:20:51 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:20:51 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:20:51 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.118 seconds
[36m(RayWorkerVllm pid=72591)[0m WARNING 05-16 18:20:51 worker_manager.py:344] Missed prefetch, fall back to loading delta 18 now
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:20:51 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:20:51 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:20:51 worker_manager.py:364] Main thread loading delta 17 done
[36m(RayWorkerVllm pid=72269)[0m WARNING 05-16 18:20:51 worker_manager.py:344] Missed prefetch, fall back to loading delta 18 now
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:20:51 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:20:51 models.py:263] [main] Lossless Compression Disabled
INFO 05-16 18:20:52 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.544 seconds
INFO 05-16 18:20:52 worker_manager.py:364] Main thread loading delta 20 done
WARNING 05-16 18:20:52 worker_manager.py:344] Missed prefetch, fall back to loading delta 22 now
INFO 05-16 18:20:52 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-16 18:20:52 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:20:53 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.119 seconds
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:20:53 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.057 seconds
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:20:53 worker_manager.py:364] Main thread loading delta 18 done
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:20:53 worker_manager.py:364] Main thread loading delta 18 done
[36m(RayWorkerVllm pid=72443)[0m WARNING 05-16 18:20:53 worker_manager.py:344] Missed prefetch, fall back to loading delta 19 now
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:20:53 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:20:53 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72591)[0m WARNING 05-16 18:20:53 worker_manager.py:344] Missed prefetch, fall back to loading delta 19 now
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:20:53 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:20:53 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:20:53 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.147 seconds
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:20:53 worker_manager.py:364] Main thread loading delta 18 done
[36m(RayWorkerVllm pid=72269)[0m WARNING 05-16 18:20:53 worker_manager.py:344] Missed prefetch, fall back to loading delta 19 now
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:20:53 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:20:53 models.py:263] [main] Lossless Compression Disabled
INFO 05-16 18:20:53 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.548 seconds
INFO 05-16 18:20:54 worker_manager.py:364] Main thread loading delta 22 done
WARNING 05-16 18:20:54 worker_manager.py:344] Missed prefetch, fall back to loading delta 24 now
INFO 05-16 18:20:54 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-16 18:20:54 models.py:263] [main] Lossless Compression Disabled
INFO 05-16 18:20:55 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.579 seconds
INFO 05-16 18:20:55 worker_manager.py:364] Main thread loading delta 24 done
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:20:55 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.258 seconds
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:20:55 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.218 seconds
WARNING 05-16 18:20:55 worker_manager.py:344] Missed prefetch, fall back to loading delta 27 now
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:20:55 worker_manager.py:364] Main thread loading delta 19 done
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:20:55 worker_manager.py:364] Main thread loading delta 19 done
INFO 05-16 18:20:55 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-16 18:20:55 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72443)[0m WARNING 05-16 18:20:56 worker_manager.py:344] Missed prefetch, fall back to loading delta 20 now
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:20:56 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:20:56 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72591)[0m WARNING 05-16 18:20:56 worker_manager.py:344] Missed prefetch, fall back to loading delta 20 now
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:20:56 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:20:56 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:20:56 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.295 seconds
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:20:56 worker_manager.py:364] Main thread loading delta 19 done
[36m(RayWorkerVllm pid=72269)[0m WARNING 05-16 18:20:56 worker_manager.py:344] Missed prefetch, fall back to loading delta 20 now
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:20:56 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:20:56 models.py:263] [main] Lossless Compression Disabled
INFO 05-16 18:20:56 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 27 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.9%, CPU KV cache usage: 0.0%
INFO 05-16 18:20:57 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.582 seconds
INFO 05-16 18:20:57 worker_manager.py:364] Main thread loading delta 27 done
WARNING 05-16 18:20:57 worker_manager.py:344] Missed prefetch, fall back to loading delta 30 now
INFO 05-16 18:20:57 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-16 18:20:57 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:20:58 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.082 seconds
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:20:58 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.146 seconds
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:20:58 worker_manager.py:364] Main thread loading delta 20 done
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:20:58 worker_manager.py:364] Main thread loading delta 20 done
[36m(RayWorkerVllm pid=72591)[0m WARNING 05-16 18:20:58 worker_manager.py:344] Missed prefetch, fall back to loading delta 22 now
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:20:58 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:20:58 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72443)[0m WARNING 05-16 18:20:58 worker_manager.py:344] Missed prefetch, fall back to loading delta 22 now
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:20:58 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:20:58 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:20:58 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.158 seconds
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:20:58 worker_manager.py:364] Main thread loading delta 20 done
[36m(RayWorkerVllm pid=72269)[0m WARNING 05-16 18:20:58 worker_manager.py:344] Missed prefetch, fall back to loading delta 22 now
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:20:58 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:20:58 models.py:263] [main] Lossless Compression Disabled
INFO 05-16 18:20:59 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.559 seconds
INFO 05-16 18:20:59 worker_manager.py:364] Main thread loading delta 30 done
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:21:00 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.031 seconds
INFO 05-16 18:21:07 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 27 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.9%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:21:00 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.033 seconds
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:21:00 worker_manager.py:364] Main thread loading delta 22 done
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:21:00 worker_manager.py:364] Main thread loading delta 22 done
[36m(RayWorkerVllm pid=72591)[0m WARNING 05-16 18:21:00 worker_manager.py:344] Missed prefetch, fall back to loading delta 24 now
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:21:00 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:21:00 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72443)[0m WARNING 05-16 18:21:00 worker_manager.py:344] Missed prefetch, fall back to loading delta 24 now
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:21:00 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:21:00 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:21:00 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.058 seconds
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:21:00 worker_manager.py:364] Main thread loading delta 22 done
[36m(RayWorkerVllm pid=72269)[0m WARNING 05-16 18:21:01 worker_manager.py:344] Missed prefetch, fall back to loading delta 24 now
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:21:01 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:21:01 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:21:02 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.980 seconds
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:21:02 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.965 seconds
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:21:02 worker_manager.py:364] Main thread loading delta 24 done
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:21:02 worker_manager.py:364] Main thread loading delta 24 done
[36m(RayWorkerVllm pid=72443)[0m WARNING 05-16 18:21:02 worker_manager.py:344] Missed prefetch, fall back to loading delta 27 now
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:21:02 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:21:02 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72591)[0m WARNING 05-16 18:21:02 worker_manager.py:344] Missed prefetch, fall back to loading delta 27 now
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:21:02 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:21:02 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:21:03 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.008 seconds
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:21:03 worker_manager.py:364] Main thread loading delta 24 done
[36m(RayWorkerVllm pid=72269)[0m WARNING 05-16 18:21:03 worker_manager.py:344] Missed prefetch, fall back to loading delta 27 now
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:21:03 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:21:03 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:21:04 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.961 seconds
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:21:04 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.985 seconds
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:21:04 worker_manager.py:364] Main thread loading delta 27 done
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:21:04 worker_manager.py:364] Main thread loading delta 27 done
[36m(RayWorkerVllm pid=72591)[0m WARNING 05-16 18:21:04 worker_manager.py:344] Missed prefetch, fall back to loading delta 30 now
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:21:04 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:21:04 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72443)[0m WARNING 05-16 18:21:05 worker_manager.py:344] Missed prefetch, fall back to loading delta 30 now
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:21:05 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:21:05 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:21:05 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.988 seconds
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:21:05 worker_manager.py:364] Main thread loading delta 27 done
[36m(RayWorkerVllm pid=72269)[0m WARNING 05-16 18:21:05 worker_manager.py:344] Missed prefetch, fall back to loading delta 30 now
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:21:05 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:21:05 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:21:07 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.044 seconds
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:21:07 worker_manager.py:364] Main thread loading delta 30 done
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:21:07 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.165 seconds
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:21:07 worker_manager.py:364] Main thread loading delta 30 done
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:21:07 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.075 seconds
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:21:07 worker_manager.py:364] Main thread loading delta 30 done
INFO:     ::1:44988 - "POST /v1/completions HTTP/1.1" 200 OK
WARNING 05-16 18:21:11 worker_manager.py:344] Missed prefetch, fall back to loading delta 8 now
INFO 05-16 18:21:11 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-16 18:21:11 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72269)[0m WARNING 05-16 18:21:11 worker_manager.py:344] Missed prefetch, fall back to loading delta 8 now
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:21:11 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:21:11 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72443)[0m WARNING 05-16 18:21:11 worker_manager.py:344] Missed prefetch, fall back to loading delta 8 now
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:21:11 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:21:11 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72591)[0m WARNING 05-16 18:21:11 worker_manager.py:344] Missed prefetch, fall back to loading delta 8 now
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:21:11 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:21:11 models.py:263] [main] Lossless Compression Disabled
INFO 05-16 18:21:13 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.882 seconds
INFO 05-16 18:21:13 worker_manager.py:364] Main thread loading delta 8 done
WARNING 05-16 18:21:13 worker_manager.py:344] Missed prefetch, fall back to loading delta 26 now
INFO 05-16 18:21:13 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-16 18:21:13 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:21:13 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.190 seconds
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:21:13 worker_manager.py:364] Main thread loading delta 8 done
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:21:13 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.298 seconds
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:21:13 worker_manager.py:364] Main thread loading delta 8 done
[36m(RayWorkerVllm pid=72443)[0m WARNING 05-16 18:21:13 worker_manager.py:344] Missed prefetch, fall back to loading delta 26 now
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:21:13 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:21:13 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:21:13 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.401 seconds
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:21:13 worker_manager.py:364] Main thread loading delta 8 done
[36m(RayWorkerVllm pid=72269)[0m WARNING 05-16 18:21:13 worker_manager.py:344] Missed prefetch, fall back to loading delta 26 now
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:21:13 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:21:13 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72591)[0m WARNING 05-16 18:21:14 worker_manager.py:344] Missed prefetch, fall back to loading delta 26 now
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:21:14 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:21:14 models.py:263] [main] Lossless Compression Disabled
INFO 05-16 18:21:15 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.838 seconds
INFO 05-16 18:21:15 worker_manager.py:364] Main thread loading delta 26 done
WARNING 05-16 18:21:15 worker_manager.py:344] Missed prefetch, fall back to loading delta 31 now
INFO 05-16 18:21:15 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-16 18:21:15 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:21:16 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.262 seconds
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:21:16 worker_manager.py:364] Main thread loading delta 26 done
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:21:16 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.289 seconds
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:21:16 worker_manager.py:364] Main thread loading delta 26 done
[36m(RayWorkerVllm pid=72443)[0m WARNING 05-16 18:21:16 worker_manager.py:344] Missed prefetch, fall back to loading delta 31 now
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:21:16 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:21:16 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72269)[0m WARNING 05-16 18:21:16 worker_manager.py:344] Missed prefetch, fall back to loading delta 31 now
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:21:16 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:21:16 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:21:16 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.531 seconds
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:21:16 worker_manager.py:364] Main thread loading delta 26 done
[36m(RayWorkerVllm pid=72591)[0m WARNING 05-16 18:21:16 worker_manager.py:344] Missed prefetch, fall back to loading delta 31 now
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:21:16 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:21:16 models.py:263] [main] Lossless Compression Disabled
INFO 05-16 18:21:17 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.856 seconds
INFO 05-16 18:21:17 worker_manager.py:364] Main thread loading delta 31 done
INFO 05-16 18:21:17 metrics.py:276] Avg prompt throughput: 57.4 tokens/s, Avg generation throughput: 2.0 tokens/s, Running: 52 reqs, Swapped: 0 reqs, Pending: 5 reqs, GPU KV cache usage: 1.9%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:21:18 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.139 seconds
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:21:18 worker_manager.py:364] Main thread loading delta 31 done
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:21:18 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.204 seconds
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:21:18 worker_manager.py:364] Main thread loading delta 31 done
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:21:19 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.317 seconds
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:21:19 worker_manager.py:364] Main thread loading delta 31 done
INFO 05-16 18:21:23 metrics.py:276] Avg prompt throughput: 138.1 tokens/s, Avg generation throughput: 4.4 tokens/s, Running: 52 reqs, Swapped: 0 reqs, Pending: 5 reqs, GPU KV cache usage: 1.9%, CPU KV cache usage: 0.0%
INFO:     ::1:45042 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-16 18:21:30 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 16.1 tokens/s, Running: 51 reqs, Swapped: 0 reqs, Pending: 5 reqs, GPU KV cache usage: 1.9%, CPU KV cache usage: 0.0%
INFO 05-16 18:21:36 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 15.8 tokens/s, Running: 49 reqs, Swapped: 0 reqs, Pending: 5 reqs, GPU KV cache usage: 2.0%, CPU KV cache usage: 0.0%
INFO:     ::1:44972 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:45032 - "POST /v1/completions HTTP/1.1" 200 OK
WARNING 05-16 18:21:36 worker_manager.py:344] Missed prefetch, fall back to loading delta 4 now
INFO 05-16 18:21:36 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-16 18:21:36 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72269)[0m WARNING 05-16 18:21:36 worker_manager.py:344] Missed prefetch, fall back to loading delta 4 now
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:21:36 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:21:36 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72443)[0m WARNING 05-16 18:21:36 worker_manager.py:344] Missed prefetch, fall back to loading delta 4 now
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:21:36 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:21:36 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72591)[0m WARNING 05-16 18:21:36 worker_manager.py:344] Missed prefetch, fall back to loading delta 4 now
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:21:36 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:21:36 models.py:263] [main] Lossless Compression Disabled
INFO 05-16 18:21:38 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.599 seconds
INFO 05-16 18:21:38 worker_manager.py:364] Main thread loading delta 4 done
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:21:38 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.146 seconds
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:21:38 worker_manager.py:364] Main thread loading delta 4 done
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:21:38 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.197 seconds
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:21:38 worker_manager.py:364] Main thread loading delta 4 done
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:21:38 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.383 seconds
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:21:38 worker_manager.py:364] Main thread loading delta 4 done
INFO 05-16 18:21:42 metrics.py:276] Avg prompt throughput: 3.1 tokens/s, Avg generation throughput: 8.4 tokens/s, Running: 47 reqs, Swapped: 0 reqs, Pending: 4 reqs, GPU KV cache usage: 1.9%, CPU KV cache usage: 0.0%
INFO:     ::1:45058 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:45052 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:45054 - "POST /v1/completions HTTP/1.1" 200 OK
WARNING 05-16 18:21:42 worker_manager.py:344] Missed prefetch, fall back to loading delta 29 now
INFO 05-16 18:21:42 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-16 18:21:42 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72269)[0m WARNING 05-16 18:21:42 worker_manager.py:344] Missed prefetch, fall back to loading delta 29 now
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:21:42 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:21:42 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72443)[0m WARNING 05-16 18:21:42 worker_manager.py:344] Missed prefetch, fall back to loading delta 29 now
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:21:42 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:21:42 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72591)[0m WARNING 05-16 18:21:42 worker_manager.py:344] Missed prefetch, fall back to loading delta 29 now
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:21:42 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:21:42 models.py:263] [main] Lossless Compression Disabled
INFO 05-16 18:21:44 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.560 seconds
INFO 05-16 18:21:44 worker_manager.py:364] Main thread loading delta 29 done
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:21:44 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.117 seconds
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:21:44 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.125 seconds
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:21:44 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.125 seconds
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:21:44 worker_manager.py:364] Main thread loading delta 29 done
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:21:44 worker_manager.py:364] Main thread loading delta 29 done
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:21:44 worker_manager.py:364] Main thread loading delta 29 done
INFO 05-16 18:21:47 metrics.py:276] Avg prompt throughput: 3.5 tokens/s, Avg generation throughput: 0.2 tokens/s, Running: 48 reqs, Swapped: 0 reqs, Pending: 3 reqs, GPU KV cache usage: 1.9%, CPU KV cache usage: 0.0%
INFO:     ::1:45046 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-16 18:21:54 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 19.8 tokens/s, Running: 46 reqs, Swapped: 0 reqs, Pending: 3 reqs, GPU KV cache usage: 1.9%, CPU KV cache usage: 0.0%
INFO:     ::1:45072 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-16 18:22:01 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 14.4 tokens/s, Running: 45 reqs, Swapped: 0 reqs, Pending: 3 reqs, GPU KV cache usage: 2.0%, CPU KV cache usage: 0.0%
INFO:     ::1:45056 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:44966 - "POST /v1/completions HTTP/1.1" 200 OK
WARNING 05-16 18:22:04 worker_manager.py:344] Missed prefetch, fall back to loading delta 6 now
INFO 05-16 18:22:04 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-16 18:22:04 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72269)[0m WARNING 05-16 18:22:04 worker_manager.py:344] Missed prefetch, fall back to loading delta 6 now
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:22:04 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:22:04 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72443)[0m WARNING 05-16 18:22:04 worker_manager.py:344] Missed prefetch, fall back to loading delta 6 now
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:22:04 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:22:04 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72591)[0m WARNING 05-16 18:22:04 worker_manager.py:344] Missed prefetch, fall back to loading delta 6 now
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:22:04 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:22:04 models.py:263] [main] Lossless Compression Disabled
INFO 05-16 18:22:06 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.823 seconds
INFO 05-16 18:22:06 worker_manager.py:364] Main thread loading delta 6 done
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:22:07 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.142 seconds
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:22:07 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.216 seconds
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:22:07 worker_manager.py:364] Main thread loading delta 6 done
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:22:07 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.196 seconds
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:22:07 worker_manager.py:364] Main thread loading delta 6 done
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:22:07 worker_manager.py:364] Main thread loading delta 6 done
INFO 05-16 18:22:07 metrics.py:276] Avg prompt throughput: 6.3 tokens/s, Avg generation throughput: 7.6 tokens/s, Running: 46 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 2.1%, CPU KV cache usage: 0.0%
INFO 05-16 18:22:13 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 14.5 tokens/s, Running: 46 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 2.2%, CPU KV cache usage: 0.0%
INFO 05-16 18:22:20 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 14.3 tokens/s, Running: 46 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 2.3%, CPU KV cache usage: 0.0%
INFO 05-16 18:22:26 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 14.3 tokens/s, Running: 46 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 2.4%, CPU KV cache usage: 0.0%
INFO 05-16 18:22:33 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 14.3 tokens/s, Running: 46 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 2.4%, CPU KV cache usage: 0.0%
INFO 05-16 18:22:39 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 14.3 tokens/s, Running: 46 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 2.5%, CPU KV cache usage: 0.0%
INFO 05-16 18:22:46 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 14.3 tokens/s, Running: 45 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 2.5%, CPU KV cache usage: 0.0%
INFO:     ::1:45084 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-16 18:22:52 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 14.1 tokens/s, Running: 45 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 2.6%, CPU KV cache usage: 0.0%
INFO 05-16 18:22:57 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 8.6 tokens/s, Running: 45 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 2.7%, CPU KV cache usage: 0.0%
INFO 05-16 18:23:05 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 17.8 tokens/s, Running: 45 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 2.9%, CPU KV cache usage: 0.0%
INFO 05-16 18:23:11 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 14.0 tokens/s, Running: 44 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 2.9%, CPU KV cache usage: 0.0%
INFO:     ::1:45026 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:45074 - "POST /v1/completions HTTP/1.1" 200 OK
WARNING 05-16 18:23:14 worker_manager.py:344] Missed prefetch, fall back to loading delta 7 now
INFO 05-16 18:23:14 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-16 18:23:14 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72269)[0m WARNING 05-16 18:23:14 worker_manager.py:344] Missed prefetch, fall back to loading delta 7 now
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:23:14 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:23:14 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72443)[0m WARNING 05-16 18:23:14 worker_manager.py:344] Missed prefetch, fall back to loading delta 7 now
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:23:14 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:23:14 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=72591)[0m WARNING 05-16 18:23:14 worker_manager.py:344] Missed prefetch, fall back to loading delta 7 now
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:23:14 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:23:14 models.py:263] [main] Lossless Compression Disabled
INFO 05-16 18:23:16 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.833 seconds
INFO 05-16 18:23:16 worker_manager.py:364] Main thread loading delta 7 done
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:23:17 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.250 seconds
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:23:17 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.246 seconds
[36m(RayWorkerVllm pid=72269)[0m INFO 05-16 18:23:17 worker_manager.py:364] Main thread loading delta 7 done
[36m(RayWorkerVllm pid=72443)[0m INFO 05-16 18:23:17 worker_manager.py:364] Main thread loading delta 7 done
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:23:17 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.339 seconds
[36m(RayWorkerVllm pid=72591)[0m INFO 05-16 18:23:17 worker_manager.py:364] Main thread loading delta 7 done
INFO 05-16 18:23:17 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 7.3 tokens/s, Running: 44 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 2.9%, CPU KV cache usage: 0.0%
INFO 05-16 18:23:24 metrics.py:276] Avg prompt throughput: 3.1 tokens/s, Avg generation throughput: 13.9 tokens/s, Running: 43 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 2.9%, CPU KV cache usage: 0.0%
INFO:     ::1:44986 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-16 18:23:30 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 14.0 tokens/s, Running: 43 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.0%, CPU KV cache usage: 0.0%
INFO 05-16 18:23:36 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 14.0 tokens/s, Running: 43 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.0%, CPU KV cache usage: 0.0%
INFO 05-16 18:23:42 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 14.0 tokens/s, Running: 42 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.0%, CPU KV cache usage: 0.0%
INFO:     ::1:45094 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-16 18:23:47 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 8.1 tokens/s, Running: 42 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.1%, CPU KV cache usage: 0.0%
INFO:     ::1:44964 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-16 18:23:54 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 17.5 tokens/s, Running: 41 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.2%, CPU KV cache usage: 0.0%
INFO:     ::1:45020 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-16 18:24:00 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.3 tokens/s, Running: 40 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.2%, CPU KV cache usage: 0.0%
INFO 05-16 18:24:07 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.0 tokens/s, Running: 39 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.1%, CPU KV cache usage: 0.0%
INFO:     ::1:45116 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-16 18:24:12 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.3 tokens/s, Running: 39 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.2%, CPU KV cache usage: 0.0%
INFO 05-16 18:24:18 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.3 tokens/s, Running: 39 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.3%, CPU KV cache usage: 0.0%
INFO 05-16 18:24:24 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.3 tokens/s, Running: 39 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.3%, CPU KV cache usage: 0.0%
INFO 05-16 18:24:30 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.3 tokens/s, Running: 39 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.3%, CPU KV cache usage: 0.0%
INFO 05-16 18:24:36 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.2 tokens/s, Running: 39 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.4%, CPU KV cache usage: 0.0%
INFO 05-16 18:24:42 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.3 tokens/s, Running: 38 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.5%, CPU KV cache usage: 0.0%
INFO:     ::1:44956 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-16 18:24:47 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 7.1 tokens/s, Running: 38 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.6%, CPU KV cache usage: 0.0%
INFO 05-16 18:24:53 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 19.6 tokens/s, Running: 38 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.7%, CPU KV cache usage: 0.0%
INFO:     ::1:45076 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-16 18:24:59 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.3 tokens/s, Running: 36 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.5%, CPU KV cache usage: 0.0%
INFO:     ::1:44958 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-16 18:25:04 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.4 tokens/s, Running: 36 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.6%, CPU KV cache usage: 0.0%
INFO 05-16 18:25:09 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.4 tokens/s, Running: 36 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.6%, CPU KV cache usage: 0.0%
INFO:     ::1:45086 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-16 18:25:15 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.2 tokens/s, Running: 35 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.5%, CPU KV cache usage: 0.0%
INFO 05-16 18:25:20 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.1 tokens/s, Running: 35 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.6%, CPU KV cache usage: 0.0%
INFO 05-16 18:25:25 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.0 tokens/s, Running: 35 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.7%, CPU KV cache usage: 0.0%
INFO 05-16 18:25:31 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.0 tokens/s, Running: 35 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.9%, CPU KV cache usage: 0.0%
INFO 05-16 18:25:36 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 12.5 tokens/s, Running: 35 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.9%, CPU KV cache usage: 0.0%
INFO 05-16 18:25:42 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.0 tokens/s, Running: 35 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.0%, CPU KV cache usage: 0.0%
INFO:     ::1:44976 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-16 18:25:47 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.3 tokens/s, Running: 34 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.9%, CPU KV cache usage: 0.0%
INFO 05-16 18:25:52 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.4 tokens/s, Running: 34 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.9%, CPU KV cache usage: 0.0%
INFO 05-16 18:25:57 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.4 tokens/s, Running: 34 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.9%, CPU KV cache usage: 0.0%
INFO 05-16 18:26:02 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.4 tokens/s, Running: 34 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.0%, CPU KV cache usage: 0.0%
INFO 05-16 18:26:07 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.3 tokens/s, Running: 34 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.1%, CPU KV cache usage: 0.0%
INFO 05-16 18:26:12 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.3 tokens/s, Running: 34 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.2%, CPU KV cache usage: 0.0%
INFO:     ::1:45006 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-16 18:26:18 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.0 tokens/s, Running: 33 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.2%, CPU KV cache usage: 0.0%
INFO:     ::1:45120 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-16 18:26:23 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 12.9 tokens/s, Running: 32 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.1%, CPU KV cache usage: 0.0%
INFO:     ::1:45004 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:45100 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-16 18:26:30 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.1 tokens/s, Running: 29 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.8%, CPU KV cache usage: 0.0%
INFO:     ::1:45063 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:44960 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-16 18:26:37 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 12.5 tokens/s, Running: 27 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.6%, CPU KV cache usage: 0.0%
INFO:     ::1:44984 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-16 18:26:43 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 11.8 tokens/s, Running: 27 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.7%, CPU KV cache usage: 0.0%
INFO 05-16 18:26:50 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 11.8 tokens/s, Running: 27 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.8%, CPU KV cache usage: 0.0%
INFO 05-16 18:26:57 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 11.9 tokens/s, Running: 27 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.9%, CPU KV cache usage: 0.0%
INFO:     ::1:44970 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-16 18:27:04 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 12.0 tokens/s, Running: 26 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.8%, CPU KV cache usage: 0.0%
INFO 05-16 18:27:10 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 12.1 tokens/s, Running: 26 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.9%, CPU KV cache usage: 0.0%
INFO 05-16 18:27:17 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 12.1 tokens/s, Running: 26 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.9%, CPU KV cache usage: 0.0%
INFO 05-16 18:27:23 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 12.1 tokens/s, Running: 26 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.1%, CPU KV cache usage: 0.0%
INFO:     ::1:45082 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-16 18:27:29 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 11.8 tokens/s, Running: 25 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.9%, CPU KV cache usage: 0.0%
INFO 05-16 18:27:36 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 11.7 tokens/s, Running: 25 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.0%, CPU KV cache usage: 0.0%
INFO 05-16 18:27:42 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 11.7 tokens/s, Running: 25 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.1%, CPU KV cache usage: 0.0%
INFO 05-16 18:27:49 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 11.7 tokens/s, Running: 25 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.2%, CPU KV cache usage: 0.0%
INFO:     ::1:44942 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-16 18:27:55 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 11.4 tokens/s, Running: 24 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.1%, CPU KV cache usage: 0.0%
INFO 05-16 18:28:02 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 11.2 tokens/s, Running: 24 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.2%, CPU KV cache usage: 0.0%
INFO 05-16 18:28:07 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 8.5 tokens/s, Running: 24 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.2%, CPU KV cache usage: 0.0%
INFO 05-16 18:28:12 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 14.3 tokens/s, Running: 24 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.3%, CPU KV cache usage: 0.0%
INFO:     ::1:45038 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-16 18:28:19 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 10.9 tokens/s, Running: 23 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.1%, CPU KV cache usage: 0.0%
INFO 05-16 18:28:25 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 10.7 tokens/s, Running: 23 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.2%, CPU KV cache usage: 0.0%
INFO:     ::1:45028 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-16 18:28:31 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 10.7 tokens/s, Running: 22 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.2%, CPU KV cache usage: 0.0%
INFO:     ::1:45092 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-16 18:28:37 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 7.7 tokens/s, Running: 21 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.0%, CPU KV cache usage: 0.0%
INFO 05-16 18:28:44 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 12.6 tokens/s, Running: 21 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.0%, CPU KV cache usage: 0.0%
INFO 05-16 18:28:50 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 10.4 tokens/s, Running: 21 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.1%, CPU KV cache usage: 0.0%
INFO 05-16 18:28:56 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 10.4 tokens/s, Running: 21 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.2%, CPU KV cache usage: 0.0%
INFO:     ::1:44940 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-16 18:29:02 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 10.2 tokens/s, Running: 20 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.0%, CPU KV cache usage: 0.0%
INFO 05-16 18:29:07 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 7.7 tokens/s, Running: 20 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.1%, CPU KV cache usage: 0.0%
INFO:     ::1:45066 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-16 18:29:14 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 11.9 tokens/s, Running: 19 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.9%, CPU KV cache usage: 0.0%
INFO 05-16 18:29:19 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 10.0 tokens/s, Running: 19 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.0%, CPU KV cache usage: 0.0%
INFO:     ::1:45110 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:45024 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-16 18:29:25 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 10.1 tokens/s, Running: 17 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.6%, CPU KV cache usage: 0.0%
INFO 05-16 18:29:30 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 9.8 tokens/s, Running: 17 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.7%, CPU KV cache usage: 0.0%
INFO 05-16 18:29:35 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 9.7 tokens/s, Running: 17 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.7%, CPU KV cache usage: 0.0%
INFO 05-16 18:29:40 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 9.6 tokens/s, Running: 17 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.8%, CPU KV cache usage: 0.0%
INFO 05-16 18:29:46 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 9.5 tokens/s, Running: 17 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.8%, CPU KV cache usage: 0.0%
INFO 05-16 18:29:51 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 9.6 tokens/s, Running: 17 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.9%, CPU KV cache usage: 0.0%
INFO 05-16 18:29:56 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 9.7 tokens/s, Running: 16 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.7%, CPU KV cache usage: 0.0%
INFO:     ::1:45098 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-16 18:30:03 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 9.9 tokens/s, Running: 16 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.8%, CPU KV cache usage: 0.0%
INFO 05-16 18:30:09 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 9.9 tokens/s, Running: 16 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.8%, CPU KV cache usage: 0.0%
INFO:     ::1:44950 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-16 18:30:15 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 10.0 tokens/s, Running: 15 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.7%, CPU KV cache usage: 0.0%
INFO 05-16 18:30:21 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 10.1 tokens/s, Running: 15 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.7%, CPU KV cache usage: 0.0%
INFO 05-16 18:30:27 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 7.6 tokens/s, Running: 15 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.8%, CPU KV cache usage: 0.0%
INFO 05-16 18:30:33 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 12.5 tokens/s, Running: 15 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.8%, CPU KV cache usage: 0.0%
INFO 05-16 18:30:39 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 10.2 tokens/s, Running: 14 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.6%, CPU KV cache usage: 0.0%
INFO:     ::1:45102 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-16 18:30:44 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 10.5 tokens/s, Running: 14 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.6%, CPU KV cache usage: 0.0%
INFO:     ::1:45088 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-16 18:30:50 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 10.4 tokens/s, Running: 13 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.4%, CPU KV cache usage: 0.0%
INFO:     ::1:45114 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-16 18:30:55 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 10.9 tokens/s, Running: 12 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.2%, CPU KV cache usage: 0.0%
INFO 05-16 18:31:01 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 11.3 tokens/s, Running: 12 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.2%, CPU KV cache usage: 0.0%
INFO 05-16 18:31:06 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 11.2 tokens/s, Running: 12 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.3%, CPU KV cache usage: 0.0%
INFO:     ::1:44962 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-16 18:31:12 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 10.9 tokens/s, Running: 11 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.1%, CPU KV cache usage: 0.0%
INFO 05-16 18:31:17 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 10.3 tokens/s, Running: 11 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.2%, CPU KV cache usage: 0.0%
INFO:     ::1:45030 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-16 18:31:22 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 10.3 tokens/s, Running: 10 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 2.9%, CPU KV cache usage: 0.0%
INFO 05-16 18:31:27 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 10.0 tokens/s, Running: 10 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.0%, CPU KV cache usage: 0.0%
INFO 05-16 18:31:33 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 11.2 tokens/s, Running: 10 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.0%, CPU KV cache usage: 0.0%
INFO 05-16 18:31:38 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 10.6 tokens/s, Running: 10 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.1%, CPU KV cache usage: 0.0%
INFO 05-16 18:31:44 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 10.7 tokens/s, Running: 10 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.1%, CPU KV cache usage: 0.0%
INFO:     ::1:45044 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:44996 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-16 18:31:49 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 10.0 tokens/s, Running: 8 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 2.6%, CPU KV cache usage: 0.0%
INFO 05-16 18:31:55 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 8.6 tokens/s, Running: 8 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 2.6%, CPU KV cache usage: 0.0%
INFO 05-16 18:32:01 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 8.6 tokens/s, Running: 8 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 2.7%, CPU KV cache usage: 0.0%
INFO 05-16 18:32:06 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 8.6 tokens/s, Running: 8 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 2.7%, CPU KV cache usage: 0.0%
INFO:     ::1:44952 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-16 18:32:12 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 7.9 tokens/s, Running: 7 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 2.4%, CPU KV cache usage: 0.0%
INFO:     ::1:45118 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-16 18:32:17 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 6.5 tokens/s, Running: 6 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 2.1%, CPU KV cache usage: 0.0%
INFO:     ::1:45113 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:45080 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-16 18:32:23 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 7.7 tokens/s, Running: 4 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.5%, CPU KV cache usage: 0.0%
INFO 05-16 18:32:28 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 6.0 tokens/s, Running: 4 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.5%, CPU KV cache usage: 0.0%
INFO 05-16 18:32:33 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 6.0 tokens/s, Running: 4 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.5%, CPU KV cache usage: 0.0%
INFO 05-16 18:32:39 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 6.1 tokens/s, Running: 4 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.6%, CPU KV cache usage: 0.0%
INFO 05-16 18:32:44 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 6.0 tokens/s, Running: 4 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.6%, CPU KV cache usage: 0.0%
INFO:     ::1:45078 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-16 18:32:49 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 5.9 tokens/s, Running: 3 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%
INFO 05-16 18:32:54 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 5.7 tokens/s, Running: 3 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%
INFO 05-16 18:33:00 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 5.6 tokens/s, Running: 3 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.3%, CPU KV cache usage: 0.0%
INFO:     ::1:45068 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-16 18:33:05 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 5.3 tokens/s, Running: 2 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.9%, CPU KV cache usage: 0.0%
INFO:     ::1:45036 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-16 18:33:10 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.8 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.5%, CPU KV cache usage: 0.0%
INFO 05-16 18:33:15 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 3.9 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.5%, CPU KV cache usage: 0.0%
INFO 05-16 18:33:20 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 3.9 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.5%, CPU KV cache usage: 0.0%
INFO 05-16 18:33:26 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 3.9 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.5%, CPU KV cache usage: 0.0%
INFO:     ::1:44992 - "POST /v1/completions HTTP/1.1" 200 OK
Results written to .artifact/benchmarks/results/737f84cd-aaca-4e02-8410-b445fbb47868.jsonl
Killing process 64205...
/var/spool/slurmd/job3675824/slurm_script: line 46: 64172 Killed                  apptainer run --nv --home /mnt/petrelfs/huqinghao/xzyao/:/home/xiayao --bind /mnt/petrelfs/huqinghao/xzyao/code/vllm:/vllm --bind /mnt/petrelfs/huqinghao/xzyao/code/triteia:/triteia --env PYTHONPATH=/vllm:/triteia --env CUDA_LAUNCH_BLOCKING=1 --env TVM_TARGET=nvidia/nvidia-a100 --env TRANSFORMERS_OFFLINE=1 --env NUMEXPR_MAX_THREADS=128 --env USE_BITBLAS=1 --env BITBLAS_TARGET=nvidia/nvidia-a100 --env RAY_DEDUP_LOGS=0 --workdir /vllm /mnt/petrelfs/huqinghao/xzyao/images/vllm-0.4.1.sif python3 /vllm/vllm/entrypoints/openai/api_server.py --model /vllm/.idea/full_models/Llama-2-13b-hf --enable-delta --disable-log-requests --gpu-memory-utilization 0.85 --delta-modules delta-1=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-1 delta-2=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-2 delta-3=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-3 delta-4=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-4 delta-5=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-5 delta-6=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-6 delta-7=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-7 delta-8=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-8 delta-9=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-9 delta-10=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-10 delta-11=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-11 delta-12=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-12 delta-13=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-13 delta-14=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-14 delta-15=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-15 delta-16=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-16 delta-17=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-17 delta-18=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-18 delta-19=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-19 delta-20=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-20 delta-21=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-21 delta-22=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-22 delta-23=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-23 delta-24=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-24 delta-25=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-25 delta-26=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-26 delta-27=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-27 delta-28=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-28 delta-29=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-29 delta-30=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-30 delta-31=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-31 delta-32=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-32 --max-deltas 24 --tensor-parallel-size 4 --enforce-eager
