/mnt/hwfile/huqinghao/miniconda3/bin/python
2024-05-17 16:20:54,697 - INFO - Note: detected 128 virtual cores but NumExpr set to maximum of 64, check "NUMEXPR_MAX_THREADS" environment variable.
2024-05-17 16:20:54,698 - INFO - Note: NumExpr detected 128 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
2024-05-17 16:20:54,698 - INFO - NumExpr defaulting to 8 threads.
2024-05-17 16:20:56,334	INFO scripts.py:1182 -- Did not find any active Ray processes.

==========
== CUDA ==
==========

CUDA Version 12.1.0

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

*************************
** DEPRECATION NOTICE! **
*************************
THIS IMAGE IS DEPRECATED and is scheduled for DELETION.
    https://gitlab.com/nvidia/container-images/cuda/blob/master/doc/support-policy.md

Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd706d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd71450>: Failed to establish a new connection: [Errno 111] Connection refused'))
INFO 05-17 16:21:10 api_server.py:191] vLLM API server version 0.3.3
INFO 05-17 16:21:10 api_server.py:192] args: Namespace(host=None, port=8000, uvicorn_log_level='info', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_key=None, served_model_name=None, lora_modules=[], delta_modules=[Delta(name='delta-1', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-1'), Delta(name='delta-2', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-2'), Delta(name='delta-3', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-3'), Delta(name='delta-4', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-4'), Delta(name='delta-5', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-5'), Delta(name='delta-6', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-6'), Delta(name='delta-7', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-7'), Delta(name='delta-8', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-8'), Delta(name='delta-9', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-9'), Delta(name='delta-10', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-10'), Delta(name='delta-11', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-11'), Delta(name='delta-12', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-12'), Delta(name='delta-13', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-13'), Delta(name='delta-14', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-14'), Delta(name='delta-15', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-15'), Delta(name='delta-16', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-16'), Delta(name='delta-17', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-17'), Delta(name='delta-18', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-18'), Delta(name='delta-19', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-19'), Delta(name='delta-20', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-20'), Delta(name='delta-21', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-21'), Delta(name='delta-22', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-22'), Delta(name='delta-23', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-23'), Delta(name='delta-24', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-24'), Delta(name='delta-25', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-25'), Delta(name='delta-26', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-26'), Delta(name='delta-27', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-27'), Delta(name='delta-28', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-28'), Delta(name='delta-29', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-29'), Delta(name='delta-30', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-30'), Delta(name='delta-31', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-31'), Delta(name='delta-32', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-32')], swap_modules=[], chat_template=None, response_role='assistant', ssl_keyfile=None, ssl_certfile=None, ssl_ca_certs=None, ssl_cert_reqs=0, root_path=None, middleware=[], model='/vllm/.idea/full_models/Llama-2-13b-hf', tokenizer=None, revision=None, code_revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=False, download_dir=None, load_format='auto', dtype='auto', kv_cache_dtype='auto', max_model_len=None, worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=4, max_parallel_loading_workers=None, ray_workers_use_nsight=False, block_size=16, enable_prefix_caching=False, seed=0, swap_space=4, gpu_memory_utilization=0.85, max_num_batched_tokens=None, max_num_seqs=256, max_logprobs=5, disable_log_stats=False, quantization=None, enforce_eager=True, max_context_len_to_capture=8192, disable_custom_all_reduce=False, tokenizer_pool_size=0, tokenizer_pool_type='ray', tokenizer_pool_extra_config=None, enable_lora=False, max_loras=1, max_lora_rank=64, lora_extra_vocab_size=256, lora_dtype='auto', max_cpu_loras=32, enable_delta=True, max_deltas=24, max_cpu_deltas=32, max_delta_bitwidth=4, device='auto', image_input_type=None, image_token_id=None, image_input_shape=None, image_feature_size=None, scheduler_delay_factor=0.0, enable_prefetch=False, scheduler_policy='fcfs', max_swap_slots=1, max_cpu_models=4, enable_swap=False, engine_use_ray=False, disable_log_requests=True, max_log_len=None)
2024-05-17 16:21:14,304	INFO worker.py:1749 -- Started a local Ray instance.
INFO 05-17 16:21:16 llm_engine.py:90] Initializing an LLM engine (v0.3.3) with config: model='/vllm/.idea/full_models/Llama-2-13b-hf', tokenizer='/vllm/.idea/full_models/Llama-2-13b-hf', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, lora_config=None, delta_config=DeltaConfig(max_deltas=24, max_bitwidth=4, delta_dtype=torch.int8, max_cpu_deltas=32, delta_extra_vocab_size=0, pack_factor=Fraction(2, 1), kernel=<QuantKernel.TRITON: 'triton'>), swap_config=None, max_seq_len=4096, download_dir=None, load_format=auto, tensor_parallel_size=4, disable_custom_all_reduce=False, quantization=None, enforce_eager=True, kv_cache_dtype=auto, device_config=cuda, seed=0)
INFO 05-17 16:21:16 llm_engine.py:243] ignored verifying delta_config
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd71d20>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd71150>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception ignored in: <function TempDirectory.__del__ at 0x7f3a4aad7eb0>
Traceback (most recent call last):
  File "/home/xiayao/.local/lib/python3.10/site-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 145, in __del__
    self.remove()
  File "/home/xiayao/.local/lib/python3.10/site-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 121, in remove
    if self.temp_dir:
AttributeError: 'TempDirectory' object has no attribute 'temp_dir'
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd70880>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd725f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd72ec0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception ignored in: <function TempDirectory.__del__ at 0x7f3a4aad7eb0>
Traceback (most recent call last):
  File "/home/xiayao/.local/lib/python3.10/site-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 145, in __del__
    self.remove()
  File "/home/xiayao/.local/lib/python3.10/site-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 121, in remove
    if self.temp_dir:
AttributeError: 'TempDirectory' object has no attribute 'temp_dir'
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd73790>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd729e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd72110>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd703d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd71390>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5f93c0a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd73b20>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd713f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd70370>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd72140>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd73310>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd72a10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd72800>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd71f30>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd70ee0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd73cd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5f93c370>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd73e80>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd71510>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd701f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd72350>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd72c50>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd737f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd726e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd70580>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd71030>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd73d90>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd71cf0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd73fa0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd71000>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd70070>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd72650>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd72980>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5f93c070>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd70580>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd71030>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd73d90>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd71cf0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd4bb20>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd71540>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd71c00>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd73880>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd70dc0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd71ff0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5f93c9a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd702b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd71270>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd73d30>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd73ee0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5f93c400>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd71bd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd71ae0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd73850>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd71150>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd704f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5f93c040>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd70160>: Failed to establish a new connection: [Errno 111] Connection refused'))
Using bitblas
BitBLAS Operator not loaded, retrying in 5 seconds...
Error: [Errno 17] File exists: '/home/xiayao/.cache/bitblas/nvidia/nvidia-a100/c96df0f34eb23be516ef0126651d4e78b151337f28ebc87cc5492d79d135855f/tvm_rt_mod'
BitBLAS Operator not loaded, retrying in 5 seconds...
Error: [Errno 17] File exists: '/home/xiayao/.cache/bitblas/nvidia/nvidia-a100/ff3d6f6d8934761a45ef3a70d759596010761192a655d893a7465dc76e4707f5/tvm_rt_mod'
WARNING 05-17 16:31:31 models.py:48] Using bitblas delta modules
INFO 05-17 16:31:31 selector.py:16] Using FlashAttention backend.
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd71420>: Failed to establish a new connection: [Errno 111] Connection refused'))
[36m(RayWorkerVllm pid=73241)[0m Exception ignored in: <function TempDirectory.__del__ at 0x7f80d0252200>
[36m(RayWorkerVllm pid=73241)[0m Traceback (most recent call last):
[36m(RayWorkerVllm pid=73241)[0m   File "/home/xiayao/.local/lib/python3.10/site-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 145, in __del__
[36m(RayWorkerVllm pid=73241)[0m     self.remove()
[36m(RayWorkerVllm pid=73241)[0m   File "/home/xiayao/.local/lib/python3.10/site-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 121, in remove
[36m(RayWorkerVllm pid=73241)[0m     if self.temp_dir:
[36m(RayWorkerVllm pid=73241)[0m AttributeError: 'TempDirectory' object has no attribute 'temp_dir'
[36m(RayWorkerVllm pid=73384)[0m Exception ignored in: <function TempDirectory.__del__ at 0x7f7cf9d42200>
[36m(RayWorkerVllm pid=73384)[0m Traceback (most recent call last):
[36m(RayWorkerVllm pid=73384)[0m   File "/home/xiayao/.local/lib/python3.10/site-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 145, in __del__
[36m(RayWorkerVllm pid=73384)[0m     self.remove()
[36m(RayWorkerVllm pid=73384)[0m   File "/home/xiayao/.local/lib/python3.10/site-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 121, in remove
[36m(RayWorkerVllm pid=73384)[0m     if self.temp_dir:
[36m(RayWorkerVllm pid=73384)[0m AttributeError: 'TempDirectory' object has no attribute 'temp_dir'
[36m(RayWorkerVllm pid=73241)[0m Exception ignored in: <function TempDirectory.__del__ at 0x7f80d0252200>
[36m(RayWorkerVllm pid=73241)[0m Traceback (most recent call last):
[36m(RayWorkerVllm pid=73241)[0m   File "/home/xiayao/.local/lib/python3.10/site-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 145, in __del__
[36m(RayWorkerVllm pid=73241)[0m     self.remove()
[36m(RayWorkerVllm pid=73241)[0m   File "/home/xiayao/.local/lib/python3.10/site-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 121, in remove
[36m(RayWorkerVllm pid=73241)[0m     if self.temp_dir:
[36m(RayWorkerVllm pid=73241)[0m AttributeError: 'TempDirectory' object has no attribute 'temp_dir'
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd73910>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd71a20>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5f93cbe0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd73d00>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd71810>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd714b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd70220>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd725c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5f93d270>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd72530>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd70730>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd71120>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd71c30>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5f93c700>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd71540>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd71a20>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd73910>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd71420>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd70490>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5f93ca60>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd721a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd72440>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd70130>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd715d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5f93d4e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd71660>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd711e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd70640>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd72410>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd721d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5f93db70>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd72500>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd70f70>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd73ac0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd710f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd72830>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd72230>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd71e40>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd72770>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd72380>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd70fd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5f93d4b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd73820>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd73970>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd717b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd706a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd4bd60>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd729e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd72c50>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd71b40>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd71210>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd703a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5f93d840>: Failed to establish a new connection: [Errno 111] Connection refused'))
[36m(RayWorkerVllm pid=73066)[0m Using bitblas
[36m(RayWorkerVllm pid=73241)[0m Using bitblas
[36m(RayWorkerVllm pid=73384)[0m Using bitblas
[36m(RayWorkerVllm pid=73241)[0m BitBLAS Operator not loaded, retrying in 5 seconds...
[36m(RayWorkerVllm pid=73241)[0m Error: [Errno 17] File exists: '/home/xiayao/.cache/bitblas/nvidia/nvidia-a100/c96df0f34eb23be516ef0126651d4e78b151337f28ebc87cc5492d79d135855f/tvm_rt_mod'
[36m(RayWorkerVllm pid=73384)[0m BitBLAS Operator not loaded, retrying in 5 seconds...
[36m(RayWorkerVllm pid=73384)[0m Error: [Errno 17] File exists: '/home/xiayao/.cache/bitblas/nvidia/nvidia-a100/c96df0f34eb23be516ef0126651d4e78b151337f28ebc87cc5492d79d135855f/tvm_rt_mod'
[36m(RayWorkerVllm pid=73241)[0m BitBLAS Operator not loaded, retrying in 5 seconds...
[36m(RayWorkerVllm pid=73241)[0m Error: [Errno 17] File exists: '/home/xiayao/.cache/bitblas/nvidia/nvidia-a100/c96df0f34eb23be516ef0126651d4e78b151337f28ebc87cc5492d79d135855f/tvm_rt_mod'
[36m(RayWorkerVllm pid=73066)[0m WARNING 05-17 16:40:13 models.py:48] Using bitblas delta modules
[36m(RayWorkerVllm pid=73066)[0m INFO 05-17 16:40:13 selector.py:16] Using FlashAttention backend.
[36m(RayWorkerVllm pid=73384)[0m WARNING 05-17 16:40:17 models.py:48] Using bitblas delta modules
[36m(RayWorkerVllm pid=73384)[0m INFO 05-17 16:40:17 selector.py:16] Using FlashAttention backend.
[36m(RayWorkerVllm pid=73241)[0m WARNING 05-17 16:40:21 models.py:48] Using bitblas delta modules
[36m(RayWorkerVllm pid=73241)[0m INFO 05-17 16:40:21 selector.py:16] Using FlashAttention backend.
INFO 05-17 16:40:33 model_runner.py:161] Loading model weights took 6.1114 GB
INFO 05-17 16:40:33 worker_manager.py:297] Starting prefetching thread
[36m(RayWorkerVllm pid=73241)[0m INFO 05-17 16:40:34 model_runner.py:161] Loading model weights took 6.1114 GB
[36m(RayWorkerVllm pid=73241)[0m INFO 05-17 16:40:34 worker_manager.py:297] Starting prefetching thread
[36m(RayWorkerVllm pid=73066)[0m INFO 05-17 16:40:35 model_runner.py:161] Loading model weights took 6.1114 GB
[36m(RayWorkerVllm pid=73066)[0m INFO 05-17 16:40:35 worker_manager.py:297] Starting prefetching thread
[36m(RayWorkerVllm pid=73384)[0m INFO 05-17 16:40:35 model_runner.py:161] Loading model weights took 6.1114 GB
[36m(RayWorkerVllm pid=73384)[0m INFO 05-17 16:40:35 worker_manager.py:297] Starting prefetching thread
WARNING 05-17 16:40:36 quant_linear_triton.py:557] We should warm up the kernel here 
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd739a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd71600>: Failed to establish a new connection: [Errno 111] Connection refused'))
[36m(RayWorkerVllm pid=73241)[0m WARNING 05-17 16:40:38 quant_linear_triton.py:557] We should warm up the kernel here 
[36m(RayWorkerVllm pid=73384)[0m WARNING 05-17 16:40:38 quant_linear_triton.py:557] We should warm up the kernel here 
[36m(RayWorkerVllm pid=73066)[0m WARNING 05-17 16:40:38 quant_linear_triton.py:557] We should warm up the kernel here 
INFO 05-17 16:40:51 ray_gpu_executor.py:275] # GPU blocks: 6431, # CPU blocks: 1310
INFO 05-17 16:40:53 scheduler.py:136] Using fcfs policy.
INFO 05-17 16:40:53 block_manager.py:264] disable automatic prefix caching
WARNING 05-17 16:40:54 serving_chat.py:373] No chat template provided. Chat API will not work.
INFO:     Started server process [65255]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     ::1:56606 - "GET /sysinfo HTTP/1.1" 200 OK
Translating from base-model to /vllm/.idea/full_models/Llama-2-13b-hf
Warming up starts
{'id': 47, 'prompt': 'USER: List car manufacturers sorted by exclusiveness\nASSISTANT:', 'timestamp': 0, 'model': 'delta-6', 'min_tokens': 155, 'max_tokens': 155}
Prefetching is disabled
WARNING 05-17 16:40:58 worker_manager.py:344] Missed prefetch, fall back to loading delta 6 now
INFO 05-17 16:40:58 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 16:40:58 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=73066)[0m WARNING 05-17 16:40:58 worker_manager.py:344] Missed prefetch, fall back to loading delta 6 now
[36m(RayWorkerVllm pid=73066)[0m INFO 05-17 16:40:58 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=73066)[0m INFO 05-17 16:40:58 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=73241)[0m WARNING 05-17 16:40:58 worker_manager.py:344] Missed prefetch, fall back to loading delta 6 now
[36m(RayWorkerVllm pid=73241)[0m INFO 05-17 16:40:58 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=73241)[0m INFO 05-17 16:40:58 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=73384)[0m WARNING 05-17 16:40:58 worker_manager.py:344] Missed prefetch, fall back to loading delta 6 now
[36m(RayWorkerVllm pid=73384)[0m INFO 05-17 16:40:58 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=73384)[0m INFO 05-17 16:40:58 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:40:59 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.552 seconds
INFO 05-17 16:40:59 worker_manager.py:364] Main thread loading delta 6 done
INFO 05-17 16:40:59 worker_manager.py:379] [1715935259.7568562] activating delta
INFO 05-17 16:40:59 worker_manager.py:384] [1715935259.8609273] CPU -> GPU time: 0.1040
[36m(RayWorkerVllm pid=73066)[0m INFO 05-17 16:41:00 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.964 seconds
[36m(RayWorkerVllm pid=73241)[0m INFO 05-17 16:41:00 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.017 seconds
[36m(RayWorkerVllm pid=73066)[0m INFO 05-17 16:41:00 worker_manager.py:364] Main thread loading delta 6 done
[36m(RayWorkerVllm pid=73066)[0m INFO 05-17 16:41:00 worker_manager.py:379] [1715935260.1452026] activating delta
[36m(RayWorkerVllm pid=73241)[0m INFO 05-17 16:41:00 worker_manager.py:364] Main thread loading delta 6 done
[36m(RayWorkerVllm pid=73241)[0m INFO 05-17 16:41:00 worker_manager.py:379] [1715935260.21273] activating delta
[36m(RayWorkerVllm pid=73384)[0m INFO 05-17 16:41:00 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.082 seconds
[36m(RayWorkerVllm pid=73066)[0m INFO 05-17 16:41:00 worker_manager.py:384] [1715935260.272374] CPU -> GPU time: 0.1271
[36m(RayWorkerVllm pid=73384)[0m INFO 05-17 16:41:00 worker_manager.py:364] Main thread loading delta 6 done
[36m(RayWorkerVllm pid=73384)[0m INFO 05-17 16:41:00 worker_manager.py:379] [1715935260.2790031] activating delta
[36m(RayWorkerVllm pid=73241)[0m INFO 05-17 16:41:00 worker_manager.py:384] [1715935260.3554401] CPU -> GPU time: 0.1427
[36m(RayWorkerVllm pid=73384)[0m INFO 05-17 16:41:00 worker_manager.py:384] [1715935260.419953] CPU -> GPU time: 0.1409
INFO 05-17 16:41:00 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
INFO 05-17 16:41:05 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 3.9 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
INFO 05-17 16:41:11 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%
INFO 05-17 16:41:16 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.1 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%
INFO 05-17 16:41:21 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.1 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%
INFO 05-17 16:41:26 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.1 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%
INFO 05-17 16:41:31 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.1 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%
INFO 05-17 16:41:36 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.1 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.2%, CPU KV cache usage: 0.0%
INFO:     ::1:56608 - "POST /v1/completions HTTP/1.1" 200 OK
Warming up ends
Issuing queries
sending 1 queries at 0.4
sending 1 queries at 1.1
sending 1 queries at 1.5
sending 1 queries at 1.9000000000000001
sending 1 queries at 2.2
sending 1 queries at 2.7
sending 1 queries at 3.0
sending 1 queries at 4.1000000000000005
sending 1 queries at 5.800000000000001
sending 1 queries at 6.0
sending 1 queries at 6.800000000000001
sending 1 queries at 7.2
sending 1 queries at 7.6000000000000005
sending 2 queries at 8.9
sending 2 queries at 9.0
sending 1 queries at 9.9
sending 1 queries at 10.600000000000001
sending 1 queries at 11.700000000000001
sending 1 queries at 13.600000000000001
sending 1 queries at 14.4
sending 1 queries at 14.700000000000001
sending 2 queries at 15.5
sending 1 queries at 16.0
sending 1 queries at 16.1
sending 1 queries at 17.6
sending 1 queries at 17.900000000000002
sending 1 queries at 18.2
sending 1 queries at 18.3
sending 1 queries at 19.1
sending 1 queries at 19.400000000000002
sending 2 queries at 19.8
sending 1 queries at 20.3
sending 1 queries at 20.8
sending 1 queries at 21.3
sending 1 queries at 22.700000000000003
sending 1 queries at 23.3
sending 1 queries at 23.5
sending 1 queries at 23.8
sending 2 queries at 24.400000000000002
sending 1 queries at 25.0
sending 1 queries at 25.5
sending 1 queries at 25.6
sending 1 queries at 25.700000000000003
sending 1 queries at 25.900000000000002
sending 1 queries at 26.1
sending 1 queries at 26.5
sending 1 queries at 26.8
sending 2 queries at 29.1
sending 1 queries at 29.200000000000003
sending 1 queries at 29.3
sending 1 queries at 29.8
sending 1 queries at 30.0
Prefetching is disabled
WARNING 05-17 16:41:39 worker_manager.py:344] Missed prefetch, fall back to loading delta 26 now
INFO 05-17 16:41:39 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 16:41:39 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=73066)[0m WARNING 05-17 16:41:39 worker_manager.py:344] Missed prefetch, fall back to loading delta 26 now
[36m(RayWorkerVllm pid=73066)[0m INFO 05-17 16:41:39 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=73066)[0m INFO 05-17 16:41:39 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=73241)[0m WARNING 05-17 16:41:39 worker_manager.py:344] Missed prefetch, fall back to loading delta 26 now
[36m(RayWorkerVllm pid=73241)[0m INFO 05-17 16:41:39 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=73241)[0m INFO 05-17 16:41:39 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=73384)[0m WARNING 05-17 16:41:39 worker_manager.py:344] Missed prefetch, fall back to loading delta 26 now
[36m(RayWorkerVllm pid=73384)[0m INFO 05-17 16:41:39 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=73384)[0m INFO 05-17 16:41:39 models.py:263] [main] Lossless Compression Disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
INFO 05-17 16:41:44 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 1.1 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
[36m(RayWorkerVllm pid=73384)[0m INFO 05-17 16:41:52 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 13.420 seconds
[36m(RayWorkerVllm pid=73384)[0m INFO 05-17 16:41:52 worker_manager.py:364] Main thread loading delta 26 done
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
INFO 05-17 16:41:54 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
Prefetching is disabled
Prefetching is disabled
[36m(RayWorkerVllm pid=73066)[0m INFO 05-17 16:41:55 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 16.671 seconds
[36m(RayWorkerVllm pid=73241)[0m INFO 05-17 16:41:55 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 16.711 seconds
[36m(RayWorkerVllm pid=73066)[0m INFO 05-17 16:41:55 worker_manager.py:364] Main thread loading delta 26 done
[36m(RayWorkerVllm pid=73241)[0m INFO 05-17 16:41:55 worker_manager.py:364] Main thread loading delta 26 done
Prefetching is disabled
INFO 05-17 16:41:56 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 17.453 seconds
INFO 05-17 16:41:56 worker_manager.py:364] Main thread loading delta 26 done
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
WARNING 05-17 16:41:56 worker_manager.py:344] Missed prefetch, fall back to loading delta 1 now
INFO 05-17 16:41:56 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 16:41:56 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=73066)[0m WARNING 05-17 16:41:56 worker_manager.py:344] Missed prefetch, fall back to loading delta 1 now
[36m(RayWorkerVllm pid=73066)[0m INFO 05-17 16:41:56 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=73066)[0m INFO 05-17 16:41:56 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=73241)[0m WARNING 05-17 16:41:56 worker_manager.py:344] Missed prefetch, fall back to loading delta 1 now
[36m(RayWorkerVllm pid=73241)[0m INFO 05-17 16:41:56 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=73241)[0m INFO 05-17 16:41:56 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=73384)[0m WARNING 05-17 16:41:56 worker_manager.py:344] Missed prefetch, fall back to loading delta 1 now
[36m(RayWorkerVllm pid=73384)[0m INFO 05-17 16:41:56 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=73384)[0m INFO 05-17 16:41:56 models.py:263] [main] Lossless Compression Disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
INFO 05-17 16:41:58 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.469 seconds
INFO 05-17 16:41:58 worker_manager.py:364] Main thread loading delta 1 done
WARNING 05-17 16:41:58 worker_manager.py:344] Missed prefetch, fall back to loading delta 3 now
INFO 05-17 16:41:58 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 16:41:58 models.py:263] [main] Lossless Compression Disabled
Prefetching is disabled
[36m(RayWorkerVllm pid=73066)[0m INFO 05-17 16:41:58 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.012 seconds
[36m(RayWorkerVllm pid=73066)[0m INFO 05-17 16:41:59 worker_manager.py:364] Main thread loading delta 1 done
[36m(RayWorkerVllm pid=73241)[0m INFO 05-17 16:41:59 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.087 seconds
[36m(RayWorkerVllm pid=73241)[0m INFO 05-17 16:41:59 worker_manager.py:364] Main thread loading delta 1 done
[36m(RayWorkerVllm pid=73384)[0m INFO 05-17 16:41:59 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.100 seconds
[36m(RayWorkerVllm pid=73384)[0m INFO 05-17 16:41:59 worker_manager.py:364] Main thread loading delta 1 done
[36m(RayWorkerVllm pid=73066)[0m WARNING 05-17 16:41:59 worker_manager.py:344] Missed prefetch, fall back to loading delta 3 now
[36m(RayWorkerVllm pid=73066)[0m INFO 05-17 16:41:59 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=73066)[0m INFO 05-17 16:41:59 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=73241)[0m WARNING 05-17 16:41:59 worker_manager.py:344] Missed prefetch, fall back to loading delta 3 now
[36m(RayWorkerVllm pid=73241)[0m INFO 05-17 16:41:59 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=73241)[0m INFO 05-17 16:41:59 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=73384)[0m WARNING 05-17 16:41:59 worker_manager.py:344] Missed prefetch, fall back to loading delta 3 now
[36m(RayWorkerVllm pid=73384)[0m INFO 05-17 16:41:59 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=73384)[0m INFO 05-17 16:41:59 models.py:263] [main] Lossless Compression Disabled
Prefetching is disabled
Prefetching is disabled
INFO 05-17 16:42:00 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.531 seconds
INFO 05-17 16:42:00 worker_manager.py:364] Main thread loading delta 3 done
WARNING 05-17 16:42:00 worker_manager.py:344] Missed prefetch, fall back to loading delta 4 now
INFO 05-17 16:42:00 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 16:42:00 models.py:263] [main] Lossless Compression Disabled
Prefetching is disabled
[36m(RayWorkerVllm pid=73066)[0m INFO 05-17 16:42:01 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.083 seconds
[36m(RayWorkerVllm pid=73066)[0m INFO 05-17 16:42:01 worker_manager.py:364] Main thread loading delta 3 done
[36m(RayWorkerVllm pid=73066)[0m WARNING 05-17 16:42:01 worker_manager.py:344] Missed prefetch, fall back to loading delta 4 now
[36m(RayWorkerVllm pid=73241)[0m INFO 05-17 16:42:01 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.023 seconds
[36m(RayWorkerVllm pid=73241)[0m INFO 05-17 16:42:01 worker_manager.py:364] Main thread loading delta 3 done
[36m(RayWorkerVllm pid=73384)[0m INFO 05-17 16:42:01 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.119 seconds
[36m(RayWorkerVllm pid=73066)[0m INFO 05-17 16:42:01 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=73066)[0m INFO 05-17 16:42:01 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=73384)[0m INFO 05-17 16:42:01 worker_manager.py:364] Main thread loading delta 3 done
[36m(RayWorkerVllm pid=73241)[0m WARNING 05-17 16:42:01 worker_manager.py:344] Missed prefetch, fall back to loading delta 4 now
[36m(RayWorkerVllm pid=73241)[0m INFO 05-17 16:42:01 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=73241)[0m INFO 05-17 16:42:01 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=73384)[0m WARNING 05-17 16:42:01 worker_manager.py:344] Missed prefetch, fall back to loading delta 4 now
[36m(RayWorkerVllm pid=73384)[0m INFO 05-17 16:42:01 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=73384)[0m INFO 05-17 16:42:01 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:42:01 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.498 seconds
INFO 05-17 16:42:01 worker_manager.py:364] Main thread loading delta 4 done
Prefetching is disabled
WARNING 05-17 16:42:02 worker_manager.py:344] Missed prefetch, fall back to loading delta 5 now
INFO 05-17 16:42:02 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 16:42:02 models.py:263] [main] Lossless Compression Disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
INFO 05-17 16:42:03 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.475 seconds
INFO 05-17 16:42:03 worker_manager.py:364] Main thread loading delta 5 done
[36m(RayWorkerVllm pid=73066)[0m INFO 05-17 16:42:03 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.075 seconds
Prefetching is disabled
[36m(RayWorkerVllm pid=73066)[0m INFO 05-17 16:42:03 worker_manager.py:364] Main thread loading delta 4 done
[36m(RayWorkerVllm pid=73241)[0m INFO 05-17 16:42:03 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.036 seconds
WARNING 05-17 16:42:03 worker_manager.py:344] Missed prefetch, fall back to loading delta 7 now
INFO 05-17 16:42:03 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 16:42:03 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=73241)[0m INFO 05-17 16:42:03 worker_manager.py:364] Main thread loading delta 4 done
[36m(RayWorkerVllm pid=73384)[0m INFO 05-17 16:42:03 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.087 seconds
[36m(RayWorkerVllm pid=73066)[0m WARNING 05-17 16:42:03 worker_manager.py:344] Missed prefetch, fall back to loading delta 5 now
[36m(RayWorkerVllm pid=73066)[0m INFO 05-17 16:42:03 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=73066)[0m INFO 05-17 16:42:03 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=73241)[0m WARNING 05-17 16:42:03 worker_manager.py:344] Missed prefetch, fall back to loading delta 5 now
[36m(RayWorkerVllm pid=73241)[0m INFO 05-17 16:42:03 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=73241)[0m INFO 05-17 16:42:03 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=73384)[0m INFO 05-17 16:42:03 worker_manager.py:364] Main thread loading delta 4 done
[36m(RayWorkerVllm pid=73384)[0m WARNING 05-17 16:42:03 worker_manager.py:344] Missed prefetch, fall back to loading delta 5 now
[36m(RayWorkerVllm pid=73384)[0m INFO 05-17 16:42:03 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=73384)[0m INFO 05-17 16:42:03 models.py:263] [main] Lossless Compression Disabled
Prefetching is disabled
Prefetching is disabled
INFO 05-17 16:42:04 metrics.py:276] Avg prompt throughput: 2.1 tokens/s, Avg generation throughput: 0.1 tokens/s, Running: 31 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.0%, CPU KV cache usage: 0.0%
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
INFO 05-17 16:42:05 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.474 seconds
INFO 05-17 16:42:05 worker_manager.py:364] Main thread loading delta 7 done
WARNING 05-17 16:42:05 worker_manager.py:344] Missed prefetch, fall back to loading delta 10 now
INFO 05-17 16:42:05 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 16:42:05 models.py:263] [main] Lossless Compression Disabled
total threads: 58
Prefetching is disabled
[36m(RayWorkerVllm pid=73066)[0m INFO 05-17 16:42:05 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.079 seconds
[36m(RayWorkerVllm pid=73066)[0m INFO 05-17 16:42:05 worker_manager.py:364] Main thread loading delta 5 done
[36m(RayWorkerVllm pid=73241)[0m INFO 05-17 16:42:05 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.058 seconds
[36m(RayWorkerVllm pid=73241)[0m INFO 05-17 16:42:05 worker_manager.py:364] Main thread loading delta 5 done
[36m(RayWorkerVllm pid=73384)[0m INFO 05-17 16:42:06 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.073 seconds
[36m(RayWorkerVllm pid=73066)[0m WARNING 05-17 16:42:06 worker_manager.py:344] Missed prefetch, fall back to loading delta 7 now
[36m(RayWorkerVllm pid=73066)[0m INFO 05-17 16:42:06 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=73066)[0m INFO 05-17 16:42:06 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=73241)[0m WARNING 05-17 16:42:06 worker_manager.py:344] Missed prefetch, fall back to loading delta 7 now
[36m(RayWorkerVllm pid=73241)[0m INFO 05-17 16:42:06 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=73241)[0m INFO 05-17 16:42:06 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=73384)[0m INFO 05-17 16:42:06 worker_manager.py:364] Main thread loading delta 5 done
[36m(RayWorkerVllm pid=73384)[0m WARNING 05-17 16:42:06 worker_manager.py:344] Missed prefetch, fall back to loading delta 7 now
[36m(RayWorkerVllm pid=73384)[0m INFO 05-17 16:42:06 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=73384)[0m INFO 05-17 16:42:06 models.py:263] [main] Lossless Compression Disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
[36m(RayWorkerVllm pid=73066)[0m INFO 05-17 16:42:08 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.128 seconds
[36m(RayWorkerVllm pid=73241)[0m INFO 05-17 16:42:08 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.095 seconds
[36m(RayWorkerVllm pid=73066)[0m INFO 05-17 16:42:08 worker_manager.py:364] Main thread loading delta 7 done
[36m(RayWorkerVllm pid=73241)[0m INFO 05-17 16:42:08 worker_manager.py:364] Main thread loading delta 7 done
[36m(RayWorkerVllm pid=73384)[0m INFO 05-17 16:42:08 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.123 seconds
Prefetching is disabled
[36m(RayWorkerVllm pid=73066)[0m WARNING 05-17 16:42:08 worker_manager.py:344] Missed prefetch, fall back to loading delta 10 now
[36m(RayWorkerVllm pid=73066)[0m INFO 05-17 16:42:08 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=73066)[0m INFO 05-17 16:42:08 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=73241)[0m WARNING 05-17 16:42:08 worker_manager.py:344] Missed prefetch, fall back to loading delta 10 now
[36m(RayWorkerVllm pid=73241)[0m INFO 05-17 16:42:08 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=73241)[0m INFO 05-17 16:42:08 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=73384)[0m INFO 05-17 16:42:08 worker_manager.py:364] Main thread loading delta 7 done
[36m(RayWorkerVllm pid=73384)[0m WARNING 05-17 16:42:08 worker_manager.py:344] Missed prefetch, fall back to loading delta 10 now
[36m(RayWorkerVllm pid=73384)[0m INFO 05-17 16:42:08 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=73384)[0m INFO 05-17 16:42:08 models.py:263] [main] Lossless Compression Disabled
Prefetching is disabled
INFO 05-17 16:42:14 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 31 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.0%, CPU KV cache usage: 0.0%
INFO 05-17 16:42:18 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 13.234 seconds
INFO 05-17 16:42:18 worker_manager.py:364] Main thread loading delta 10 done
WARNING 05-17 16:42:18 worker_manager.py:344] Missed prefetch, fall back to loading delta 18 now
INFO 05-17 16:42:18 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 16:42:18 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=73241)[0m INFO 05-17 16:42:19 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 11.350 seconds
[36m(RayWorkerVllm pid=73241)[0m INFO 05-17 16:42:19 worker_manager.py:364] Main thread loading delta 10 done
[36m(RayWorkerVllm pid=73241)[0m WARNING 05-17 16:42:19 worker_manager.py:344] Missed prefetch, fall back to loading delta 18 now
[36m(RayWorkerVllm pid=73241)[0m INFO 05-17 16:42:19 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=73241)[0m INFO 05-17 16:42:19 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=73384)[0m INFO 05-17 16:42:22 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 14.301 seconds
[36m(RayWorkerVllm pid=73384)[0m INFO 05-17 16:42:22 worker_manager.py:364] Main thread loading delta 10 done
[36m(RayWorkerVllm pid=73384)[0m WARNING 05-17 16:42:23 worker_manager.py:344] Missed prefetch, fall back to loading delta 18 now
[36m(RayWorkerVllm pid=73384)[0m INFO 05-17 16:42:23 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=73384)[0m INFO 05-17 16:42:23 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=73066)[0m INFO 05-17 16:42:23 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 14.867 seconds
[36m(RayWorkerVllm pid=73066)[0m INFO 05-17 16:42:23 worker_manager.py:364] Main thread loading delta 10 done
[36m(RayWorkerVllm pid=73066)[0m WARNING 05-17 16:42:23 worker_manager.py:344] Missed prefetch, fall back to loading delta 18 now
[36m(RayWorkerVllm pid=73066)[0m INFO 05-17 16:42:23 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=73066)[0m INFO 05-17 16:42:23 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:42:24 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 31 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.0%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=73384)[0m INFO 05-17 16:42:33 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 10.335 seconds
[36m(RayWorkerVllm pid=73384)[0m INFO 05-17 16:42:33 worker_manager.py:364] Main thread loading delta 18 done
INFO 05-17 16:42:34 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 31 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.0%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=73066)[0m INFO 05-17 16:42:35 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 12.090 seconds
[36m(RayWorkerVllm pid=73066)[0m INFO 05-17 16:42:35 worker_manager.py:364] Main thread loading delta 18 done
INFO 05-17 16:42:37 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 18.556 seconds
INFO 05-17 16:42:37 worker_manager.py:364] Main thread loading delta 18 done
[36m(RayWorkerVllm pid=73241)[0m INFO 05-17 16:42:37 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 18.013 seconds
[36m(RayWorkerVllm pid=73241)[0m INFO 05-17 16:42:38 worker_manager.py:364] Main thread loading delta 18 done
INFO 05-17 16:42:40 metrics.py:276] Avg prompt throughput: 122.3 tokens/s, Avg generation throughput: 4.6 tokens/s, Running: 30 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.0%, CPU KV cache usage: 0.0%
INFO:     ::1:56760 - "POST /v1/completions HTTP/1.1" 200 OK
WARNING 05-17 16:42:40 worker_manager.py:344] Missed prefetch, fall back to loading delta 2 now
INFO 05-17 16:42:40 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 16:42:40 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=73066)[0m WARNING 05-17 16:42:40 worker_manager.py:344] Missed prefetch, fall back to loading delta 2 now
[36m(RayWorkerVllm pid=73066)[0m INFO 05-17 16:42:40 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=73066)[0m INFO 05-17 16:42:40 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=73241)[0m WARNING 05-17 16:42:40 worker_manager.py:344] Missed prefetch, fall back to loading delta 2 now
[36m(RayWorkerVllm pid=73241)[0m INFO 05-17 16:42:40 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=73241)[0m INFO 05-17 16:42:40 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=73384)[0m WARNING 05-17 16:42:40 worker_manager.py:344] Missed prefetch, fall back to loading delta 2 now
[36m(RayWorkerVllm pid=73384)[0m INFO 05-17 16:42:40 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=73384)[0m INFO 05-17 16:42:40 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:42:43 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.777 seconds
INFO 05-17 16:42:43 worker_manager.py:364] Main thread loading delta 2 done
WARNING 05-17 16:42:43 worker_manager.py:344] Missed prefetch, fall back to loading delta 11 now
INFO 05-17 16:42:43 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 16:42:43 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=73066)[0m INFO 05-17 16:42:44 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 3.491 seconds
[36m(RayWorkerVllm pid=73066)[0m INFO 05-17 16:42:44 worker_manager.py:364] Main thread loading delta 2 done
[36m(RayWorkerVllm pid=73241)[0m INFO 05-17 16:42:44 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 3.534 seconds
[36m(RayWorkerVllm pid=73384)[0m INFO 05-17 16:42:44 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 3.537 seconds
[36m(RayWorkerVllm pid=73384)[0m INFO 05-17 16:42:44 worker_manager.py:364] Main thread loading delta 2 done
[36m(RayWorkerVllm pid=73066)[0m WARNING 05-17 16:42:44 worker_manager.py:344] Missed prefetch, fall back to loading delta 11 now
[36m(RayWorkerVllm pid=73066)[0m INFO 05-17 16:42:44 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=73066)[0m INFO 05-17 16:42:44 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=73241)[0m INFO 05-17 16:42:44 worker_manager.py:364] Main thread loading delta 2 done
[36m(RayWorkerVllm pid=73241)[0m WARNING 05-17 16:42:44 worker_manager.py:344] Missed prefetch, fall back to loading delta 11 now
[36m(RayWorkerVllm pid=73241)[0m INFO 05-17 16:42:44 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=73241)[0m INFO 05-17 16:42:44 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=73384)[0m WARNING 05-17 16:42:44 worker_manager.py:344] Missed prefetch, fall back to loading delta 11 now
[36m(RayWorkerVllm pid=73384)[0m INFO 05-17 16:42:44 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=73384)[0m INFO 05-17 16:42:44 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:42:54 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 57 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 2.0%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=73066)[0m INFO 05-17 16:42:57 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 13.093 seconds
[36m(RayWorkerVllm pid=73066)[0m INFO 05-17 16:42:57 worker_manager.py:364] Main thread loading delta 11 done
[36m(RayWorkerVllm pid=73066)[0m WARNING 05-17 16:42:57 worker_manager.py:344] Missed prefetch, fall back to loading delta 13 now
[36m(RayWorkerVllm pid=73066)[0m INFO 05-17 16:42:57 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=73066)[0m INFO 05-17 16:42:57 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=73384)[0m INFO 05-17 16:43:00 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 15.545 seconds
[36m(RayWorkerVllm pid=73384)[0m INFO 05-17 16:43:00 worker_manager.py:364] Main thread loading delta 11 done
[36m(RayWorkerVllm pid=73384)[0m WARNING 05-17 16:43:00 worker_manager.py:344] Missed prefetch, fall back to loading delta 13 now
[36m(RayWorkerVllm pid=73384)[0m INFO 05-17 16:43:00 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=73384)[0m INFO 05-17 16:43:00 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=73241)[0m INFO 05-17 16:43:00 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 15.931 seconds
[36m(RayWorkerVllm pid=73241)[0m INFO 05-17 16:43:00 worker_manager.py:364] Main thread loading delta 11 done
[36m(RayWorkerVllm pid=73241)[0m WARNING 05-17 16:43:00 worker_manager.py:344] Missed prefetch, fall back to loading delta 13 now
[36m(RayWorkerVllm pid=73241)[0m INFO 05-17 16:43:00 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=73241)[0m INFO 05-17 16:43:00 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:43:01 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 18.195 seconds
INFO 05-17 16:43:02 worker_manager.py:364] Main thread loading delta 11 done
WARNING 05-17 16:43:02 worker_manager.py:344] Missed prefetch, fall back to loading delta 13 now
INFO 05-17 16:43:02 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 16:43:02 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:43:04 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 57 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 2.0%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=73066)[0m INFO 05-17 16:43:10 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 12.860 seconds
[36m(RayWorkerVllm pid=73066)[0m INFO 05-17 16:43:10 worker_manager.py:364] Main thread loading delta 13 done
[36m(RayWorkerVllm pid=73066)[0m WARNING 05-17 16:43:10 worker_manager.py:344] Missed prefetch, fall back to loading delta 14 now
[36m(RayWorkerVllm pid=73066)[0m INFO 05-17 16:43:10 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=73066)[0m INFO 05-17 16:43:10 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=73241)[0m INFO 05-17 16:43:13 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 13.187 seconds
[36m(RayWorkerVllm pid=73241)[0m INFO 05-17 16:43:13 worker_manager.py:364] Main thread loading delta 13 done
[36m(RayWorkerVllm pid=73241)[0m WARNING 05-17 16:43:14 worker_manager.py:344] Missed prefetch, fall back to loading delta 14 now
[36m(RayWorkerVllm pid=73241)[0m INFO 05-17 16:43:14 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=73241)[0m INFO 05-17 16:43:14 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:43:14 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 57 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 2.0%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=73384)[0m INFO 05-17 16:43:15 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 15.046 seconds
[36m(RayWorkerVllm pid=73384)[0m INFO 05-17 16:43:15 worker_manager.py:364] Main thread loading delta 13 done
[36m(RayWorkerVllm pid=73384)[0m WARNING 05-17 16:43:15 worker_manager.py:344] Missed prefetch, fall back to loading delta 14 now
[36m(RayWorkerVllm pid=73384)[0m INFO 05-17 16:43:15 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=73384)[0m INFO 05-17 16:43:15 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:43:23 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 21.542 seconds
INFO 05-17 16:43:23 worker_manager.py:364] Main thread loading delta 13 done
WARNING 05-17 16:43:23 worker_manager.py:344] Missed prefetch, fall back to loading delta 14 now
INFO 05-17 16:43:23 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 16:43:23 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:43:24 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 57 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 2.0%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=73066)[0m INFO 05-17 16:43:25 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 14.603 seconds
[36m(RayWorkerVllm pid=73066)[0m INFO 05-17 16:43:25 worker_manager.py:364] Main thread loading delta 14 done
[36m(RayWorkerVllm pid=73066)[0m WARNING 05-17 16:43:25 worker_manager.py:344] Missed prefetch, fall back to loading delta 22 now
[36m(RayWorkerVllm pid=73066)[0m INFO 05-17 16:43:25 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=73066)[0m INFO 05-17 16:43:25 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=73241)[0m INFO 05-17 16:43:28 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 13.978 seconds
[36m(RayWorkerVllm pid=73241)[0m INFO 05-17 16:43:28 worker_manager.py:364] Main thread loading delta 14 done
[36m(RayWorkerVllm pid=73241)[0m WARNING 05-17 16:43:28 worker_manager.py:344] Missed prefetch, fall back to loading delta 22 now
[36m(RayWorkerVllm pid=73241)[0m INFO 05-17 16:43:28 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=73241)[0m INFO 05-17 16:43:28 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=73384)[0m INFO 05-17 16:43:28 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 13.334 seconds
[36m(RayWorkerVllm pid=73384)[0m INFO 05-17 16:43:28 worker_manager.py:364] Main thread loading delta 14 done
[36m(RayWorkerVllm pid=73384)[0m WARNING 05-17 16:43:29 worker_manager.py:344] Missed prefetch, fall back to loading delta 22 now
[36m(RayWorkerVllm pid=73384)[0m INFO 05-17 16:43:29 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=73384)[0m INFO 05-17 16:43:29 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:43:34 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 57 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 2.0%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=73066)[0m INFO 05-17 16:43:36 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 10.782 seconds
[36m(RayWorkerVllm pid=73066)[0m INFO 05-17 16:43:36 worker_manager.py:364] Main thread loading delta 22 done
[36m(RayWorkerVllm pid=73066)[0m WARNING 05-17 16:43:36 worker_manager.py:344] Missed prefetch, fall back to loading delta 23 now
[36m(RayWorkerVllm pid=73066)[0m INFO 05-17 16:43:36 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=73066)[0m INFO 05-17 16:43:36 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:43:40 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 16.329 seconds
INFO 05-17 16:43:40 worker_manager.py:364] Main thread loading delta 14 done
WARNING 05-17 16:43:40 worker_manager.py:344] Missed prefetch, fall back to loading delta 22 now
INFO 05-17 16:43:40 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 16:43:40 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=73241)[0m INFO 05-17 16:43:40 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 12.168 seconds
[36m(RayWorkerVllm pid=73241)[0m INFO 05-17 16:43:40 worker_manager.py:364] Main thread loading delta 22 done
[36m(RayWorkerVllm pid=73241)[0m WARNING 05-17 16:43:40 worker_manager.py:344] Missed prefetch, fall back to loading delta 23 now
[36m(RayWorkerVllm pid=73241)[0m INFO 05-17 16:43:40 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=73241)[0m INFO 05-17 16:43:40 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:43:44 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 57 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 2.0%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=73384)[0m INFO 05-17 16:43:46 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 17.458 seconds
[36m(RayWorkerVllm pid=73384)[0m INFO 05-17 16:43:46 worker_manager.py:364] Main thread loading delta 22 done
[36m(RayWorkerVllm pid=73384)[0m WARNING 05-17 16:43:46 worker_manager.py:344] Missed prefetch, fall back to loading delta 23 now
[36m(RayWorkerVllm pid=73384)[0m INFO 05-17 16:43:46 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=73384)[0m INFO 05-17 16:43:46 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=73066)[0m INFO 05-17 16:43:47 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 10.798 seconds
[36m(RayWorkerVllm pid=73066)[0m INFO 05-17 16:43:47 worker_manager.py:364] Main thread loading delta 23 done
INFO 05-17 16:43:54 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 57 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 2.0%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=73241)[0m INFO 05-17 16:43:56 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 15.702 seconds
[36m(RayWorkerVllm pid=73241)[0m INFO 05-17 16:43:56 worker_manager.py:364] Main thread loading delta 23 done
[36m(RayWorkerVllm pid=73384)[0m INFO 05-17 16:43:56 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 10.080 seconds
[36m(RayWorkerVllm pid=73384)[0m INFO 05-17 16:43:56 worker_manager.py:364] Main thread loading delta 23 done
INFO 05-17 16:43:57 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 16.621 seconds
INFO 05-17 16:43:57 worker_manager.py:364] Main thread loading delta 22 done
WARNING 05-17 16:43:57 worker_manager.py:344] Missed prefetch, fall back to loading delta 23 now
INFO 05-17 16:43:57 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 16:43:57 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:44:03 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 6.550 seconds
INFO 05-17 16:44:03 worker_manager.py:364] Main thread loading delta 23 done
INFO 05-17 16:44:04 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 57 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 2.0%, CPU KV cache usage: 0.0%
INFO 05-17 16:44:09 metrics.py:276] Avg prompt throughput: 151.2 tokens/s, Avg generation throughput: 15.6 tokens/s, Running: 56 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 2.1%, CPU KV cache usage: 0.0%
INFO:     ::1:56806 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:44:16 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 25.5 tokens/s, Running: 54 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 2.1%, CPU KV cache usage: 0.0%
INFO:     ::1:56792 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:56750 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:56824 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:56816 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:56812 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:56810 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:44:22 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 24.4 tokens/s, Running: 50 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 2.0%, CPU KV cache usage: 0.0%
INFO:     ::1:56838 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:44:28 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 23.9 tokens/s, Running: 48 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 2.1%, CPU KV cache usage: 0.0%
INFO:     ::1:56822 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:56740 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:44:34 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 17.3 tokens/s, Running: 47 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 2.3%, CPU KV cache usage: 0.0%
INFO 05-17 16:44:41 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 27.7 tokens/s, Running: 47 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 2.4%, CPU KV cache usage: 0.0%
INFO 05-17 16:44:47 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 22.9 tokens/s, Running: 47 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 2.5%, CPU KV cache usage: 0.0%
INFO 05-17 16:44:53 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 22.9 tokens/s, Running: 47 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 2.6%, CPU KV cache usage: 0.0%
INFO:     ::1:56856 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:44:59 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 23.7 tokens/s, Running: 46 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 2.7%, CPU KV cache usage: 0.0%
INFO 05-17 16:45:04 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 18.3 tokens/s, Running: 46 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 2.9%, CPU KV cache usage: 0.0%
INFO:     ::1:56844 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:45:10 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 29.8 tokens/s, Running: 44 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 2.9%, CPU KV cache usage: 0.0%
INFO:     ::1:56786 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:45:15 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 24.7 tokens/s, Running: 43 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.0%, CPU KV cache usage: 0.0%
INFO:     ::1:56756 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:45:21 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 24.2 tokens/s, Running: 43 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.1%, CPU KV cache usage: 0.0%
INFO 05-17 16:45:26 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 24.2 tokens/s, Running: 42 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.0%, CPU KV cache usage: 0.0%
INFO:     ::1:56866 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:45:31 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 23.6 tokens/s, Running: 41 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.1%, CPU KV cache usage: 0.0%
INFO:     ::1:56736 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:56780 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:45:37 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 23.0 tokens/s, Running: 40 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.3%, CPU KV cache usage: 0.0%
INFO:     ::1:56894 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:45:42 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 22.3 tokens/s, Running: 39 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.2%, CPU KV cache usage: 0.0%
INFO 05-17 16:45:47 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 21.9 tokens/s, Running: 39 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.3%, CPU KV cache usage: 0.0%
INFO 05-17 16:45:53 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 21.8 tokens/s, Running: 39 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.4%, CPU KV cache usage: 0.0%
INFO 05-17 16:45:58 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 21.9 tokens/s, Running: 39 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.5%, CPU KV cache usage: 0.0%
INFO:     ::1:56722 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:46:03 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 21.8 tokens/s, Running: 38 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.6%, CPU KV cache usage: 0.0%
INFO 05-17 16:46:09 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 21.5 tokens/s, Running: 38 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.7%, CPU KV cache usage: 0.0%
INFO:     ::1:56900 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:56846 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:56726 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:46:14 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 14.1 tokens/s, Running: 35 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.5%, CPU KV cache usage: 0.0%
INFO 05-17 16:46:19 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 26.1 tokens/s, Running: 35 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.6%, CPU KV cache usage: 0.0%
INFO:     ::1:56860 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:46:24 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 19.5 tokens/s, Running: 34 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.6%, CPU KV cache usage: 0.0%
INFO 05-17 16:46:30 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 19.4 tokens/s, Running: 34 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.7%, CPU KV cache usage: 0.0%
INFO 05-17 16:46:35 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 19.3 tokens/s, Running: 34 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.9%, CPU KV cache usage: 0.0%
INFO 05-17 16:46:40 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 19.4 tokens/s, Running: 34 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.9%, CPU KV cache usage: 0.0%
INFO:     ::1:56752 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:46:45 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 19.1 tokens/s, Running: 33 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.8%, CPU KV cache usage: 0.0%
INFO 05-17 16:46:51 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 18.9 tokens/s, Running: 33 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.9%, CPU KV cache usage: 0.0%
INFO 05-17 16:46:56 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 18.8 tokens/s, Running: 33 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.0%, CPU KV cache usage: 0.0%
INFO 05-17 16:47:01 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 18.6 tokens/s, Running: 33 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.2%, CPU KV cache usage: 0.0%
INFO:     ::1:56775 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:47:07 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 18.3 tokens/s, Running: 32 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.1%, CPU KV cache usage: 0.0%
INFO 05-17 16:47:12 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 18.3 tokens/s, Running: 30 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.9%, CPU KV cache usage: 0.0%
INFO:     ::1:56872 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:56769 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:56826 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:56728 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:47:17 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 16.7 tokens/s, Running: 28 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.7%, CPU KV cache usage: 0.0%
INFO:     ::1:56754 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:47:22 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 15.8 tokens/s, Running: 27 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.7%, CPU KV cache usage: 0.0%
INFO 05-17 16:47:28 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 15.5 tokens/s, Running: 27 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.8%, CPU KV cache usage: 0.0%
INFO 05-17 16:47:33 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 15.6 tokens/s, Running: 27 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.9%, CPU KV cache usage: 0.0%
INFO:     ::1:56746 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:47:38 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 15.4 tokens/s, Running: 26 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.8%, CPU KV cache usage: 0.0%
INFO 05-17 16:47:43 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 15.0 tokens/s, Running: 26 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.8%, CPU KV cache usage: 0.0%
INFO 05-17 16:47:48 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 14.9 tokens/s, Running: 26 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.9%, CPU KV cache usage: 0.0%
INFO 05-17 16:47:54 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 15.0 tokens/s, Running: 26 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.0%, CPU KV cache usage: 0.0%
INFO:     ::1:56852 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:47:59 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 15.2 tokens/s, Running: 25 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.0%, CPU KV cache usage: 0.0%
INFO 05-17 16:48:04 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 14.6 tokens/s, Running: 25 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.0%, CPU KV cache usage: 0.0%
INFO 05-17 16:48:10 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 16.6 tokens/s, Running: 25 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.1%, CPU KV cache usage: 0.0%
INFO 05-17 16:48:16 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 15.7 tokens/s, Running: 24 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.0%, CPU KV cache usage: 0.0%
INFO:     ::1:56710 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:48:23 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 15.1 tokens/s, Running: 24 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.2%, CPU KV cache usage: 0.0%
INFO 05-17 16:48:29 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 15.0 tokens/s, Running: 24 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.3%, CPU KV cache usage: 0.0%
INFO:     ::1:56804 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:48:35 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 14.9 tokens/s, Running: 23 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.1%, CPU KV cache usage: 0.0%
INFO 05-17 16:48:42 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 14.5 tokens/s, Running: 22 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.0%, CPU KV cache usage: 0.0%
INFO:     ::1:56864 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:56790 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:48:48 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.4 tokens/s, Running: 21 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.0%, CPU KV cache usage: 0.0%
INFO 05-17 16:48:54 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 11.0 tokens/s, Running: 21 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.1%, CPU KV cache usage: 0.0%
INFO 05-17 16:48:59 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 15.5 tokens/s, Running: 21 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.1%, CPU KV cache usage: 0.0%
INFO 05-17 16:49:06 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.2 tokens/s, Running: 21 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.2%, CPU KV cache usage: 0.0%
INFO:     ::1:56700 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:49:12 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.6 tokens/s, Running: 20 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.1%, CPU KV cache usage: 0.0%
INFO:     ::1:56830 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:49:17 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.3 tokens/s, Running: 19 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.9%, CPU KV cache usage: 0.0%
INFO 05-17 16:49:23 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.0 tokens/s, Running: 19 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.0%, CPU KV cache usage: 0.0%
INFO:     ::1:56888 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:56784 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:49:28 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.7 tokens/s, Running: 17 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.7%, CPU KV cache usage: 0.0%
INFO 05-17 16:49:34 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 12.5 tokens/s, Running: 17 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.8%, CPU KV cache usage: 0.0%
INFO:     ::1:56870 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:49:39 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 16.4 tokens/s, Running: 16 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.6%, CPU KV cache usage: 0.0%
INFO 05-17 16:49:44 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 15.0 tokens/s, Running: 16 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.7%, CPU KV cache usage: 0.0%
INFO 05-17 16:49:49 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 15.0 tokens/s, Running: 16 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.8%, CPU KV cache usage: 0.0%
INFO 05-17 16:49:55 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 15.0 tokens/s, Running: 16 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.8%, CPU KV cache usage: 0.0%
INFO:     ::1:56714 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:50:01 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 15.7 tokens/s, Running: 15 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.7%, CPU KV cache usage: 0.0%
INFO 05-17 16:50:06 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 16.1 tokens/s, Running: 15 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.8%, CPU KV cache usage: 0.0%
INFO 05-17 16:50:12 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 16.0 tokens/s, Running: 15 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.9%, CPU KV cache usage: 0.0%
INFO:     ::1:56874 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:50:17 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 15.6 tokens/s, Running: 14 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.6%, CPU KV cache usage: 0.0%
INFO:     ::1:56862 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:50:23 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 15.4 tokens/s, Running: 13 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.5%, CPU KV cache usage: 0.0%
INFO:     ::1:56892 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:50:28 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 15.4 tokens/s, Running: 12 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.2%, CPU KV cache usage: 0.0%
INFO 05-17 16:50:34 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.3 tokens/s, Running: 12 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.3%, CPU KV cache usage: 0.0%
INFO:     ::1:56730 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:50:39 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 16.3 tokens/s, Running: 11 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.1%, CPU KV cache usage: 0.0%
INFO 05-17 16:50:44 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.8 tokens/s, Running: 11 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.2%, CPU KV cache usage: 0.0%
INFO:     ::1:56788 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:50:50 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 12.8 tokens/s, Running: 10 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.0%, CPU KV cache usage: 0.0%
INFO 05-17 16:50:55 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 12.6 tokens/s, Running: 10 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.0%, CPU KV cache usage: 0.0%
INFO 05-17 16:51:01 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 12.6 tokens/s, Running: 10 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.1%, CPU KV cache usage: 0.0%
INFO 05-17 16:51:07 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 12.7 tokens/s, Running: 9 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 2.9%, CPU KV cache usage: 0.0%
INFO:     ::1:56808 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:56764 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:51:12 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 11.9 tokens/s, Running: 8 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 2.6%, CPU KV cache usage: 0.0%
INFO 05-17 16:51:17 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 12.1 tokens/s, Running: 8 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 2.7%, CPU KV cache usage: 0.0%
INFO:     ::1:56886 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:56720 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:51:23 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 11.7 tokens/s, Running: 6 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 2.1%, CPU KV cache usage: 0.0%
INFO 05-17 16:51:28 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 9.1 tokens/s, Running: 5 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.8%, CPU KV cache usage: 0.0%
INFO:     ::1:56896 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:56854 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:51:33 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 8.4 tokens/s, Running: 4 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.5%, CPU KV cache usage: 0.0%
INFO 05-17 16:51:38 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 7.7 tokens/s, Running: 4 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.5%, CPU KV cache usage: 0.0%
INFO 05-17 16:51:44 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 7.6 tokens/s, Running: 4 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.6%, CPU KV cache usage: 0.0%
INFO 05-17 16:51:49 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 7.6 tokens/s, Running: 4 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.6%, CPU KV cache usage: 0.0%
INFO:     ::1:56848 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:51:54 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 6.7 tokens/s, Running: 3 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%
INFO 05-17 16:51:59 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 5.7 tokens/s, Running: 3 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%
INFO 05-17 16:52:05 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 5.7 tokens/s, Running: 3 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.3%, CPU KV cache usage: 0.0%
INFO:     ::1:56832 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:52:10 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 5.4 tokens/s, Running: 2 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.9%, CPU KV cache usage: 0.0%
INFO:     ::1:56794 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:52:15 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.9 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.5%, CPU KV cache usage: 0.0%
INFO 05-17 16:52:20 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.5%, CPU KV cache usage: 0.0%
INFO 05-17 16:52:25 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 3.9 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.5%, CPU KV cache usage: 0.0%
INFO 05-17 16:52:30 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 3.9 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.5%, CPU KV cache usage: 0.0%
INFO:     ::1:56758 - "POST /v1/completions HTTP/1.1" 200 OK
Results written to .artifact/benchmarks/results/f4be4c27-d6d2-43c9-8522-9fa20c611483.jsonl
Killing process 65255...
/var/spool/slurmd/job3676855/slurm_script: line 45: 65189 Killed                  apptainer run --nv --home /mnt/petrelfs/huqinghao/xzyao/:/home/xiayao --bind /mnt/petrelfs/huqinghao/xzyao/code/vllm:/vllm --bind /mnt/petrelfs/huqinghao/xzyao/code/triteia:/triteia --env PYTHONPATH=/vllm:/triteia --env CUDA_LAUNCH_BLOCKING=1 --env TVM_TARGET=nvidia/nvidia-a100 --env TRANSFORMERS_OFFLINE=1 --env NUMEXPR_MAX_THREADS=128 --env USE_BITBLAS=1 --env BITBLAS_TARGET=nvidia/nvidia-a100 --env RAY_DEDUP_LOGS=0 --workdir /vllm /mnt/petrelfs/huqinghao/xzyao/images/vllm-0.4.1.sif python3 /vllm/vllm/entrypoints/openai/api_server.py --model /vllm/.idea/full_models/Llama-2-13b-hf --enable-delta --disable-log-requests --gpu-memory-utilization 0.85 --delta-modules delta-1=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-1 delta-2=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-2 delta-3=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-3 delta-4=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-4 delta-5=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-5 delta-6=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-6 delta-7=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-7 delta-8=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-8 delta-9=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-9 delta-10=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-10 delta-11=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-11 delta-12=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-12 delta-13=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-13 delta-14=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-14 delta-15=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-15 delta-16=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-16 delta-17=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-17 delta-18=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-18 delta-19=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-19 delta-20=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-20 delta-21=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-21 delta-22=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-22 delta-23=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-23 delta-24=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-24 delta-25=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-25 delta-26=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-26 delta-27=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-27 delta-28=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-28 delta-29=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-29 delta-30=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-30 delta-31=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-31 delta-32=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-32 --max-deltas 24 --max-cpu-deltas 32 --tensor-parallel-size 4 --enforce-eager
