/mnt/hwfile/huqinghao/miniconda3/bin/python
2024-05-17 11:09:33,851 - INFO - Note: detected 128 virtual cores but NumExpr set to maximum of 64, check "NUMEXPR_MAX_THREADS" environment variable.
2024-05-17 11:09:33,851 - INFO - Note: NumExpr detected 128 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
2024-05-17 11:09:33,851 - INFO - NumExpr defaulting to 8 threads.
2024-05-17 11:09:35,093	INFO scripts.py:1182 -- Did not find any active Ray processes.
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c74070>: Failed to establish a new connection: [Errno 111] Connection refused'))

==========
== CUDA ==
==========

CUDA Version 12.1.0

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

*************************
** DEPRECATION NOTICE! **
*************************
THIS IMAGE IS DEPRECATED and is scheduled for DELETION.
    https://gitlab.com/nvidia/container-images/cuda/blob/master/doc/support-policy.md

Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c75450>: Failed to establish a new connection: [Errno 111] Connection refused'))
INFO 05-17 11:09:50 api_server.py:191] vLLM API server version 0.3.3
INFO 05-17 11:09:50 api_server.py:192] args: Namespace(host=None, port=8000, uvicorn_log_level='info', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_key=None, served_model_name=None, lora_modules=[], delta_modules=[Delta(name='delta-1', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-1'), Delta(name='delta-2', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-2'), Delta(name='delta-3', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-3'), Delta(name='delta-4', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-4'), Delta(name='delta-5', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-5'), Delta(name='delta-6', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-6'), Delta(name='delta-7', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-7'), Delta(name='delta-8', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-8'), Delta(name='delta-9', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-9'), Delta(name='delta-10', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-10'), Delta(name='delta-11', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-11'), Delta(name='delta-12', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-12'), Delta(name='delta-13', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-13'), Delta(name='delta-14', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-14'), Delta(name='delta-15', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-15'), Delta(name='delta-16', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-16'), Delta(name='delta-17', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-17'), Delta(name='delta-18', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-18'), Delta(name='delta-19', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-19'), Delta(name='delta-20', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-20'), Delta(name='delta-21', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-21'), Delta(name='delta-22', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-22'), Delta(name='delta-23', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-23'), Delta(name='delta-24', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-24'), Delta(name='delta-25', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-25'), Delta(name='delta-26', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-26'), Delta(name='delta-27', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-27'), Delta(name='delta-28', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-28'), Delta(name='delta-29', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-29'), Delta(name='delta-30', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-30'), Delta(name='delta-31', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-31'), Delta(name='delta-32', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-32'), Delta(name='delta-33', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-33'), Delta(name='delta-34', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-34'), Delta(name='delta-35', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-35'), Delta(name='delta-36', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-36'), Delta(name='delta-37', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-37'), Delta(name='delta-38', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-38'), Delta(name='delta-39', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-39'), Delta(name='delta-40', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-40'), Delta(name='delta-41', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-41'), Delta(name='delta-42', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-42'), Delta(name='delta-43', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-43'), Delta(name='delta-44', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-44'), Delta(name='delta-45', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-45'), Delta(name='delta-46', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-46'), Delta(name='delta-47', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-47'), Delta(name='delta-48', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-48'), Delta(name='delta-49', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-49'), Delta(name='delta-50', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-50'), Delta(name='delta-51', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-51'), Delta(name='delta-52', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-52'), Delta(name='delta-53', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-53'), Delta(name='delta-54', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-54'), Delta(name='delta-55', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-55'), Delta(name='delta-56', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-56'), Delta(name='delta-57', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-57'), Delta(name='delta-58', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-58'), Delta(name='delta-59', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-59'), Delta(name='delta-60', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-60'), Delta(name='delta-61', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-61'), Delta(name='delta-62', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-62'), Delta(name='delta-63', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-63'), Delta(name='delta-64', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-64')], swap_modules=[], chat_template=None, response_role='assistant', ssl_keyfile=None, ssl_certfile=None, ssl_ca_certs=None, ssl_cert_reqs=0, root_path=None, middleware=[], model='/vllm/.idea/full_models/Llama-2-13b-hf', tokenizer=None, revision=None, code_revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=False, download_dir=None, load_format='auto', dtype='auto', kv_cache_dtype='auto', max_model_len=None, worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=4, max_parallel_loading_workers=None, ray_workers_use_nsight=False, block_size=16, enable_prefix_caching=False, seed=0, swap_space=4, gpu_memory_utilization=0.85, max_num_batched_tokens=None, max_num_seqs=256, max_logprobs=5, disable_log_stats=False, quantization=None, enforce_eager=True, max_context_len_to_capture=8192, disable_custom_all_reduce=False, tokenizer_pool_size=0, tokenizer_pool_type='ray', tokenizer_pool_extra_config=None, enable_lora=False, max_loras=1, max_lora_rank=64, lora_extra_vocab_size=256, lora_dtype='auto', max_cpu_loras=32, enable_delta=True, max_deltas=24, max_cpu_deltas=32, max_delta_bitwidth=4, device='auto', image_input_type=None, image_token_id=None, image_input_shape=None, image_feature_size=None, scheduler_delay_factor=0.0, enable_prefetch=False, scheduler_policy='fcfs', max_swap_slots=1, max_cpu_models=4, enable_swap=False, engine_use_ray=False, disable_log_requests=True, max_log_len=None)
2024-05-17 11:09:53,621	INFO worker.py:1749 -- Started a local Ray instance.
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c75d20>: Failed to establish a new connection: [Errno 111] Connection refused'))
INFO 05-17 11:09:56 llm_engine.py:90] Initializing an LLM engine (v0.3.3) with config: model='/vllm/.idea/full_models/Llama-2-13b-hf', tokenizer='/vllm/.idea/full_models/Llama-2-13b-hf', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, lora_config=None, delta_config=DeltaConfig(max_deltas=24, max_bitwidth=4, delta_dtype=torch.int8, max_cpu_deltas=32, delta_extra_vocab_size=0, pack_factor=Fraction(2, 1), kernel=<QuantKernel.TRITON: 'triton'>), swap_config=None, max_seq_len=4096, download_dir=None, load_format=auto, tensor_parallel_size=4, disable_custom_all_reduce=False, quantization=None, enforce_eager=True, kv_cache_dtype=auto, device_config=cuda, seed=0)
INFO 05-17 11:09:56 llm_engine.py:243] ignored verifying delta_config
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c75cf0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c75420>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c741f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c765f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c76ec0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c76e30>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c76560>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c74430>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c755d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c76080>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c77790>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c759c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c750f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c74790>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c76920>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c76a10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c769b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c76980>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c74550>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c74fd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c750c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c77460>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c75330>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c74640>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c766b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c76f80>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c770a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c77340>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c76aa0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c761d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c74ee0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c748e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c77610>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c75ba0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c752d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c742b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c77b20>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c77ca0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c77940>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c74520>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c75000>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c758d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c75450>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc9508380a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c763b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c76a40>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c77c40>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c779d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c4fd90>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c75960>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c76bc0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c772b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c767a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c74ee0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c774c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c76b60>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c76da0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c77a90>: Failed to establish a new connection: [Errno 111] Connection refused'))
Using bitblas
WARNING 05-17 11:19:36 models.py:48] Using bitblas delta modules
INFO 05-17 11:19:36 selector.py:16] Using FlashAttention backend.
[36m(RayWorkerVllm pid=94020)[0m Exception ignored in: <function TempDirectory.__del__ at 0x7f00c153e200>
[36m(RayWorkerVllm pid=94020)[0m Traceback (most recent call last):
[36m(RayWorkerVllm pid=94020)[0m   File "/home/xiayao/.local/lib/python3.10/site-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 145, in __del__
[36m(RayWorkerVllm pid=94020)[0m     self.remove()
[36m(RayWorkerVllm pid=94020)[0m   File "/home/xiayao/.local/lib/python3.10/site-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 121, in remove
[36m(RayWorkerVllm pid=94020)[0m     if self.temp_dir:
[36m(RayWorkerVllm pid=94020)[0m AttributeError: 'TempDirectory' object has no attribute 'temp_dir'
[36m(RayWorkerVllm pid=94212)[0m Exception ignored in: <function TempDirectory.__del__ at 0x7f74e0952200>
[36m(RayWorkerVllm pid=94212)[0m Traceback (most recent call last):
[36m(RayWorkerVllm pid=94212)[0m   File "/home/xiayao/.local/lib/python3.10/site-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 145, in __del__
[36m(RayWorkerVllm pid=94212)[0m     self.remove()
[36m(RayWorkerVllm pid=94212)[0m   File "/home/xiayao/.local/lib/python3.10/site-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 121, in remove
[36m(RayWorkerVllm pid=94212)[0m     if self.temp_dir:
[36m(RayWorkerVllm pid=94212)[0m AttributeError: 'TempDirectory' object has no attribute 'temp_dir'
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c77340>: Failed to establish a new connection: [Errno 111] Connection refused'))
[36m(RayWorkerVllm pid=94020)[0m Exception ignored in: <function TempDirectory.__del__ at 0x7f00c153e200>
[36m(RayWorkerVllm pid=94020)[0m Traceback (most recent call last):
[36m(RayWorkerVllm pid=94020)[0m   File "/home/xiayao/.local/lib/python3.10/site-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 145, in __del__
[36m(RayWorkerVllm pid=94020)[0m     self.remove()
[36m(RayWorkerVllm pid=94020)[0m   File "/home/xiayao/.local/lib/python3.10/site-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 121, in remove
[36m(RayWorkerVllm pid=94020)[0m     if self.temp_dir:
[36m(RayWorkerVllm pid=94020)[0m AttributeError: 'TempDirectory' object has no attribute 'temp_dir'
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950838520>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c75bd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c77c10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c77a00>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c76890>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c746d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc9508389a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c74880>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c76f80>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c770a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c77d00>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950838340>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c75810>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c75660>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c76a10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c76b00>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c745b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950838460>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c766e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c77070>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c77d90>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c77940>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950838be0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c77fa0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c77c10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c77a00>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c76890>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c758d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc9508392a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c74370>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c76c20>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c77970>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c77af0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950838820>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c77fd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c77940>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c77d90>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c77070>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c77100>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c74df0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c746a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c76320>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c768f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c774f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c75690>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c76020>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c76050>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c776d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c76d40>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c76a70>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950839720>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c76320>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c768f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[36m(RayWorkerVllm pid=94020)[0m Using bitblas
[36m(RayWorkerVllm pid=94212)[0m Using bitblas
[36m(RayWorkerVllm pid=95226)[0m Using bitblas
[36m(RayWorkerVllm pid=94020)[0m BitBLAS Operator not loaded, retrying in 5 seconds...
[36m(RayWorkerVllm pid=94020)[0m Error: [Errno 17] File exists: '/home/xiayao/.cache/bitblas/nvidia/nvidia-a100/c96df0f34eb23be516ef0126651d4e78b151337f28ebc87cc5492d79d135855f/tvm_rt_mod'
[36m(RayWorkerVllm pid=94212)[0m BitBLAS Operator not loaded, retrying in 5 seconds...
[36m(RayWorkerVllm pid=94212)[0m Error: [Errno 17] File exists: '/home/xiayao/.cache/bitblas/nvidia/nvidia-a100/c96df0f34eb23be516ef0126651d4e78b151337f28ebc87cc5492d79d135855f/tvm_rt_mod'
[36m(RayWorkerVllm pid=94020)[0m BitBLAS Operator not loaded, retrying in 5 seconds...
[36m(RayWorkerVllm pid=94020)[0m Error: [Errno 17] File exists: '/home/xiayao/.cache/bitblas/nvidia/nvidia-a100/c96df0f34eb23be516ef0126651d4e78b151337f28ebc87cc5492d79d135855f/tvm_rt_mod'
[36m(RayWorkerVllm pid=95226)[0m WARNING 05-17 11:28:16 models.py:48] Using bitblas delta modules
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:28:16 selector.py:16] Using FlashAttention backend.
[36m(RayWorkerVllm pid=94212)[0m WARNING 05-17 11:28:22 models.py:48] Using bitblas delta modules
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:28:22 selector.py:16] Using FlashAttention backend.
[36m(RayWorkerVllm pid=94020)[0m WARNING 05-17 11:28:27 models.py:48] Using bitblas delta modules
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:28:27 selector.py:16] Using FlashAttention backend.
INFO 05-17 11:28:40 model_runner.py:161] Loading model weights took 6.1114 GB
INFO 05-17 11:28:40 worker_manager.py:297] Starting prefetching thread
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:28:42 model_runner.py:161] Loading model weights took 6.1114 GB
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:28:42 worker_manager.py:297] Starting prefetching thread
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:28:42 model_runner.py:161] Loading model weights took 6.1114 GB
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:28:42 worker_manager.py:297] Starting prefetching thread
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:28:42 model_runner.py:161] Loading model weights took 6.1114 GB
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:28:42 worker_manager.py:297] Starting prefetching thread
WARNING 05-17 11:28:44 quant_linear_triton.py:557] We should warm up the kernel here 
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c774f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc950c75690>: Failed to establish a new connection: [Errno 111] Connection refused'))
[36m(RayWorkerVllm pid=95226)[0m WARNING 05-17 11:28:45 quant_linear_triton.py:557] We should warm up the kernel here 
[36m(RayWorkerVllm pid=94020)[0m WARNING 05-17 11:28:45 quant_linear_triton.py:557] We should warm up the kernel here 
[36m(RayWorkerVllm pid=94212)[0m WARNING 05-17 11:28:45 quant_linear_triton.py:557] We should warm up the kernel here 
INFO 05-17 11:28:59 ray_gpu_executor.py:275] # GPU blocks: 6431, # CPU blocks: 1310
INFO 05-17 11:29:02 scheduler.py:136] Using fcfs policy.
INFO 05-17 11:29:02 block_manager.py:264] disable automatic prefix caching
WARNING 05-17 11:29:02 serving_chat.py:373] No chat template provided. Chat API will not work.
INFO:     Started server process [86217]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     ::1:52520 - "GET /sysinfo HTTP/1.1" 200 OK
Translating from base-model to /vllm/.idea/full_models/Llama-2-13b-hf
Warming up starts
{'id': 22, 'prompt': 'USER: Write a python one line lambda function that calculates mean of two lists, without using any imported libraries. The entire function should fit on a single line, start with this. mean = lambda A:\nASSISTANT:', 'timestamp': 0, 'model': 'delta-20', 'min_tokens': 32, 'max_tokens': 32}
Prefetching is disabled
WARNING 05-17 11:29:06 worker_manager.py:344] Missed prefetch, fall back to loading delta 20 now
INFO 05-17 11:29:06 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 11:29:06 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=94020)[0m WARNING 05-17 11:29:06 worker_manager.py:344] Missed prefetch, fall back to loading delta 20 now
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:29:06 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:29:06 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=94212)[0m WARNING 05-17 11:29:06 worker_manager.py:344] Missed prefetch, fall back to loading delta 20 now
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:29:06 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:29:06 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=95226)[0m WARNING 05-17 11:29:06 worker_manager.py:344] Missed prefetch, fall back to loading delta 20 now
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:29:06 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:29:06 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 11:29:08 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.738 seconds
INFO 05-17 11:29:08 worker_manager.py:364] Main thread loading delta 20 done
INFO 05-17 11:29:08 worker_manager.py:379] [1715916548.6047826] activating delta
INFO 05-17 11:29:08 worker_manager.py:384] [1715916548.701817] CPU -> GPU time: 0.0970
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:29:09 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.285 seconds
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:29:09 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.212 seconds
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:29:09 worker_manager.py:364] Main thread loading delta 20 done
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:29:09 worker_manager.py:379] [1715916549.0730133] activating delta
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:29:09 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.259 seconds
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:29:09 worker_manager.py:364] Main thread loading delta 20 done
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:29:09 worker_manager.py:379] [1715916549.1588602] activating delta
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:29:09 worker_manager.py:364] Main thread loading delta 20 done
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:29:09 worker_manager.py:379] [1715916549.138835] activating delta
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:29:09 worker_manager.py:384] [1715916549.2191923] CPU -> GPU time: 0.1461
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:29:09 worker_manager.py:384] [1715916549.296482] CPU -> GPU time: 0.1376
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:29:09 worker_manager.py:384] [1715916549.2879915] CPU -> GPU time: 0.1491
INFO 05-17 11:29:09 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%
INFO 05-17 11:29:14 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%
INFO:     ::1:52522 - "POST /v1/completions HTTP/1.1" 200 OK
Warming up ends
Issuing queries
sending 1 queries at 0.8
sending 1 queries at 2.1
sending 1 queries at 3.0
sending 1 queries at 3.8000000000000003
sending 1 queries at 4.4
sending 1 queries at 5.4
sending 1 queries at 6.0
sending 1 queries at 8.200000000000001
sending 1 queries at 11.5
sending 1 queries at 12.0
sending 1 queries at 13.600000000000001
sending 1 queries at 14.3
sending 1 queries at 15.200000000000001
sending 2 queries at 17.8
sending 2 queries at 17.900000000000002
sending 1 queries at 19.700000000000003
sending 1 queries at 21.200000000000003
sending 1 queries at 23.3
sending 1 queries at 27.1
sending 1 queries at 28.700000000000003
sending 1 queries at 29.3
Prefetching is disabled
WARNING 05-17 11:29:18 worker_manager.py:344] Missed prefetch, fall back to loading delta 38 now
INFO 05-17 11:29:18 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 11:29:18 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=94020)[0m WARNING 05-17 11:29:18 worker_manager.py:344] Missed prefetch, fall back to loading delta 38 now
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:29:18 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:29:18 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=94212)[0m WARNING 05-17 11:29:18 worker_manager.py:344] Missed prefetch, fall back to loading delta 38 now
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:29:18 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:29:18 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=95226)[0m WARNING 05-17 11:29:18 worker_manager.py:344] Missed prefetch, fall back to loading delta 38 now
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:29:18 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:29:18 models.py:263] [main] Lossless Compression Disabled
Prefetching is disabled
INFO 05-17 11:29:20 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.731 seconds
INFO 05-17 11:29:20 worker_manager.py:364] Main thread loading delta 38 done
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:29:20 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.270 seconds
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:29:20 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.274 seconds
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:29:20 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.273 seconds
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:29:20 worker_manager.py:364] Main thread loading delta 38 done
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:29:20 worker_manager.py:364] Main thread loading delta 38 done
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:29:20 worker_manager.py:364] Main thread loading delta 38 done
Prefetching is disabled
INFO 05-17 11:29:21 metrics.py:276] Avg prompt throughput: 3.2 tokens/s, Avg generation throughput: 1.9 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
WARNING 05-17 11:29:21 worker_manager.py:344] Missed prefetch, fall back to loading delta 17 now
INFO 05-17 11:29:21 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 11:29:21 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=94020)[0m WARNING 05-17 11:29:21 worker_manager.py:344] Missed prefetch, fall back to loading delta 17 now
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:29:21 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:29:21 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=94212)[0m WARNING 05-17 11:29:21 worker_manager.py:344] Missed prefetch, fall back to loading delta 17 now
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:29:21 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:29:21 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=95226)[0m WARNING 05-17 11:29:21 worker_manager.py:344] Missed prefetch, fall back to loading delta 17 now
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:29:21 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:29:21 models.py:263] [main] Lossless Compression Disabled
Prefetching is disabled
Prefetching is disabled
INFO 05-17 11:29:22 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.694 seconds
INFO 05-17 11:29:23 worker_manager.py:364] Main thread loading delta 17 done
Prefetching is disabled
WARNING 05-17 11:29:23 worker_manager.py:344] Missed prefetch, fall back to loading delta 4 now
INFO 05-17 11:29:23 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 11:29:23 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:29:23 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.208 seconds
Prefetching is disabled
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:29:23 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.296 seconds
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:29:23 worker_manager.py:364] Main thread loading delta 17 done
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:29:23 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.245 seconds
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:29:23 worker_manager.py:364] Main thread loading delta 17 done
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:29:23 worker_manager.py:364] Main thread loading delta 17 done
[36m(RayWorkerVllm pid=94212)[0m WARNING 05-17 11:29:23 worker_manager.py:344] Missed prefetch, fall back to loading delta 4 now
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:29:23 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:29:23 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=94020)[0m WARNING 05-17 11:29:23 worker_manager.py:344] Missed prefetch, fall back to loading delta 4 now
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:29:23 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:29:23 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=95226)[0m WARNING 05-17 11:29:23 worker_manager.py:344] Missed prefetch, fall back to loading delta 4 now
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:29:23 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:29:23 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 11:29:24 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.675 seconds
INFO 05-17 11:29:24 worker_manager.py:364] Main thread loading delta 4 done
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:29:25 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.171 seconds
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:29:25 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.156 seconds
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:29:25 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.158 seconds
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:29:25 worker_manager.py:364] Main thread loading delta 4 done
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:29:25 worker_manager.py:364] Main thread loading delta 4 done
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:29:26 worker_manager.py:364] Main thread loading delta 4 done
Prefetching is disabled
INFO 05-17 11:29:26 metrics.py:276] Avg prompt throughput: 7.6 tokens/s, Avg generation throughput: 0.4 tokens/s, Running: 3 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%
WARNING 05-17 11:29:26 worker_manager.py:344] Missed prefetch, fall back to loading delta 1 now
INFO 05-17 11:29:26 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 11:29:26 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=94020)[0m WARNING 05-17 11:29:26 worker_manager.py:344] Missed prefetch, fall back to loading delta 1 now
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:29:26 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:29:26 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=94212)[0m WARNING 05-17 11:29:26 worker_manager.py:344] Missed prefetch, fall back to loading delta 1 now
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:29:26 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:29:26 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=95226)[0m WARNING 05-17 11:29:26 worker_manager.py:344] Missed prefetch, fall back to loading delta 1 now
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:29:26 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:29:26 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 11:29:28 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.668 seconds
INFO 05-17 11:29:28 worker_manager.py:364] Main thread loading delta 1 done
WARNING 05-17 11:29:28 worker_manager.py:344] Missed prefetch, fall back to loading delta 41 now
INFO 05-17 11:29:28 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 11:29:28 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:29:28 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.191 seconds
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:29:28 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.193 seconds
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:29:28 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.209 seconds
Prefetching is disabled
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:29:29 worker_manager.py:364] Main thread loading delta 1 done
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:29:29 worker_manager.py:364] Main thread loading delta 1 done
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:29:29 worker_manager.py:364] Main thread loading delta 1 done
[36m(RayWorkerVllm pid=94020)[0m WARNING 05-17 11:29:29 worker_manager.py:344] Missed prefetch, fall back to loading delta 41 now
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:29:29 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:29:29 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=94212)[0m WARNING 05-17 11:29:29 worker_manager.py:344] Missed prefetch, fall back to loading delta 41 now
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:29:29 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:29:29 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=95226)[0m WARNING 05-17 11:29:29 worker_manager.py:344] Missed prefetch, fall back to loading delta 41 now
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:29:29 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:29:29 models.py:263] [main] Lossless Compression Disabled
Prefetching is disabled
INFO 05-17 11:29:30 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.679 seconds
INFO 05-17 11:29:30 worker_manager.py:364] Main thread loading delta 41 done
WARNING 05-17 11:29:30 worker_manager.py:344] Missed prefetch, fall back to loading delta 42 now
INFO 05-17 11:29:30 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 11:29:30 models.py:263] [main] Lossless Compression Disabled
Prefetching is disabled
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:29:31 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.215 seconds
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:29:31 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.136 seconds
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:29:31 worker_manager.py:364] Main thread loading delta 41 done
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:29:31 worker_manager.py:364] Main thread loading delta 41 done
[36m(RayWorkerVllm pid=94212)[0m WARNING 05-17 11:29:31 worker_manager.py:344] Missed prefetch, fall back to loading delta 42 now
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:29:31 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:29:31 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:29:31 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.207 seconds
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:29:31 worker_manager.py:364] Main thread loading delta 41 done
[36m(RayWorkerVllm pid=94020)[0m WARNING 05-17 11:29:31 worker_manager.py:344] Missed prefetch, fall back to loading delta 42 now
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:29:31 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:29:31 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=95226)[0m WARNING 05-17 11:29:31 worker_manager.py:344] Missed prefetch, fall back to loading delta 42 now
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:29:31 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:29:31 models.py:263] [main] Lossless Compression Disabled
Prefetching is disabled
INFO 05-17 11:29:32 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.710 seconds
INFO 05-17 11:29:32 worker_manager.py:364] Main thread loading delta 42 done
WARNING 05-17 11:29:32 worker_manager.py:344] Missed prefetch, fall back to loading delta 58 now
INFO 05-17 11:29:32 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 8 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.2%, CPU KV cache usage: 0.0%
INFO 05-17 11:29:32 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 11:29:32 models.py:263] [main] Lossless Compression Disabled
Prefetching is disabled
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:29:33 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.161 seconds
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:29:33 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.210 seconds
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:29:33 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.195 seconds
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:29:33 worker_manager.py:364] Main thread loading delta 42 done
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:29:33 worker_manager.py:364] Main thread loading delta 42 done
[36m(RayWorkerVllm pid=94212)[0m WARNING 05-17 11:29:33 worker_manager.py:344] Missed prefetch, fall back to loading delta 58 now
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:29:33 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:29:33 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:29:33 worker_manager.py:364] Main thread loading delta 42 done
[36m(RayWorkerVllm pid=94020)[0m WARNING 05-17 11:29:34 worker_manager.py:344] Missed prefetch, fall back to loading delta 58 now
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:29:34 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:29:34 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=95226)[0m WARNING 05-17 11:29:34 worker_manager.py:344] Missed prefetch, fall back to loading delta 58 now
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:29:34 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:29:34 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 11:29:34 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.697 seconds
INFO 05-17 11:29:34 worker_manager.py:364] Main thread loading delta 58 done
WARNING 05-17 11:29:34 worker_manager.py:344] Missed prefetch, fall back to loading delta 31 now
INFO 05-17 11:29:34 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 11:29:34 models.py:263] [main] Lossless Compression Disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
INFO 05-17 11:29:36 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.668 seconds
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:29:36 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.153 seconds
INFO 05-17 11:29:36 worker_manager.py:364] Main thread loading delta 31 done
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:29:36 worker_manager.py:364] Main thread loading delta 58 done
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:29:36 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.143 seconds
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:29:36 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.142 seconds
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:29:36 worker_manager.py:364] Main thread loading delta 58 done
[36m(RayWorkerVllm pid=94212)[0m WARNING 05-17 11:29:36 worker_manager.py:344] Missed prefetch, fall back to loading delta 31 now
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:29:36 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:29:36 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:29:36 worker_manager.py:364] Main thread loading delta 58 done
[36m(RayWorkerVllm pid=94020)[0m WARNING 05-17 11:29:36 worker_manager.py:344] Missed prefetch, fall back to loading delta 31 now
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:29:36 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:29:36 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=95226)[0m WARNING 05-17 11:29:36 worker_manager.py:344] Missed prefetch, fall back to loading delta 31 now
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:29:36 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:29:36 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:29:38 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.151 seconds
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:29:38 worker_manager.py:364] Main thread loading delta 31 done
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:29:38 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.116 seconds
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:29:38 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.123 seconds
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:29:38 worker_manager.py:364] Main thread loading delta 31 done
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:29:38 worker_manager.py:364] Main thread loading delta 31 done
Prefetching is disabled
Prefetching is disabled
INFO 05-17 11:29:39 metrics.py:276] Avg prompt throughput: 12.7 tokens/s, Avg generation throughput: 0.7 tokens/s, Running: 8 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.2%, CPU KV cache usage: 0.0%
WARNING 05-17 11:29:39 worker_manager.py:344] Missed prefetch, fall back to loading delta 35 now
INFO 05-17 11:29:39 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 11:29:39 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=94020)[0m WARNING 05-17 11:29:39 worker_manager.py:344] Missed prefetch, fall back to loading delta 35 now
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:29:39 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:29:39 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=94212)[0m WARNING 05-17 11:29:39 worker_manager.py:344] Missed prefetch, fall back to loading delta 35 now
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:29:39 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:29:39 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=95226)[0m WARNING 05-17 11:29:39 worker_manager.py:344] Missed prefetch, fall back to loading delta 35 now
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:29:39 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:29:39 models.py:263] [main] Lossless Compression Disabled
Prefetching is disabled
INFO 05-17 11:29:41 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.704 seconds
INFO 05-17 11:29:41 worker_manager.py:364] Main thread loading delta 35 done
WARNING 05-17 11:29:41 worker_manager.py:344] Missed prefetch, fall back to loading delta 6 now
INFO 05-17 11:29:41 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 11:29:41 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:29:42 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.167 seconds
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:29:42 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.258 seconds
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:29:42 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.188 seconds
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:29:42 worker_manager.py:364] Main thread loading delta 35 done
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:29:42 worker_manager.py:364] Main thread loading delta 35 done
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:29:42 worker_manager.py:364] Main thread loading delta 35 done
[36m(RayWorkerVllm pid=94020)[0m WARNING 05-17 11:29:42 worker_manager.py:344] Missed prefetch, fall back to loading delta 6 now
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:29:42 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:29:42 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=94212)[0m WARNING 05-17 11:29:42 worker_manager.py:344] Missed prefetch, fall back to loading delta 6 now
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:29:42 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:29:42 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=95226)[0m WARNING 05-17 11:29:42 worker_manager.py:344] Missed prefetch, fall back to loading delta 6 now
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:29:42 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:29:42 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 11:29:43 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.719 seconds
INFO 05-17 11:29:43 worker_manager.py:364] Main thread loading delta 6 done
WARNING 05-17 11:29:43 worker_manager.py:344] Missed prefetch, fall back to loading delta 11 now
INFO 05-17 11:29:43 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 11:29:43 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:29:44 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.231 seconds
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:29:44 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.245 seconds
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:29:44 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.247 seconds
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:29:44 worker_manager.py:364] Main thread loading delta 6 done
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:29:44 worker_manager.py:364] Main thread loading delta 6 done
Prefetching is disabled
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:29:44 worker_manager.py:364] Main thread loading delta 6 done
[36m(RayWorkerVllm pid=94020)[0m WARNING 05-17 11:29:44 worker_manager.py:344] Missed prefetch, fall back to loading delta 11 now
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:29:44 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:29:44 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=94212)[0m WARNING 05-17 11:29:44 worker_manager.py:344] Missed prefetch, fall back to loading delta 11 now
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:29:44 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:29:44 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=95226)[0m WARNING 05-17 11:29:44 worker_manager.py:344] Missed prefetch, fall back to loading delta 11 now
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:29:44 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:29:44 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 11:29:45 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.678 seconds
INFO 05-17 11:29:45 worker_manager.py:364] Main thread loading delta 11 done
WARNING 05-17 11:29:45 worker_manager.py:344] Missed prefetch, fall back to loading delta 12 now
INFO 05-17 11:29:45 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 11:29:45 models.py:263] [main] Lossless Compression Disabled
total threads: 23
Prefetching is disabled
Prefetching is disabled
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:29:47 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.211 seconds
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:29:47 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.193 seconds
INFO 05-17 11:29:47 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.579 seconds
INFO 05-17 11:29:47 worker_manager.py:364] Main thread loading delta 12 done
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:29:47 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.241 seconds
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:29:47 worker_manager.py:364] Main thread loading delta 11 done
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:29:47 worker_manager.py:364] Main thread loading delta 11 done
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:29:47 worker_manager.py:364] Main thread loading delta 11 done
[36m(RayWorkerVllm pid=94212)[0m WARNING 05-17 11:29:47 worker_manager.py:344] Missed prefetch, fall back to loading delta 12 now
[36m(RayWorkerVllm pid=95226)[0m WARNING 05-17 11:29:47 worker_manager.py:344] Missed prefetch, fall back to loading delta 12 now
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:29:47 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:29:47 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:29:47 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:29:47 models.py:263] [main] Lossless Compression Disabled
WARNING 05-17 11:29:47 worker_manager.py:344] Missed prefetch, fall back to loading delta 14 now
INFO 05-17 11:29:47 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 11:29:47 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=94020)[0m WARNING 05-17 11:29:47 worker_manager.py:344] Missed prefetch, fall back to loading delta 12 now
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:29:47 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:29:47 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 11:29:48 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.593 seconds
INFO 05-17 11:29:49 worker_manager.py:364] Main thread loading delta 14 done
WARNING 05-17 11:29:49 worker_manager.py:344] Missed prefetch, fall back to loading delta 46 now
INFO 05-17 11:29:49 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 11:29:49 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:29:49 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.129 seconds
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:29:49 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.131 seconds
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:29:49 worker_manager.py:364] Main thread loading delta 12 done
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:29:49 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.149 seconds
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:29:49 worker_manager.py:364] Main thread loading delta 12 done
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:29:49 worker_manager.py:364] Main thread loading delta 12 done
[36m(RayWorkerVllm pid=94212)[0m WARNING 05-17 11:29:49 worker_manager.py:344] Missed prefetch, fall back to loading delta 14 now
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:29:49 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:29:49 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=95226)[0m WARNING 05-17 11:29:49 worker_manager.py:344] Missed prefetch, fall back to loading delta 14 now
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:29:49 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:29:49 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=94020)[0m WARNING 05-17 11:29:49 worker_manager.py:344] Missed prefetch, fall back to loading delta 14 now
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:29:49 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:29:49 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 11:29:50 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.614 seconds
INFO 05-17 11:29:50 worker_manager.py:364] Main thread loading delta 46 done
WARNING 05-17 11:29:50 worker_manager.py:344] Missed prefetch, fall back to loading delta 47 now
INFO 05-17 11:29:50 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 11:29:50 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:29:51 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.139 seconds
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:29:51 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.142 seconds
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:29:51 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.130 seconds
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:29:51 worker_manager.py:364] Main thread loading delta 14 done
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:29:51 worker_manager.py:364] Main thread loading delta 14 done
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:29:51 worker_manager.py:364] Main thread loading delta 14 done
[36m(RayWorkerVllm pid=94020)[0m WARNING 05-17 11:29:52 worker_manager.py:344] Missed prefetch, fall back to loading delta 46 now
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:29:52 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:29:52 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=94212)[0m WARNING 05-17 11:29:52 worker_manager.py:344] Missed prefetch, fall back to loading delta 46 now
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:29:52 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:29:52 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=95226)[0m WARNING 05-17 11:29:52 worker_manager.py:344] Missed prefetch, fall back to loading delta 46 now
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:29:52 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:29:52 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 11:29:52 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 19 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.7%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:29:54 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.118 seconds
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:29:54 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.181 seconds
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:29:54 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.179 seconds
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:29:54 worker_manager.py:364] Main thread loading delta 46 done
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:29:54 worker_manager.py:364] Main thread loading delta 46 done
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:29:54 worker_manager.py:364] Main thread loading delta 46 done
[36m(RayWorkerVllm pid=94020)[0m WARNING 05-17 11:29:54 worker_manager.py:344] Missed prefetch, fall back to loading delta 47 now
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:29:54 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:29:54 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=94212)[0m WARNING 05-17 11:29:54 worker_manager.py:344] Missed prefetch, fall back to loading delta 47 now
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:29:54 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:29:54 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=95226)[0m WARNING 05-17 11:29:54 worker_manager.py:344] Missed prefetch, fall back to loading delta 47 now
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:29:54 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:29:54 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 11:29:59 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 9.003 seconds
INFO 05-17 11:30:00 worker_manager.py:364] Main thread loading delta 47 done
WARNING 05-17 11:30:00 worker_manager.py:344] Missed prefetch, fall back to loading delta 53 now
INFO 05-17 11:30:00 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 11:30:00 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 11:30:02 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 19 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.7%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:30:05 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 11.424 seconds
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:30:06 worker_manager.py:364] Main thread loading delta 47 done
[36m(RayWorkerVllm pid=94212)[0m WARNING 05-17 11:30:06 worker_manager.py:344] Missed prefetch, fall back to loading delta 53 now
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:30:06 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:30:06 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:30:07 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 13.074 seconds
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:30:07 worker_manager.py:364] Main thread loading delta 47 done
[36m(RayWorkerVllm pid=95226)[0m WARNING 05-17 11:30:07 worker_manager.py:344] Missed prefetch, fall back to loading delta 53 now
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:30:07 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:30:07 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:30:11 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 16.815 seconds
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:30:11 worker_manager.py:364] Main thread loading delta 47 done
[36m(RayWorkerVllm pid=94020)[0m WARNING 05-17 11:30:11 worker_manager.py:344] Missed prefetch, fall back to loading delta 53 now
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:30:11 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:30:11 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 11:30:12 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 19 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.7%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:30:16 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 10.780 seconds
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:30:17 worker_manager.py:364] Main thread loading delta 53 done
[36m(RayWorkerVllm pid=94212)[0m WARNING 05-17 11:30:17 worker_manager.py:344] Missed prefetch, fall back to loading delta 57 now
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:30:17 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:30:17 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 11:30:21 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 20.779 seconds
INFO 05-17 11:30:21 worker_manager.py:364] Main thread loading delta 53 done
WARNING 05-17 11:30:21 worker_manager.py:344] Missed prefetch, fall back to loading delta 57 now
INFO 05-17 11:30:21 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 11:30:21 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 11:30:22 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 19 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.7%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:30:23 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 11.546 seconds
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:30:23 worker_manager.py:364] Main thread loading delta 53 done
[36m(RayWorkerVllm pid=94020)[0m WARNING 05-17 11:30:23 worker_manager.py:344] Missed prefetch, fall back to loading delta 57 now
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:30:23 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:30:23 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:30:25 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 17.803 seconds
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:30:25 worker_manager.py:364] Main thread loading delta 53 done
[36m(RayWorkerVllm pid=95226)[0m WARNING 05-17 11:30:25 worker_manager.py:344] Missed prefetch, fall back to loading delta 57 now
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:30:25 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:30:25 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:30:28 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 11.223 seconds
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:30:28 worker_manager.py:364] Main thread loading delta 57 done
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:30:32 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 8.788 seconds
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:30:32 worker_manager.py:364] Main thread loading delta 57 done
INFO 05-17 11:30:32 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 19 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.7%, CPU KV cache usage: 0.0%
INFO 05-17 11:30:35 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 13.855 seconds
INFO 05-17 11:30:35 worker_manager.py:364] Main thread loading delta 57 done
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:30:36 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 11.017 seconds
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:30:36 worker_manager.py:364] Main thread loading delta 57 done
INFO 05-17 11:30:39 metrics.py:276] Avg prompt throughput: 51.1 tokens/s, Avg generation throughput: 1.6 tokens/s, Running: 18 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.6%, CPU KV cache usage: 0.0%
INFO:     ::1:52622 - "POST /v1/completions HTTP/1.1" 200 OK
WARNING 05-17 11:30:39 worker_manager.py:344] Missed prefetch, fall back to loading delta 3 now
INFO 05-17 11:30:39 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 11:30:39 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=94020)[0m WARNING 05-17 11:30:39 worker_manager.py:344] Missed prefetch, fall back to loading delta 3 now
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:30:39 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:30:39 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=94212)[0m WARNING 05-17 11:30:39 worker_manager.py:344] Missed prefetch, fall back to loading delta 3 now
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:30:39 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:30:39 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=95226)[0m WARNING 05-17 11:30:39 worker_manager.py:344] Missed prefetch, fall back to loading delta 3 now
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:30:39 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:30:39 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 11:30:41 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.018 seconds
INFO 05-17 11:30:41 worker_manager.py:364] Main thread loading delta 3 done
WARNING 05-17 11:30:41 worker_manager.py:344] Missed prefetch, fall back to loading delta 52 now
INFO 05-17 11:30:41 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 11:30:41 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:30:41 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.647 seconds
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:30:41 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.633 seconds
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:30:41 worker_manager.py:364] Main thread loading delta 3 done
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:30:41 worker_manager.py:364] Main thread loading delta 3 done
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:30:41 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.678 seconds
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:30:41 worker_manager.py:364] Main thread loading delta 3 done
[36m(RayWorkerVllm pid=94020)[0m WARNING 05-17 11:30:42 worker_manager.py:344] Missed prefetch, fall back to loading delta 52 now
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:30:42 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:30:42 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=94212)[0m WARNING 05-17 11:30:42 worker_manager.py:344] Missed prefetch, fall back to loading delta 52 now
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:30:42 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:30:42 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=95226)[0m WARNING 05-17 11:30:42 worker_manager.py:344] Missed prefetch, fall back to loading delta 52 now
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:30:42 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:30:42 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 11:30:43 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.680 seconds
INFO 05-17 11:30:43 worker_manager.py:364] Main thread loading delta 52 done
WARNING 05-17 11:30:43 worker_manager.py:344] Missed prefetch, fall back to loading delta 15 now
INFO 05-17 11:30:43 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 11:30:43 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:30:44 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.308 seconds
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:30:44 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.296 seconds
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:30:44 worker_manager.py:364] Main thread loading delta 52 done
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:30:44 worker_manager.py:364] Main thread loading delta 52 done
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:30:44 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.428 seconds
[36m(RayWorkerVllm pid=94020)[0m WARNING 05-17 11:30:44 worker_manager.py:344] Missed prefetch, fall back to loading delta 15 now
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:30:44 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:30:44 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=94212)[0m WARNING 05-17 11:30:44 worker_manager.py:344] Missed prefetch, fall back to loading delta 15 now
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:30:44 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:30:44 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:30:44 worker_manager.py:364] Main thread loading delta 52 done
[36m(RayWorkerVllm pid=95226)[0m WARNING 05-17 11:30:44 worker_manager.py:344] Missed prefetch, fall back to loading delta 15 now
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:30:44 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:30:44 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 11:30:45 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.701 seconds
INFO 05-17 11:30:45 worker_manager.py:364] Main thread loading delta 15 done
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:30:46 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.119 seconds
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:30:46 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.087 seconds
[36m(RayWorkerVllm pid=94020)[0m INFO 05-17 11:30:46 worker_manager.py:364] Main thread loading delta 15 done
[36m(RayWorkerVllm pid=94212)[0m INFO 05-17 11:30:46 worker_manager.py:364] Main thread loading delta 15 done
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:30:46 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.099 seconds
[36m(RayWorkerVllm pid=95226)[0m INFO 05-17 11:30:46 worker_manager.py:364] Main thread loading delta 15 done
INFO 05-17 11:30:48 metrics.py:276] Avg prompt throughput: 12.8 tokens/s, Avg generation throughput: 0.4 tokens/s, Running: 22 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.8%, CPU KV cache usage: 0.0%
INFO 05-17 11:30:53 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 8.0 tokens/s, Running: 22 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.8%, CPU KV cache usage: 0.0%
INFO 05-17 11:30:59 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 7.9 tokens/s, Running: 21 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.8%, CPU KV cache usage: 0.0%
INFO:     ::1:52608 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 11:31:04 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 7.9 tokens/s, Running: 21 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.8%, CPU KV cache usage: 0.0%
INFO 05-17 11:31:09 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 7.9 tokens/s, Running: 21 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.8%, CPU KV cache usage: 0.0%
INFO 05-17 11:31:15 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 8.0 tokens/s, Running: 21 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.9%, CPU KV cache usage: 0.0%
INFO:     ::1:52594 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 11:31:20 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 8.0 tokens/s, Running: 20 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.9%, CPU KV cache usage: 0.0%
INFO 05-17 11:31:25 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 8.0 tokens/s, Running: 20 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.0%, CPU KV cache usage: 0.0%
INFO 05-17 11:31:30 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 7.9 tokens/s, Running: 20 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.0%, CPU KV cache usage: 0.0%
INFO 05-17 11:31:35 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 8.0 tokens/s, Running: 20 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.0%, CPU KV cache usage: 0.0%
INFO 05-17 11:31:42 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 5.5 tokens/s, Running: 20 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.1%, CPU KV cache usage: 0.0%
INFO 05-17 11:31:47 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 11.3 tokens/s, Running: 20 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.1%, CPU KV cache usage: 0.0%
INFO 05-17 11:31:55 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 8.0 tokens/s, Running: 20 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.1%, CPU KV cache usage: 0.0%
INFO 05-17 11:32:02 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 5.5 tokens/s, Running: 20 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.3%, CPU KV cache usage: 0.0%
INFO 05-17 11:32:07 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 11.4 tokens/s, Running: 19 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%
INFO:     ::1:52678 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 11:32:14 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 8.0 tokens/s, Running: 18 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%
INFO:     ::1:52620 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 11:32:21 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 8.0 tokens/s, Running: 18 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%
INFO 05-17 11:32:28 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 8.0 tokens/s, Running: 18 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%
INFO 05-17 11:32:35 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 8.1 tokens/s, Running: 17 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.3%, CPU KV cache usage: 0.0%
INFO:     ::1:52590 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:52660 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 11:32:41 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 8.1 tokens/s, Running: 16 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.3%, CPU KV cache usage: 0.0%
INFO 05-17 11:32:47 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 8.1 tokens/s, Running: 16 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.3%, CPU KV cache usage: 0.0%
INFO 05-17 11:32:52 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 6.0 tokens/s, Running: 16 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.4%, CPU KV cache usage: 0.0%
INFO 05-17 11:32:58 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 9.9 tokens/s, Running: 16 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.4%, CPU KV cache usage: 0.0%
INFO 05-17 11:33:04 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 8.2 tokens/s, Running: 16 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.4%, CPU KV cache usage: 0.0%
INFO:     ::1:52576 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 11:33:10 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 8.2 tokens/s, Running: 15 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.5%, CPU KV cache usage: 0.0%
INFO 05-17 11:33:16 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 8.2 tokens/s, Running: 15 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.5%, CPU KV cache usage: 0.0%
INFO:     ::1:52578 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 11:33:21 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 8.2 tokens/s, Running: 14 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.4%, CPU KV cache usage: 0.0%
INFO 05-17 11:33:26 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 8.2 tokens/s, Running: 14 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.4%, CPU KV cache usage: 0.0%
INFO 05-17 11:33:31 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 8.2 tokens/s, Running: 14 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.4%, CPU KV cache usage: 0.0%
INFO 05-17 11:33:36 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 8.2 tokens/s, Running: 14 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.5%, CPU KV cache usage: 0.0%
INFO 05-17 11:33:41 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 8.3 tokens/s, Running: 14 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.6%, CPU KV cache usage: 0.0%
INFO 05-17 11:33:46 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 8.3 tokens/s, Running: 14 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.6%, CPU KV cache usage: 0.0%
INFO:     ::1:52610 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 11:33:52 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 7.8 tokens/s, Running: 13 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.5%, CPU KV cache usage: 0.0%
INFO 05-17 11:33:57 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 7.7 tokens/s, Running: 13 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.5%, CPU KV cache usage: 0.0%
INFO 05-17 11:34:02 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 7.6 tokens/s, Running: 13 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.5%, CPU KV cache usage: 0.0%
INFO 05-17 11:34:07 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 7.6 tokens/s, Running: 13 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.6%, CPU KV cache usage: 0.0%
INFO:     ::1:52642 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 11:34:12 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 7.3 tokens/s, Running: 12 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.6%, CPU KV cache usage: 0.0%
INFO:     ::1:52636 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 11:34:18 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 7.9 tokens/s, Running: 11 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.4%, CPU KV cache usage: 0.0%
INFO:     ::1:52580 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:52618 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 11:34:23 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 7.5 tokens/s, Running: 9 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%
INFO 05-17 11:34:29 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 7.5 tokens/s, Running: 9 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%
INFO:     ::1:52604 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 11:34:35 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 7.5 tokens/s, Running: 8 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%
INFO 05-17 11:34:40 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 7.5 tokens/s, Running: 8 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%
INFO 05-17 11:34:46 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 7.6 tokens/s, Running: 8 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%
INFO 05-17 11:34:51 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 7.5 tokens/s, Running: 8 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.3%, CPU KV cache usage: 0.0%
INFO 05-17 11:34:56 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 7.6 tokens/s, Running: 8 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.3%, CPU KV cache usage: 0.0%
INFO:     ::1:52562 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 11:35:01 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 7.6 tokens/s, Running: 7 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%
INFO 05-17 11:35:07 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 7.6 tokens/s, Running: 7 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%
INFO 05-17 11:35:12 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 6.8 tokens/s, Running: 7 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%
INFO 05-17 11:35:17 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 8.4 tokens/s, Running: 7 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.3%, CPU KV cache usage: 0.0%
INFO 05-17 11:35:23 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 7.5 tokens/s, Running: 7 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.3%, CPU KV cache usage: 0.0%
INFO 05-17 11:35:28 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 7.5 tokens/s, Running: 7 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.4%, CPU KV cache usage: 0.0%
INFO:     ::1:52556 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 11:35:34 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 7.6 tokens/s, Running: 6 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%
INFO 05-17 11:35:39 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 7.5 tokens/s, Running: 5 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.1%, CPU KV cache usage: 0.0%
INFO:     ::1:52672 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 11:35:45 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 7.6 tokens/s, Running: 5 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.1%, CPU KV cache usage: 0.0%
INFO 05-17 11:35:50 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 7.5 tokens/s, Running: 5 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.1%, CPU KV cache usage: 0.0%
INFO 05-17 11:35:55 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 7.6 tokens/s, Running: 5 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%
INFO:     ::1:52570 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 11:36:01 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 7.6 tokens/s, Running: 4 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.0%, CPU KV cache usage: 0.0%
INFO 05-17 11:36:06 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 7.6 tokens/s, Running: 4 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.0%, CPU KV cache usage: 0.0%
INFO 05-17 11:36:11 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 7.7 tokens/s, Running: 4 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.0%, CPU KV cache usage: 0.0%
INFO 05-17 11:36:16 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 7.6 tokens/s, Running: 4 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.1%, CPU KV cache usage: 0.0%
INFO 05-17 11:36:22 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 7.6 tokens/s, Running: 4 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%
INFO:     ::1:52588 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 11:36:27 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 7.7 tokens/s, Running: 3 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.9%, CPU KV cache usage: 0.0%
INFO 05-17 11:36:32 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 7.6 tokens/s, Running: 3 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.9%, CPU KV cache usage: 0.0%
INFO 05-17 11:36:37 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 7.6 tokens/s, Running: 3 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.0%, CPU KV cache usage: 0.0%
INFO:     ::1:52634 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 11:36:42 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 7.8 tokens/s, Running: 2 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.7%, CPU KV cache usage: 0.0%
INFO:     ::1:52572 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 11:36:47 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.5 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.4%, CPU KV cache usage: 0.0%
INFO 05-17 11:36:52 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 3.9 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.4%, CPU KV cache usage: 0.0%
INFO 05-17 11:36:57 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 3.9 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.4%, CPU KV cache usage: 0.0%
INFO 05-17 11:37:02 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 3.9 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.5%, CPU KV cache usage: 0.0%
INFO 05-17 11:37:08 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 3.9 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.5%, CPU KV cache usage: 0.0%
INFO 05-17 11:37:13 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 3.9 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.5%, CPU KV cache usage: 0.0%
INFO 05-17 11:37:18 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 3.9 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.5%, CPU KV cache usage: 0.0%
INFO 05-17 11:37:23 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 3.9 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.5%, CPU KV cache usage: 0.0%
INFO 05-17 11:37:28 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 3.9 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.5%, CPU KV cache usage: 0.0%
INFO:     ::1:52624 - "POST /v1/completions HTTP/1.1" 200 OK
Results written to .artifact/benchmarks/results/67fc4a3d-438e-4e0b-a7fb-17425eec88c9.jsonl
Killing process 86217...
/var/spool/slurmd/job3676352/slurm_script: line 45: 86182 Killed                  apptainer run --nv --home /mnt/petrelfs/huqinghao/xzyao/:/home/xiayao --bind /mnt/petrelfs/huqinghao/xzyao/code/vllm:/vllm --bind /mnt/petrelfs/huqinghao/xzyao/code/triteia:/triteia --env PYTHONPATH=/vllm:/triteia --env CUDA_LAUNCH_BLOCKING=1 --env TVM_TARGET=nvidia/nvidia-a100 --env TRANSFORMERS_OFFLINE=1 --env NUMEXPR_MAX_THREADS=128 --env USE_BITBLAS=1 --env BITBLAS_TARGET=nvidia/nvidia-a100 --env RAY_DEDUP_LOGS=0 --workdir /vllm /mnt/petrelfs/huqinghao/xzyao/images/vllm-0.4.1.sif python3 /vllm/vllm/entrypoints/openai/api_server.py --model /vllm/.idea/full_models/Llama-2-13b-hf --enable-delta --disable-log-requests --gpu-memory-utilization 0.85 --delta-modules delta-1=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-1 delta-2=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-2 delta-3=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-3 delta-4=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-4 delta-5=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-5 delta-6=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-6 delta-7=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-7 delta-8=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-8 delta-9=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-9 delta-10=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-10 delta-11=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-11 delta-12=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-12 delta-13=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-13 delta-14=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-14 delta-15=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-15 delta-16=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-16 delta-17=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-17 delta-18=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-18 delta-19=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-19 delta-20=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-20 delta-21=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-21 delta-22=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-22 delta-23=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-23 delta-24=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-24 delta-25=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-25 delta-26=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-26 delta-27=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-27 delta-28=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-28 delta-29=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-29 delta-30=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-30 delta-31=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-31 delta-32=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-32 delta-33=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-33 delta-34=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-34 delta-35=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-35 delta-36=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-36 delta-37=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-37 delta-38=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-38 delta-39=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-39 delta-40=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-40 delta-41=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-41 delta-42=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-42 delta-43=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-43 delta-44=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-44 delta-45=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-45 delta-46=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-46 delta-47=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-47 delta-48=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-48 delta-49=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-49 delta-50=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-50 delta-51=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-51 delta-52=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-52 delta-53=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-53 delta-54=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-54 delta-55=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-55 delta-56=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-56 delta-57=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-57 delta-58=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-58 delta-59=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-59 delta-60=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-60 delta-61=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-61 delta-62=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-62 delta-63=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-63 delta-64=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-64 --max-deltas 24 --tensor-parallel-size 4 --enforce-eager
