/mnt/hwfile/huqinghao/miniconda3/bin/python
2024-05-17 03:21:59,570 - INFO - Note: detected 128 virtual cores but NumExpr set to maximum of 64, check "NUMEXPR_MAX_THREADS" environment variable.
2024-05-17 03:21:59,570 - INFO - Note: NumExpr detected 128 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
2024-05-17 03:21:59,570 - INFO - NumExpr defaulting to 8 threads.
2024-05-17 03:22:00,439	INFO scripts.py:1182 -- Did not find any active Ray processes.

==========
== CUDA ==
==========

CUDA Version 12.1.0

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d20070>: Failed to establish a new connection: [Errno 111] Connection refused'))

*************************
** DEPRECATION NOTICE! **
*************************
THIS IMAGE IS DEPRECATED and is scheduled for DELETION.
    https://gitlab.com/nvidia/container-images/cuda/blob/master/doc/support-policy.md

Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d21450>: Failed to establish a new connection: [Errno 111] Connection refused'))
INFO 05-17 03:22:14 api_server.py:191] vLLM API server version 0.3.3
INFO 05-17 03:22:14 api_server.py:192] args: Namespace(host=None, port=8000, uvicorn_log_level='info', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_key=None, served_model_name=None, lora_modules=[], delta_modules=[Delta(name='delta-1', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-1'), Delta(name='delta-2', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-2'), Delta(name='delta-3', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-3'), Delta(name='delta-4', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-4'), Delta(name='delta-5', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-5'), Delta(name='delta-6', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-6'), Delta(name='delta-7', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-7'), Delta(name='delta-8', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-8'), Delta(name='delta-9', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-9'), Delta(name='delta-10', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-10'), Delta(name='delta-11', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-11'), Delta(name='delta-12', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-12'), Delta(name='delta-13', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-13'), Delta(name='delta-14', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-14'), Delta(name='delta-15', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-15'), Delta(name='delta-16', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-16'), Delta(name='delta-17', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-17'), Delta(name='delta-18', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-18'), Delta(name='delta-19', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-19'), Delta(name='delta-20', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-20'), Delta(name='delta-21', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-21'), Delta(name='delta-22', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-22'), Delta(name='delta-23', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-23'), Delta(name='delta-24', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-24'), Delta(name='delta-25', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-25'), Delta(name='delta-26', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-26'), Delta(name='delta-27', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-27'), Delta(name='delta-28', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-28'), Delta(name='delta-29', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-29'), Delta(name='delta-30', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-30'), Delta(name='delta-31', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-31'), Delta(name='delta-32', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-32'), Delta(name='delta-33', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-33'), Delta(name='delta-34', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-34'), Delta(name='delta-35', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-35'), Delta(name='delta-36', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-36'), Delta(name='delta-37', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-37'), Delta(name='delta-38', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-38'), Delta(name='delta-39', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-39'), Delta(name='delta-40', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-40'), Delta(name='delta-41', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-41'), Delta(name='delta-42', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-42'), Delta(name='delta-43', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-43'), Delta(name='delta-44', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-44'), Delta(name='delta-45', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-45'), Delta(name='delta-46', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-46'), Delta(name='delta-47', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-47'), Delta(name='delta-48', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-48'), Delta(name='delta-49', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-49'), Delta(name='delta-50', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-50'), Delta(name='delta-51', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-51'), Delta(name='delta-52', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-52'), Delta(name='delta-53', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-53'), Delta(name='delta-54', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-54'), Delta(name='delta-55', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-55'), Delta(name='delta-56', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-56'), Delta(name='delta-57', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-57'), Delta(name='delta-58', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-58'), Delta(name='delta-59', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-59'), Delta(name='delta-60', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-60'), Delta(name='delta-61', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-61'), Delta(name='delta-62', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-62'), Delta(name='delta-63', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-63'), Delta(name='delta-64', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-64')], swap_modules=[], chat_template=None, response_role='assistant', ssl_keyfile=None, ssl_certfile=None, ssl_ca_certs=None, ssl_cert_reqs=0, root_path=None, middleware=[], model='/vllm/.idea/full_models/Llama-2-13b-hf', tokenizer=None, revision=None, code_revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=False, download_dir=None, load_format='auto', dtype='auto', kv_cache_dtype='auto', max_model_len=None, worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=4, max_parallel_loading_workers=None, ray_workers_use_nsight=False, block_size=16, enable_prefix_caching=False, seed=0, swap_space=4, gpu_memory_utilization=0.85, max_num_batched_tokens=None, max_num_seqs=256, max_logprobs=5, disable_log_stats=False, quantization=None, enforce_eager=True, max_context_len_to_capture=8192, disable_custom_all_reduce=False, tokenizer_pool_size=0, tokenizer_pool_type='ray', tokenizer_pool_extra_config=None, enable_lora=False, max_loras=1, max_lora_rank=64, lora_extra_vocab_size=256, lora_dtype='auto', max_cpu_loras=32, enable_delta=True, max_deltas=24, max_cpu_deltas=32, max_delta_bitwidth=4, device='auto', image_input_type=None, image_token_id=None, image_input_shape=None, image_feature_size=None, scheduler_delay_factor=0.0, enable_prefetch=True, scheduler_policy='fcfs', max_swap_slots=1, max_cpu_models=4, enable_swap=False, engine_use_ray=False, disable_log_requests=True, max_log_len=None)
2024-05-17 03:22:17,970	INFO worker.py:1749 -- Started a local Ray instance.
INFO 05-17 03:22:20 llm_engine.py:90] Initializing an LLM engine (v0.3.3) with config: model='/vllm/.idea/full_models/Llama-2-13b-hf', tokenizer='/vllm/.idea/full_models/Llama-2-13b-hf', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, lora_config=None, delta_config=DeltaConfig(max_deltas=24, max_bitwidth=4, delta_dtype=torch.int8, max_cpu_deltas=32, delta_extra_vocab_size=0, pack_factor=Fraction(2, 1), kernel=<QuantKernel.TRITON: 'triton'>), swap_config=None, max_seq_len=4096, download_dir=None, load_format=auto, tensor_parallel_size=4, disable_custom_all_reduce=False, quantization=None, enforce_eager=True, kv_cache_dtype=auto, device_config=cuda, seed=0)
INFO 05-17 03:22:20 llm_engine.py:243] ignored verifying delta_config
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d21d20>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d21cf0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d21420>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d201f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d225f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d22ec0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d22e30>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d22560>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d20430>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d215d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d22080>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d23790>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d219c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d210f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d20790>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d22920>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d22a10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d229b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d22980>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d20550>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d20fd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d210c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d23460>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d21330>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d20640>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d226b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d22f80>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d230a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d23340>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d22aa0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d221d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d20ee0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d208e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d23610>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d21ba0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d212d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d202b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d23b20>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d23ca0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d23940>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d20520>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d21000>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d218d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d21450>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb5908e40a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d223b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d22a40>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d23c40>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d239d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590cfbd90>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d21960>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d22bc0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d232b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d227a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d20ee0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d234c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d22b60>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d22da0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Using bitblas
WARNING 05-17 03:31:56 models.py:48] Using bitblas delta modules
INFO 05-17 03:31:56 selector.py:16] Using FlashAttention backend.
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d23a90>: Failed to establish a new connection: [Errno 111] Connection refused'))
[36m(RayWorkerVllm pid=1231)[0m Exception ignored in: <function TempDirectory.__del__ at 0x7ef41d9ed870>
[36m(RayWorkerVllm pid=1231)[0m Traceback (most recent call last):
[36m(RayWorkerVllm pid=1231)[0m   File "/usr/local/lib/python3.10/dist-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 145, in __del__
[36m(RayWorkerVllm pid=1231)[0m     self.remove()
[36m(RayWorkerVllm pid=1231)[0m   File "/usr/local/lib/python3.10/dist-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 121, in remove
[36m(RayWorkerVllm pid=1231)[0m     if self.temp_dir:
[36m(RayWorkerVllm pid=1231)[0m AttributeError: 'TempDirectory' object has no attribute 'temp_dir'
[36m(RayWorkerVllm pid=1690)[0m Exception ignored in: <function TempDirectory.__del__ at 0x7f8005149870>
[36m(RayWorkerVllm pid=1690)[0m Traceback (most recent call last):
[36m(RayWorkerVllm pid=1690)[0m   File "/usr/local/lib/python3.10/dist-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 145, in __del__
[36m(RayWorkerVllm pid=1690)[0m     self.remove()
[36m(RayWorkerVllm pid=1690)[0m   File "/usr/local/lib/python3.10/dist-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 121, in remove
[36m(RayWorkerVllm pid=1690)[0m     if self.temp_dir:
[36m(RayWorkerVllm pid=1690)[0m AttributeError: 'TempDirectory' object has no attribute 'temp_dir'
[36m(RayWorkerVllm pid=1231)[0m Exception ignored in: <function TempDirectory.__del__ at 0x7ef41d9ed870>
[36m(RayWorkerVllm pid=1231)[0m Traceback (most recent call last):
[36m(RayWorkerVllm pid=1231)[0m   File "/usr/local/lib/python3.10/dist-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 145, in __del__
[36m(RayWorkerVllm pid=1231)[0m     self.remove()
[36m(RayWorkerVllm pid=1231)[0m   File "/usr/local/lib/python3.10/dist-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 121, in remove
[36m(RayWorkerVllm pid=1231)[0m     if self.temp_dir:
[36m(RayWorkerVllm pid=1231)[0m AttributeError: 'TempDirectory' object has no attribute 'temp_dir'
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d23340>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb5908e4520>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d21bd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d23c10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d23a00>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d22890>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d206d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb5908e49a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d20880>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d22f80>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d230a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d23d00>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb5908e4340>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d21810>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d21660>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d22a10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d22b00>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d205b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb5908e4460>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d226e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d23070>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d23d90>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d23940>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb5908e4be0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d23fa0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d23c10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d23a00>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d22890>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d218d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb5908e52a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d20370>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d22c20>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d23970>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d23af0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb5908e4820>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d23fd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d23940>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d23d90>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d23070>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d23100>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d20df0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d206a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d22320>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d228f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d234f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d21690>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d22020>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d22050>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d236d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d22d40>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d22a70>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb5908e5720>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d22320>: Failed to establish a new connection: [Errno 111] Connection refused'))
[36m(RayWorkerVllm pid=1231)[0m Using bitblas
[36m(RayWorkerVllm pid=1452)[0m Using bitblas
[36m(RayWorkerVllm pid=1690)[0m Using bitblas
[36m(RayWorkerVllm pid=1231)[0m BitBLAS Operator not loaded, retrying in 5 seconds...
[36m(RayWorkerVllm pid=1231)[0m Error: [Errno 17] File exists: '/home/xiayao/.cache/bitblas/nvidia/nvidia-a100/c96df0f34eb23be516ef0126651d4e78b151337f28ebc87cc5492d79d135855f/tvm_rt_mod'
[36m(RayWorkerVllm pid=1690)[0m BitBLAS Operator not loaded, retrying in 5 seconds...
[36m(RayWorkerVllm pid=1690)[0m Error: [Errno 17] File exists: '/home/xiayao/.cache/bitblas/nvidia/nvidia-a100/c96df0f34eb23be516ef0126651d4e78b151337f28ebc87cc5492d79d135855f/tvm_rt_mod'
[36m(RayWorkerVllm pid=1231)[0m BitBLAS Operator not loaded, retrying in 5 seconds...
[36m(RayWorkerVllm pid=1231)[0m Error: [Errno 17] File exists: '/home/xiayao/.cache/bitblas/nvidia/nvidia-a100/c96df0f34eb23be516ef0126651d4e78b151337f28ebc87cc5492d79d135855f/tvm_rt_mod'
[36m(RayWorkerVllm pid=1452)[0m WARNING 05-17 03:40:38 models.py:48] Using bitblas delta modules
[36m(RayWorkerVllm pid=1452)[0m INFO 05-17 03:40:39 selector.py:16] Using FlashAttention backend.
[36m(RayWorkerVllm pid=1690)[0m WARNING 05-17 03:40:40 models.py:48] Using bitblas delta modules
[36m(RayWorkerVllm pid=1690)[0m INFO 05-17 03:40:40 selector.py:16] Using FlashAttention backend.
[36m(RayWorkerVllm pid=1231)[0m WARNING 05-17 03:40:45 models.py:48] Using bitblas delta modules
[36m(RayWorkerVllm pid=1231)[0m INFO 05-17 03:40:45 selector.py:16] Using FlashAttention backend.
INFO 05-17 03:40:59 model_runner.py:161] Loading model weights took 6.1114 GB
INFO 05-17 03:40:59 worker_manager.py:297] Starting prefetching thread
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d228f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[36m(RayWorkerVllm pid=1690)[0m INFO 05-17 03:41:00 model_runner.py:161] Loading model weights took 6.1114 GB
[36m(RayWorkerVllm pid=1690)[0m INFO 05-17 03:41:00 worker_manager.py:297] Starting prefetching thread
[36m(RayWorkerVllm pid=1231)[0m INFO 05-17 03:41:00 model_runner.py:161] Loading model weights took 6.1114 GB
[36m(RayWorkerVllm pid=1231)[0m INFO 05-17 03:41:00 worker_manager.py:297] Starting prefetching thread
[36m(RayWorkerVllm pid=1452)[0m INFO 05-17 03:41:00 model_runner.py:161] Loading model weights took 6.1114 GB
[36m(RayWorkerVllm pid=1452)[0m INFO 05-17 03:41:00 worker_manager.py:297] Starting prefetching thread
WARNING 05-17 03:41:02 quant_linear_triton.py:557] We should warm up the kernel here 
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb590d234f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[36m(RayWorkerVllm pid=1231)[0m WARNING 05-17 03:41:03 quant_linear_triton.py:557] We should warm up the kernel here 
[36m(RayWorkerVllm pid=1452)[0m WARNING 05-17 03:41:03 quant_linear_triton.py:557] We should warm up the kernel here 
[36m(RayWorkerVllm pid=1690)[0m WARNING 05-17 03:41:03 quant_linear_triton.py:557] We should warm up the kernel here 
INFO 05-17 03:41:17 ray_gpu_executor.py:275] # GPU blocks: 6431, # CPU blocks: 1310
INFO 05-17 03:41:20 scheduler.py:136] Using fcfs policy.
INFO 05-17 03:41:20 block_manager.py:264] disable automatic prefix caching
WARNING 05-17 03:41:20 serving_chat.py:373] No chat template provided. Chat API will not work.
INFO:     Started server process [123993]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     ::1:36670 - "GET /sysinfo HTTP/1.1" 200 OK
Translating from base-model to /vllm/.idea/full_models/Llama-2-13b-hf
Warming up starts
{'id': 20, 'prompt': 'USER: What can we do in AI research to address climate change?\nASSISTANT:', 'timestamp': 0, 'model': 'delta-6', 'min_tokens': 46, 'max_tokens': 46}
INFO 05-17 03:41:22 worker_manager.py:332] Adding delta 6 to prefetching queue: [6]
WARNING 05-17 03:41:22 worker_manager.py:344] Missed prefetch, fall back to loading delta 6 now
[36m(RayWorkerVllm pid=1231)[0m INFO 05-17 03:41:22 worker_manager.py:332] Adding delta 6 to prefetching queue: [6]
[36m(RayWorkerVllm pid=1231)[0m WARNING 05-17 03:41:22 worker_manager.py:344] Missed prefetch, fall back to loading delta 6 now
[36m(RayWorkerVllm pid=1452)[0m INFO 05-17 03:41:22 worker_manager.py:332] Adding delta 6 to prefetching queue: [6]
[36m(RayWorkerVllm pid=1452)[0m WARNING 05-17 03:41:22 worker_manager.py:344] Missed prefetch, fall back to loading delta 6 now
[36m(RayWorkerVllm pid=1690)[0m INFO 05-17 03:41:22 worker_manager.py:332] Adding delta 6 to prefetching queue: [6]
[36m(RayWorkerVllm pid=1690)[0m WARNING 05-17 03:41:22 worker_manager.py:344] Missed prefetch, fall back to loading delta 6 now
INFO 05-17 03:41:22 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 03:41:22 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=1231)[0m INFO 05-17 03:41:22 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=1231)[0m INFO 05-17 03:41:22 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=1452)[0m INFO 05-17 03:41:22 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=1452)[0m INFO 05-17 03:41:22 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=1690)[0m INFO 05-17 03:41:22 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=1690)[0m INFO 05-17 03:41:22 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 03:41:30 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=1690)[0m INFO 05-17 03:41:35 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 13.551 seconds
[36m(RayWorkerVllm pid=1690)[0m INFO 05-17 03:41:35 worker_manager.py:364] Main thread loading delta 6 done
[36m(RayWorkerVllm pid=1690)[0m INFO 05-17 03:41:35 worker_manager.py:379] [1715888495.6909747] activating delta
[36m(RayWorkerVllm pid=1690)[0m INFO 05-17 03:41:35 worker_manager.py:384] [1715888495.8315578] CPU -> GPU time: 0.1405
[36m(RayWorkerVllm pid=1452)[0m INFO 05-17 03:41:37 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 15.364 seconds
[36m(RayWorkerVllm pid=1452)[0m INFO 05-17 03:41:37 worker_manager.py:364] Main thread loading delta 6 done
[36m(RayWorkerVllm pid=1452)[0m INFO 05-17 03:41:37 worker_manager.py:379] [1715888497.4987116] activating delta
[36m(RayWorkerVllm pid=1452)[0m INFO 05-17 03:41:37 worker_manager.py:384] [1715888497.643391] CPU -> GPU time: 0.1446
INFO 05-17 03:41:38 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 16.229 seconds
INFO 05-17 03:41:38 worker_manager.py:364] Main thread loading delta 6 done
INFO 05-17 03:41:38 worker_manager.py:379] [1715888498.3604717] activating delta
INFO 05-17 03:41:38 worker_manager.py:384] [1715888498.4630897] CPU -> GPU time: 0.1025
[36m(RayWorkerVllm pid=1231)[0m INFO 05-17 03:41:39 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 17.511 seconds
[36m(RayWorkerVllm pid=1231)[0m INFO 05-17 03:41:39 worker_manager.py:364] Main thread loading delta 6 done
[36m(RayWorkerVllm pid=1231)[0m INFO 05-17 03:41:39 worker_manager.py:379] [1715888499.6447322] activating delta
[36m(RayWorkerVllm pid=1231)[0m INFO 05-17 03:41:39 worker_manager.py:384] [1715888499.781319] CPU -> GPU time: 0.1365
INFO 05-17 03:41:40 metrics.py:276] Avg prompt throughput: 2.3 tokens/s, Avg generation throughput: 0.1 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
INFO 05-17 03:41:45 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
INFO 05-17 03:41:50 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%
INFO:     ::1:36672 - "POST /v1/completions HTTP/1.1" 200 OK
Warming up ends
Issuing queries
sending 1 queries at 0.8
sending 1 queries at 2.1
sending 1 queries at 3.0
sending 1 queries at 3.8000000000000003
sending 1 queries at 4.4
sending 1 queries at 5.4
sending 1 queries at 6.0
sending 1 queries at 8.200000000000001
sending 1 queries at 11.5
sending 1 queries at 12.0
sending 1 queries at 13.600000000000001
sending 1 queries at 14.3
sending 1 queries at 15.200000000000001
sending 2 queries at 17.8
sending 2 queries at 17.900000000000002
sending 1 queries at 19.700000000000003
sending 1 queries at 21.200000000000003
sending 1 queries at 23.3
sending 1 queries at 27.1
sending 1 queries at 28.700000000000003
sending 1 queries at 29.3
INFO 05-17 03:41:52 worker_manager.py:332] Adding delta 5 to prefetching queue: [5]
WARNING 05-17 03:41:52 worker_manager.py:344] Missed prefetch, fall back to loading delta 5 now
[36m(RayWorkerVllm pid=1231)[0m INFO 05-17 03:41:52 worker_manager.py:332] Adding delta 5 to prefetching queue: [5]
[36m(RayWorkerVllm pid=1452)[0m INFO 05-17 03:41:52 worker_manager.py:332] Adding delta 5 to prefetching queue: [5]
[36m(RayWorkerVllm pid=1690)[0m INFO 05-17 03:41:52 worker_manager.py:332] Adding delta 5 to prefetching queue: [5]
[36m(RayWorkerVllm pid=1690)[0m WARNING 05-17 03:41:52 worker_manager.py:344] Missed prefetch, fall back to loading delta 5 now
[36m(RayWorkerVllm pid=1231)[0m WARNING 05-17 03:41:52 worker_manager.py:344] Missed prefetch, fall back to loading delta 5 now
[36m(RayWorkerVllm pid=1452)[0m WARNING 05-17 03:41:52 worker_manager.py:344] Missed prefetch, fall back to loading delta 5 now
INFO 05-17 03:41:52 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 03:41:52 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=1231)[0m INFO 05-17 03:41:52 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=1231)[0m INFO 05-17 03:41:52 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=1452)[0m INFO 05-17 03:41:52 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=1452)[0m INFO 05-17 03:41:52 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=1690)[0m INFO 05-17 03:41:52 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=1690)[0m INFO 05-17 03:41:52 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 03:41:53 worker_manager.py:332] Adding delta 5 to prefetching queue: [5]
[36m(RayWorkerVllm pid=1452)[0m INFO 05-17 03:42:04 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 12.105 seconds
[36m(RayWorkerVllm pid=1452)[0m INFO 05-17 03:42:04 worker_manager.py:364] Main thread loading delta 5 done
[36m(RayWorkerVllm pid=1231)[0m INFO 05-17 03:42:07 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 14.876 seconds
[36m(RayWorkerVllm pid=1231)[0m INFO 05-17 03:42:07 worker_manager.py:364] Main thread loading delta 5 done
[36m(RayWorkerVllm pid=1690)[0m INFO 05-17 03:42:07 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 15.633 seconds
[36m(RayWorkerVllm pid=1690)[0m INFO 05-17 03:42:07 worker_manager.py:364] Main thread loading delta 5 done
INFO 05-17 03:42:09 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 17.128 seconds
INFO 05-17 03:42:09 worker_manager.py:364] Main thread loading delta 5 done
INFO 05-17 03:42:09 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 03:42:09 models.py:263] [prefetching] Lossless Compression Disabled
INFO 05-17 03:42:11 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.2 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
INFO 05-17 03:42:11 worker_manager.py:332] Adding delta 36 to prefetching queue: [5, 36]
INFO 05-17 03:42:11 worker_manager.py:332] Adding delta 7 to prefetching queue: [5, 36, 7]
INFO 05-17 03:42:11 worker_manager.py:332] Adding delta 1 to prefetching queue: [5, 36, 7, 1]
INFO 05-17 03:42:11 worker_manager.py:332] Adding delta 2 to prefetching queue: [5, 36, 7, 1, 2]
[36m(RayWorkerVllm pid=1231)[0m INFO 05-17 03:42:11 worker_manager.py:332] Adding delta 36 to prefetching queue: [36]
[36m(RayWorkerVllm pid=1231)[0m INFO 05-17 03:42:11 worker_manager.py:332] Adding delta 7 to prefetching queue: [36, 7]
[36m(RayWorkerVllm pid=1231)[0m INFO 05-17 03:42:11 worker_manager.py:332] Adding delta 1 to prefetching queue: [36, 7, 1]
[36m(RayWorkerVllm pid=1231)[0m INFO 05-17 03:42:11 worker_manager.py:332] Adding delta 2 to prefetching queue: [36, 7, 1, 2]
[36m(RayWorkerVllm pid=1452)[0m INFO 05-17 03:42:11 worker_manager.py:332] Adding delta 36 to prefetching queue: [36]
[36m(RayWorkerVllm pid=1452)[0m INFO 05-17 03:42:11 worker_manager.py:332] Adding delta 7 to prefetching queue: [36, 7]
[36m(RayWorkerVllm pid=1452)[0m INFO 05-17 03:42:11 worker_manager.py:332] Adding delta 1 to prefetching queue: [36, 7, 1]
[36m(RayWorkerVllm pid=1452)[0m INFO 05-17 03:42:11 worker_manager.py:332] Adding delta 2 to prefetching queue: [36, 7, 1, 2]
[36m(RayWorkerVllm pid=1690)[0m INFO 05-17 03:42:11 worker_manager.py:332] Adding delta 36 to prefetching queue: [36]
[36m(RayWorkerVllm pid=1690)[0m INFO 05-17 03:42:11 worker_manager.py:332] Adding delta 7 to prefetching queue: [36, 7]
[36m(RayWorkerVllm pid=1690)[0m INFO 05-17 03:42:11 worker_manager.py:332] Adding delta 1 to prefetching queue: [36, 7, 1]
[36m(RayWorkerVllm pid=1690)[0m INFO 05-17 03:42:11 worker_manager.py:332] Adding delta 2 to prefetching queue: [36, 7, 1, 2]
WARNING 05-17 03:42:11 worker_manager.py:344] Missed prefetch, fall back to loading delta 1 now
INFO 05-17 03:42:11 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.634 seconds
INFO 05-17 03:42:11 worker_manager.py:278] Prefetching delta 5 done
[36m(RayWorkerVllm pid=1231)[0m WARNING 05-17 03:42:11 worker_manager.py:344] Missed prefetch, fall back to loading delta 1 now
[36m(RayWorkerVllm pid=1231)[0m INFO 05-17 03:42:11 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=1231)[0m INFO 05-17 03:42:11 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=1452)[0m WARNING 05-17 03:42:11 worker_manager.py:344] Missed prefetch, fall back to loading delta 1 now
[36m(RayWorkerVllm pid=1452)[0m INFO 05-17 03:42:11 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=1452)[0m INFO 05-17 03:42:11 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=1690)[0m WARNING 05-17 03:42:11 worker_manager.py:344] Missed prefetch, fall back to loading delta 1 now
[36m(RayWorkerVllm pid=1690)[0m INFO 05-17 03:42:11 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=1690)[0m INFO 05-17 03:42:11 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 03:42:11 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 03:42:11 models.py:263] [main] Lossless Compression Disabled
total threads: 23
[36m(RayWorkerVllm pid=1231)[0m INFO 05-17 03:42:23 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 12.512 seconds
[36m(RayWorkerVllm pid=1231)[0m INFO 05-17 03:42:23 worker_manager.py:364] Main thread loading delta 1 done
[36m(RayWorkerVllm pid=1231)[0m INFO 05-17 03:42:23 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=1231)[0m INFO 05-17 03:42:23 models.py:263] [prefetching] Lossless Compression Disabled
[36m(RayWorkerVllm pid=1452)[0m INFO 05-17 03:42:24 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 13.716 seconds
[36m(RayWorkerVllm pid=1452)[0m INFO 05-17 03:42:24 worker_manager.py:364] Main thread loading delta 1 done
[36m(RayWorkerVllm pid=1452)[0m INFO 05-17 03:42:24 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=1452)[0m INFO 05-17 03:42:24 models.py:263] [prefetching] Lossless Compression Disabled
[36m(RayWorkerVllm pid=1231)[0m WARNING 05-17 03:42:25 worker_manager.py:344] Missed prefetch, fall back to loading delta 2 now
[36m(RayWorkerVllm pid=1231)[0m INFO 05-17 03:42:25 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=1231)[0m INFO 05-17 03:42:25 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=1452)[0m WARNING 05-17 03:42:27 worker_manager.py:344] Missed prefetch, fall back to loading delta 2 now
[36m(RayWorkerVllm pid=1452)[0m INFO 05-17 03:42:27 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=1452)[0m INFO 05-17 03:42:27 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=1690)[0m INFO 05-17 03:42:30 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 19.785 seconds
[36m(RayWorkerVllm pid=1690)[0m INFO 05-17 03:42:31 worker_manager.py:364] Main thread loading delta 1 done
[36m(RayWorkerVllm pid=1690)[0m INFO 05-17 03:42:31 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=1690)[0m INFO 05-17 03:42:31 models.py:263] [prefetching] Lossless Compression Disabled
INFO 05-17 03:42:31 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 20.433 seconds
INFO 05-17 03:42:31 worker_manager.py:364] Main thread loading delta 1 done
INFO 05-17 03:42:31 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 03:42:31 models.py:263] [prefetching] Lossless Compression Disabled
[36m(RayWorkerVllm pid=1690)[0m WARNING 05-17 03:42:36 worker_manager.py:344] Missed prefetch, fall back to loading delta 2 now
[36m(RayWorkerVllm pid=1690)[0m INFO 05-17 03:42:36 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=1690)[0m INFO 05-17 03:42:36 models.py:263] [main] Lossless Compression Disabled
WARNING 05-17 03:42:38 worker_manager.py:344] Missed prefetch, fall back to loading delta 2 now
INFO 05-17 03:42:38 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 03:42:38 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=1690)[0m INFO 05-17 03:43:02 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 25.133 seconds
[36m(RayWorkerVllm pid=1690)[0m INFO 05-17 03:43:02 worker_manager.py:364] Main thread loading delta 2 done
[36m(RayWorkerVllm pid=1690)[0m WARNING 05-17 03:43:02 worker_manager.py:344] Missed prefetch, fall back to loading delta 36 now
[36m(RayWorkerVllm pid=1690)[0m WARNING 05-17 03:43:02 worker_manager.py:353] Discarding prefetching delta 36
[36m(RayWorkerVllm pid=1690)[0m INFO 05-17 03:43:02 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=1690)[0m INFO 05-17 03:43:02 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 03:43:02 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 30.576 seconds
INFO 05-17 03:43:02 worker_manager.py:278] Prefetching delta 36 done
INFO 05-17 03:43:02 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 24.560 seconds
INFO 05-17 03:43:03 worker_manager.py:364] Main thread loading delta 2 done
INFO 05-17 03:43:03 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 03:43:03 models.py:263] [prefetching] Lossless Compression Disabled
[36m(RayWorkerVllm pid=1452)[0m INFO 05-17 03:43:04 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 37.066 seconds
[36m(RayWorkerVllm pid=1452)[0m INFO 05-17 03:43:04 worker_manager.py:364] Main thread loading delta 2 done
WARNING 05-17 03:43:04 worker_manager.py:344] Missed prefetch, fall back to loading delta 7 now
WARNING 05-17 03:43:04 worker_manager.py:353] Discarding prefetching delta 7
INFO 05-17 03:43:04 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 03:43:04 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=1452)[0m WARNING 05-17 03:43:04 worker_manager.py:344] Missed prefetch, fall back to loading delta 36 now
[36m(RayWorkerVllm pid=1452)[0m WARNING 05-17 03:43:04 worker_manager.py:353] Discarding prefetching delta 36
[36m(RayWorkerVllm pid=1452)[0m INFO 05-17 03:43:04 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=1452)[0m INFO 05-17 03:43:04 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=1231)[0m INFO 05-17 03:43:05 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 40.245 seconds
[36m(RayWorkerVllm pid=1231)[0m INFO 05-17 03:43:06 worker_manager.py:364] Main thread loading delta 2 done
[36m(RayWorkerVllm pid=1231)[0m WARNING 05-17 03:43:06 worker_manager.py:344] Missed prefetch, fall back to loading delta 36 now
[36m(RayWorkerVllm pid=1231)[0m WARNING 05-17 03:43:06 worker_manager.py:353] Discarding prefetching delta 36
[36m(RayWorkerVllm pid=1231)[0m INFO 05-17 03:43:06 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=1231)[0m INFO 05-17 03:43:06 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=1452)[0m INFO 05-17 03:43:06 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 41.644 seconds
[36m(RayWorkerVllm pid=1452)[0m INFO 05-17 03:43:06 worker_manager.py:278] Prefetching delta 36 done
[36m(RayWorkerVllm pid=1231)[0m INFO 05-17 03:43:07 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 43.275 seconds
[36m(RayWorkerVllm pid=1231)[0m INFO 05-17 03:43:07 worker_manager.py:278] Prefetching delta 36 done
[36m(RayWorkerVllm pid=1452)[0m INFO 05-17 03:43:07 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 3.368 seconds
[36m(RayWorkerVllm pid=1452)[0m INFO 05-17 03:43:07 worker_manager.py:364] Main thread loading delta 36 done
[36m(RayWorkerVllm pid=1452)[0m INFO 05-17 03:43:07 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=1452)[0m INFO 05-17 03:43:07 models.py:263] [prefetching] Lossless Compression Disabled
[36m(RayWorkerVllm pid=1690)[0m INFO 05-17 03:43:08 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 37.726 seconds
[36m(RayWorkerVllm pid=1690)[0m INFO 05-17 03:43:08 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 6.425 seconds
[36m(RayWorkerVllm pid=1690)[0m INFO 05-17 03:43:08 worker_manager.py:364] Main thread loading delta 36 done
[36m(RayWorkerVllm pid=1231)[0m INFO 05-17 03:43:08 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.629 seconds
[36m(RayWorkerVllm pid=1231)[0m INFO 05-17 03:43:08 worker_manager.py:364] Main thread loading delta 36 done
[36m(RayWorkerVllm pid=1231)[0m INFO 05-17 03:43:09 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=1231)[0m INFO 05-17 03:43:09 models.py:263] [prefetching] Lossless Compression Disabled
[36m(RayWorkerVllm pid=1690)[0m INFO 05-17 03:43:08 worker_manager.py:278] Prefetching delta 36 done
[36m(RayWorkerVllm pid=1690)[0m INFO 05-17 03:43:08 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=1690)[0m INFO 05-17 03:43:08 models.py:263] [prefetching] Lossless Compression Disabled
[36m(RayWorkerVllm pid=1452)[0m WARNING 05-17 03:43:09 worker_manager.py:344] Missed prefetch, fall back to loading delta 7 now
[36m(RayWorkerVllm pid=1452)[0m WARNING 05-17 03:43:09 worker_manager.py:353] Discarding prefetching delta 7
[36m(RayWorkerVllm pid=1452)[0m INFO 05-17 03:43:09 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=1452)[0m INFO 05-17 03:43:09 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=1231)[0m WARNING 05-17 03:43:10 worker_manager.py:344] Missed prefetch, fall back to loading delta 7 now
[36m(RayWorkerVllm pid=1231)[0m WARNING 05-17 03:43:10 worker_manager.py:353] Discarding prefetching delta 7
[36m(RayWorkerVllm pid=1231)[0m INFO 05-17 03:43:10 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=1231)[0m INFO 05-17 03:43:10 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=1690)[0m WARNING 05-17 03:43:10 worker_manager.py:344] Missed prefetch, fall back to loading delta 7 now
[36m(RayWorkerVllm pid=1690)[0m WARNING 05-17 03:43:10 worker_manager.py:353] Discarding prefetching delta 7
[36m(RayWorkerVllm pid=1690)[0m INFO 05-17 03:43:10 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=1690)[0m INFO 05-17 03:43:10 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 03:43:11 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 8.757 seconds
INFO 05-17 03:43:11 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 7.410 seconds
INFO 05-17 03:43:11 worker_manager.py:364] Main thread loading delta 7 done
INFO 05-17 03:43:12 worker_manager.py:278] Prefetching delta 7 done
[36m(RayWorkerVllm pid=1452)[0m INFO 05-17 03:43:19 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 9.815 seconds
[36m(RayWorkerVllm pid=1452)[0m INFO 05-17 03:43:19 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 11.311 seconds
[36m(RayWorkerVllm pid=1452)[0m INFO 05-17 03:43:19 worker_manager.py:364] Main thread loading delta 7 done
[36m(RayWorkerVllm pid=1452)[0m INFO 05-17 03:43:19 worker_manager.py:278] Prefetching delta 7 done
[36m(RayWorkerVllm pid=1231)[0m INFO 05-17 03:43:21 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 10.437 seconds
[36m(RayWorkerVllm pid=1231)[0m INFO 05-17 03:43:21 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 12.193 seconds
[36m(RayWorkerVllm pid=1231)[0m INFO 05-17 03:43:21 worker_manager.py:364] Main thread loading delta 7 done
[36m(RayWorkerVllm pid=1231)[0m INFO 05-17 03:43:21 worker_manager.py:278] Prefetching delta 7 done
[36m(RayWorkerVllm pid=1690)[0m INFO 05-17 03:43:23 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 12.904 seconds
[36m(RayWorkerVllm pid=1690)[0m INFO 05-17 03:43:23 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 14.762 seconds
[36m(RayWorkerVllm pid=1690)[0m INFO 05-17 03:43:23 worker_manager.py:364] Main thread loading delta 7 done
[36m(RayWorkerVllm pid=1690)[0m INFO 05-17 03:43:23 worker_manager.py:278] Prefetching delta 7 done
INFO 05-17 03:43:25 metrics.py:276] Avg prompt throughput: 0.3 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 7 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.2%, CPU KV cache usage: 0.0%
INFO 05-17 03:43:25 worker_manager.py:332] Adding delta 4 to prefetching queue: [4]
INFO 05-17 03:43:25 worker_manager.py:332] Adding delta 56 to prefetching queue: [4, 56]
WARNING 05-17 03:43:25 worker_manager.py:344] Missed prefetch, fall back to loading delta 4 now
INFO 05-17 03:43:25 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 03:43:25 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=1231)[0m INFO 05-17 03:43:25 worker_manager.py:332] Adding delta 4 to prefetching queue: [4]
[36m(RayWorkerVllm pid=1231)[0m WARNING 05-17 03:43:25 worker_manager.py:344] Missed prefetch, fall back to loading delta 4 now
[36m(RayWorkerVllm pid=1231)[0m INFO 05-17 03:43:25 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=1231)[0m INFO 05-17 03:43:25 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=1452)[0m INFO 05-17 03:43:25 worker_manager.py:332] Adding delta 4 to prefetching queue: [4]
[36m(RayWorkerVllm pid=1452)[0m WARNING 05-17 03:43:25 worker_manager.py:344] Missed prefetch, fall back to loading delta 4 now
[36m(RayWorkerVllm pid=1452)[0m INFO 05-17 03:43:25 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=1452)[0m INFO 05-17 03:43:25 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=1690)[0m INFO 05-17 03:43:25 worker_manager.py:332] Adding delta 4 to prefetching queue: [4]
[36m(RayWorkerVllm pid=1690)[0m WARNING 05-17 03:43:25 worker_manager.py:344] Missed prefetch, fall back to loading delta 4 now
[36m(RayWorkerVllm pid=1690)[0m INFO 05-17 03:43:25 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=1690)[0m INFO 05-17 03:43:25 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=1231)[0m INFO 05-17 03:43:36 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 11.486 seconds
[36m(RayWorkerVllm pid=1231)[0m INFO 05-17 03:43:36 worker_manager.py:364] Main thread loading delta 4 done
[36m(RayWorkerVllm pid=1690)[0m INFO 05-17 03:43:37 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 12.602 seconds
[36m(RayWorkerVllm pid=1690)[0m INFO 05-17 03:43:37 worker_manager.py:364] Main thread loading delta 4 done
INFO 05-17 03:43:40 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 15.091 seconds
INFO 05-17 03:43:40 worker_manager.py:364] Main thread loading delta 4 done
INFO 05-17 03:43:40 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 03:43:40 models.py:263] [prefetching] Lossless Compression Disabled
[36m(RayWorkerVllm pid=1452)[0m INFO 05-17 03:43:40 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 15.526 seconds
[36m(RayWorkerVllm pid=1452)[0m INFO 05-17 03:43:40 worker_manager.py:364] Main thread loading delta 4 done
INFO 05-17 03:43:43 metrics.py:276] Avg prompt throughput: 6.6 tokens/s, Avg generation throughput: 0.3 tokens/s, Running: 16 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.5%, CPU KV cache usage: 0.0%
INFO:     ::1:36816 - "POST /v1/completions HTTP/1.1" 200 OK
WARNING 05-17 03:43:43 worker_manager.py:344] Missed prefetch, fall back to loading delta 56 now
WARNING 05-17 03:43:43 worker_manager.py:353] Discarding prefetching delta 56
INFO 05-17 03:43:43 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 03:43:43 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=1231)[0m INFO 05-17 03:43:43 worker_manager.py:332] Adding delta 56 to prefetching queue: [56]
[36m(RayWorkerVllm pid=1231)[0m WARNING 05-17 03:43:43 worker_manager.py:344] Missed prefetch, fall back to loading delta 56 now
[36m(RayWorkerVllm pid=1231)[0m INFO 05-17 03:43:43 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=1231)[0m INFO 05-17 03:43:43 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=1452)[0m INFO 05-17 03:43:43 worker_manager.py:332] Adding delta 56 to prefetching queue: [56]
[36m(RayWorkerVllm pid=1452)[0m WARNING 05-17 03:43:43 worker_manager.py:344] Missed prefetch, fall back to loading delta 56 now
[36m(RayWorkerVllm pid=1452)[0m INFO 05-17 03:43:43 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=1452)[0m INFO 05-17 03:43:43 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=1690)[0m INFO 05-17 03:43:43 worker_manager.py:332] Adding delta 56 to prefetching queue: [56]
[36m(RayWorkerVllm pid=1690)[0m WARNING 05-17 03:43:43 worker_manager.py:344] Missed prefetch, fall back to loading delta 56 now
[36m(RayWorkerVllm pid=1690)[0m INFO 05-17 03:43:43 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=1690)[0m INFO 05-17 03:43:43 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 03:43:53 metrics.py:276] Avg prompt throughput: 22.9 tokens/s, Avg generation throughput: 0.9 tokens/s, Running: 22 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.8%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=1231)[0m INFO 05-17 03:43:54 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 11.206 seconds
[36m(RayWorkerVllm pid=1231)[0m INFO 05-17 03:43:54 worker_manager.py:364] Main thread loading delta 56 done
INFO 05-17 03:43:57 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 16.511 seconds
INFO 05-17 03:43:57 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 13.727 seconds
INFO 05-17 03:43:57 worker_manager.py:364] Main thread loading delta 56 done
INFO 05-17 03:43:57 worker_manager.py:278] Prefetching delta 56 done
[36m(RayWorkerVllm pid=1452)[0m INFO 05-17 03:43:57 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 14.451 seconds
[36m(RayWorkerVllm pid=1452)[0m INFO 05-17 03:43:57 worker_manager.py:364] Main thread loading delta 56 done
[36m(RayWorkerVllm pid=1690)[0m INFO 05-17 03:43:58 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 15.355 seconds
[36m(RayWorkerVllm pid=1690)[0m INFO 05-17 03:43:58 worker_manager.py:364] Main thread loading delta 56 done
INFO 05-17 03:43:59 metrics.py:276] Avg prompt throughput: 38.2 tokens/s, Avg generation throughput: 1.1 tokens/s, Running: 22 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.8%, CPU KV cache usage: 0.0%
INFO:     ::1:36802 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 03:44:05 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 18.7 tokens/s, Running: 21 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.8%, CPU KV cache usage: 0.0%
INFO 05-17 03:44:11 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 17.8 tokens/s, Running: 21 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.9%, CPU KV cache usage: 0.0%
INFO:     ::1:36792 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 03:44:17 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 17.2 tokens/s, Running: 20 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.0%, CPU KV cache usage: 0.0%
INFO 05-17 03:44:23 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 17.0 tokens/s, Running: 20 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.1%, CPU KV cache usage: 0.0%
INFO 05-17 03:44:29 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 17.0 tokens/s, Running: 20 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.1%, CPU KV cache usage: 0.0%
INFO 05-17 03:44:34 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 17.0 tokens/s, Running: 20 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.3%, CPU KV cache usage: 0.0%
INFO:     ::1:36868 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:36814 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 03:44:40 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 16.6 tokens/s, Running: 18 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%
INFO 05-17 03:44:45 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 17.3 tokens/s, Running: 18 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%
INFO:     ::1:36790 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 03:44:51 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 16.9 tokens/s, Running: 16 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.3%, CPU KV cache usage: 0.0%
INFO:     ::1:36852 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 03:44:56 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 17.6 tokens/s, Running: 16 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.4%, CPU KV cache usage: 0.0%
INFO 05-17 03:45:01 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 17.7 tokens/s, Running: 16 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.4%, CPU KV cache usage: 0.0%
INFO:     ::1:36770 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 03:45:07 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 17.1 tokens/s, Running: 15 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.5%, CPU KV cache usage: 0.0%
INFO:     ::1:36776 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 03:45:12 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 17.3 tokens/s, Running: 14 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.4%, CPU KV cache usage: 0.0%
INFO 05-17 03:45:17 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 17.8 tokens/s, Running: 14 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.5%, CPU KV cache usage: 0.0%
INFO 05-17 03:45:23 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 15.7 tokens/s, Running: 14 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.6%, CPU KV cache usage: 0.0%
INFO:     ::1:36806 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 03:45:28 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 18.7 tokens/s, Running: 13 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.5%, CPU KV cache usage: 0.0%
INFO:     ::1:36842 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 03:45:34 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 16.2 tokens/s, Running: 12 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.6%, CPU KV cache usage: 0.0%
INFO:     ::1:36834 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:36778 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 03:45:39 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 14.3 tokens/s, Running: 9 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%
INFO:     ::1:36812 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 03:45:45 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.9 tokens/s, Running: 9 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.3%, CPU KV cache usage: 0.0%
INFO:     ::1:36798 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 03:45:50 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 12.6 tokens/s, Running: 8 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%
INFO 05-17 03:45:55 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 12.3 tokens/s, Running: 8 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.3%, CPU KV cache usage: 0.0%
INFO 05-17 03:46:00 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 12.3 tokens/s, Running: 8 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.3%, CPU KV cache usage: 0.0%
INFO:     ::1:36752 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 03:46:05 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 11.3 tokens/s, Running: 7 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%
INFO 05-17 03:46:10 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 10.9 tokens/s, Running: 7 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%
INFO 05-17 03:46:16 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 10.9 tokens/s, Running: 7 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.3%, CPU KV cache usage: 0.0%
INFO 05-17 03:46:21 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 10.8 tokens/s, Running: 7 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.4%, CPU KV cache usage: 0.0%
INFO:     ::1:36746 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 03:46:26 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 11.3 tokens/s, Running: 6 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%
INFO:     ::1:36862 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 03:46:31 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 10.7 tokens/s, Running: 5 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.1%, CPU KV cache usage: 0.0%
INFO 05-17 03:46:36 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 9.7 tokens/s, Running: 5 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.1%, CPU KV cache usage: 0.0%
INFO 05-17 03:46:42 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 9.7 tokens/s, Running: 5 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%
INFO:     ::1:36760 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 03:46:47 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 10.3 tokens/s, Running: 4 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.0%, CPU KV cache usage: 0.0%
INFO 05-17 03:46:52 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 10.5 tokens/s, Running: 4 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.0%, CPU KV cache usage: 0.0%
INFO 05-17 03:46:58 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 10.6 tokens/s, Running: 4 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.1%, CPU KV cache usage: 0.0%
INFO:     ::1:36786 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 03:47:03 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 9.0 tokens/s, Running: 3 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.9%, CPU KV cache usage: 0.0%
INFO 05-17 03:47:08 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 8.3 tokens/s, Running: 3 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.9%, CPU KV cache usage: 0.0%
INFO 05-17 03:47:13 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 7.9 tokens/s, Running: 3 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.0%, CPU KV cache usage: 0.0%
INFO:     ::1:36828 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 03:47:18 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 6.4 tokens/s, Running: 2 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.7%, CPU KV cache usage: 0.0%
INFO:     ::1:36766 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 03:47:24 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 5.2 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.4%, CPU KV cache usage: 0.0%
INFO 05-17 03:47:29 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.1 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.4%, CPU KV cache usage: 0.0%
INFO 05-17 03:47:34 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.1 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.4%, CPU KV cache usage: 0.0%
INFO 05-17 03:47:39 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.4%, CPU KV cache usage: 0.0%
INFO 05-17 03:47:44 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.1 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.5%, CPU KV cache usage: 0.0%
INFO 05-17 03:47:49 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.1 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.5%, CPU KV cache usage: 0.0%
INFO 05-17 03:47:55 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.1 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.5%, CPU KV cache usage: 0.0%
INFO 05-17 03:48:00 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.5%, CPU KV cache usage: 0.0%
INFO 05-17 03:48:05 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.5%, CPU KV cache usage: 0.0%
INFO:     ::1:36818 - "POST /v1/completions HTTP/1.1" 200 OK
Results written to .artifact/benchmarks/results/048cecf7-0a34-413f-ad0c-5505ec191653.jsonl
Killing process 123993...
/var/spool/slurmd/job3676342/slurm_script: line 45: 123960 Killed                  apptainer run --nv --home /mnt/petrelfs/huqinghao/xzyao/:/home/xiayao --bind /mnt/petrelfs/huqinghao/xzyao/code/vllm:/vllm --bind /mnt/petrelfs/huqinghao/xzyao/code/triteia:/triteia --env PYTHONPATH=/vllm:/triteia --env CUDA_LAUNCH_BLOCKING=1 --env TVM_TARGET=nvidia/nvidia-a100 --env TRANSFORMERS_OFFLINE=1 --env NUMEXPR_MAX_THREADS=128 --env USE_BITBLAS=1 --env BITBLAS_TARGET=nvidia/nvidia-a100 --env RAY_DEDUP_LOGS=0 --workdir /vllm /mnt/petrelfs/huqinghao/xzyao/images/vllm-0.4.1.sif python3 /vllm/vllm/entrypoints/openai/api_server.py --model /vllm/.idea/full_models/Llama-2-13b-hf --enable-delta --disable-log-requests --gpu-memory-utilization 0.85 --delta-modules delta-1=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-1 delta-2=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-2 delta-3=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-3 delta-4=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-4 delta-5=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-5 delta-6=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-6 delta-7=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-7 delta-8=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-8 delta-9=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-9 delta-10=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-10 delta-11=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-11 delta-12=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-12 delta-13=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-13 delta-14=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-14 delta-15=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-15 delta-16=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-16 delta-17=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-17 delta-18=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-18 delta-19=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-19 delta-20=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-20 delta-21=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-21 delta-22=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-22 delta-23=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-23 delta-24=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-24 delta-25=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-25 delta-26=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-26 delta-27=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-27 delta-28=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-28 delta-29=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-29 delta-30=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-30 delta-31=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-31 delta-32=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-32 delta-33=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-33 delta-34=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-34 delta-35=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-35 delta-36=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-36 delta-37=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-37 delta-38=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-38 delta-39=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-39 delta-40=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-40 delta-41=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-41 delta-42=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-42 delta-43=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-43 delta-44=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-44 delta-45=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-45 delta-46=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-46 delta-47=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-47 delta-48=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-48 delta-49=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-49 delta-50=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-50 delta-51=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-51 delta-52=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-52 delta-53=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-53 delta-54=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-54 delta-55=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-55 delta-56=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-56 delta-57=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-57 delta-58=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-58 delta-59=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-59 delta-60=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-60 delta-61=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-61 delta-62=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-62 delta-63=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-63 delta-64=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-64 --max-deltas 24 --tensor-parallel-size 4 --enforce-eager --enable-prefetch
